-- UnityBridge/TransformAnimator
-- Drives simple looping transform animations (spin, bob, tilt) on non-skeletal
-- objects like collectibles and obstacles. Generated by animation_converter.py
-- from Unity Legacy Animation components and .anim files.
--
-- Usage:
--   local TA = require(ReplicatedStorage.UnityBridge.TransformAnimator)
--   local config = require(ReplicatedStorage:WaitForChild("Pickup_TransformAnimConfig"))
--   local animator = TA.new(pickupModel, config)
--   -- Runs automatically via shared Heartbeat. Call :Destroy() to stop.
--
-- Config table format:
--   {
--     loop = true,
--     duration = 2.0,
--     curves = {
--       position = { {time=0, value=Vector3.new(0,0.5,0)}, {time=1, value=Vector3.new(0,0.4,0)}, ... },
--       euler = { {time=0, value=Vector3.new(0,0,33.458)}, {time=2, value=Vector3.new(0,360,0)}, ... },
--       scale = { {time=0, value=Vector3.new(1,1,1)}, ... },
--     },
--   }

local RunService = game:GetService("RunService")

-- All active TransformAnimator instances, ticked by one shared Heartbeat connection
local _allInstances: { [number]: any } = {}
local _heartbeatConnection = nil

local TransformAnimator = {}
TransformAnimator.__index = TransformAnimator

function TransformAnimator.new(partOrModel, config)
	local self = setmetatable({}, TransformAnimator)

	-- Accept Part or Model
	if partOrModel:IsA("Model") then
		self._pivot = partOrModel
		self._isModel = true
	else
		self._pivot = partOrModel
		self._isModel = false
	end

	self._config = config
	self._baseCFrame = self._isModel and partOrModel:GetPivot() or partOrModel.CFrame
	self._baseSize = not self._isModel and partOrModel.Size or nil
	self._elapsed = 0
	self._duration = config.duration or 1
	self._loop = config.loop ~= false -- default true
	self._finished = false

	-- Pre-process curves into sorted arrays for fast lookup
	self._curves = {}
	for curveType, keyframes in pairs(config.curves or {}) do
		local sorted = {}
		for _, kf in ipairs(keyframes) do
			table.insert(sorted, { time = kf.time, value = kf.value })
		end
		table.sort(sorted, function(a, b) return a.time < b.time end)
		self._curves[curveType] = sorted
	end

	-- Register for shared tick
	table.insert(_allInstances, self)
	TransformAnimator._ensureHeartbeat()

	return self
end

-- -----------------------------------------------------------------------
-- Keyframe interpolation
-- -----------------------------------------------------------------------

local function lerpVector3(a: Vector3, b: Vector3, t: number): Vector3
	return a + (b - a) * t
end

local function evaluateCurve(keyframes, time): Vector3?
	if not keyframes or #keyframes == 0 then
		return nil
	end

	-- Before first keyframe: return first value
	if time <= keyframes[1].time then
		return keyframes[1].value
	end

	-- After last keyframe: return last value
	if time >= keyframes[#keyframes].time then
		return keyframes[#keyframes].value
	end

	-- Find surrounding keyframes and lerp
	for i = 1, #keyframes - 1 do
		local kf0 = keyframes[i]
		local kf1 = keyframes[i + 1]
		if time >= kf0.time and time <= kf1.time then
			local span = kf1.time - kf0.time
			local t = if span > 0 then (time - kf0.time) / span else 0
			return lerpVector3(kf0.value, kf1.value, t)
		end
	end

	return keyframes[#keyframes].value
end

-- -----------------------------------------------------------------------
-- Per-frame update (called from shared Heartbeat)
-- -----------------------------------------------------------------------

function TransformAnimator:Update(dt)
	if self._finished then return end

	self._elapsed += dt

	local time = self._elapsed
	if self._loop then
		time = time % self._duration
	elseif time >= self._duration then
		time = self._duration
		self._finished = true
	end

	-- Evaluate each curve type
	local posOffset = evaluateCurve(self._curves.position, time)
	local eulerAngles = evaluateCurve(self._curves.euler, time)
	local scaleValue = evaluateCurve(self._curves.scale, time)

	-- Compose final CFrame: base + position offset + rotation
	local cf = self._baseCFrame

	if posOffset then
		cf = cf * CFrame.new(posOffset)
	end

	if eulerAngles then
		-- Unity Euler angles are in degrees; CFrame.Angles expects radians
		local rx = math.rad(eulerAngles.X)
		local ry = math.rad(eulerAngles.Y)
		local rz = math.rad(eulerAngles.Z)
		cf = cf * CFrame.Angles(rx, ry, rz)
	end

	-- Apply CFrame
	if self._isModel then
		self._pivot:PivotTo(cf)
	else
		self._pivot.CFrame = cf
	end

	-- Apply scale if present (only for Parts, not Models)
	if scaleValue and self._baseSize then
		self._pivot.Size = Vector3.new(
			self._baseSize.X * scaleValue.X,
			self._baseSize.Y * scaleValue.Y,
			self._baseSize.Z * scaleValue.Z
		)
	end
end

-- -----------------------------------------------------------------------
-- Cleanup
-- -----------------------------------------------------------------------

function TransformAnimator:Destroy()
	-- Remove from tick list
	for i, inst in ipairs(_allInstances) do
		if inst == self then
			table.remove(_allInstances, i)
			break
		end
	end

	-- Restore original transform
	if self._isModel then
		self._pivot:PivotTo(self._baseCFrame)
	else
		self._pivot.CFrame = self._baseCFrame
		if self._baseSize then
			self._pivot.Size = self._baseSize
		end
	end

	-- Disconnect heartbeat if no instances left
	if #_allInstances == 0 and _heartbeatConnection then
		_heartbeatConnection:Disconnect()
		_heartbeatConnection = nil
	end
end

-- -----------------------------------------------------------------------
-- Shared Heartbeat (one connection drives all instances)
-- -----------------------------------------------------------------------

function TransformAnimator._ensureHeartbeat()
	if _heartbeatConnection then return end

	_heartbeatConnection = RunService.Heartbeat:Connect(function(dt)
		for _, inst in ipairs(_allInstances) do
			inst:Update(dt)
		end
	end)
end

return TransformAnimator
