"""FPS scaffolding — opt-in via ``--scaffolding=fps``.

Emits an FPS client controller (mouse-look, WASD, raycast shoot), a
HUD ScreenGui (health bar, ammo counter, item indicators, pause menu),
and an HUD client LocalScript that wires HUDController-shaped
RemoteEvents/BindableEvents into the HUD elements.

Pipeline gate lives in
:meth:`converter.pipeline.Pipeline._subphase_inject_autogen_scripts`:
the FPS scripts only get appended when ``"fps" in self.scaffolding``.
The previous gate auto-detected FPS games via ``detect_fps_game`` and
ran on every matching project, sweeping up converted projects whose
scripts happened to match the heuristic. The opt-in flag keeps non-FPS
projects (Gamekit3D, BoatAttack, ChopChop, RedRunner) free of unwanted
UI/input scripts.

This module was split out of ``fps_client_generator.py`` so the
converter's generic autogen scripts (collision groups, GameServerManager,
CollisionFidelityRecook) live in :mod:`converter.autogen` while genre-
specific scaffolding lives under :mod:`converter.scaffolding`.
"""
from __future__ import annotations

import logging
from pathlib import Path

from core.roblox_types import RbxScript, RbxScreenGui, RbxUIElement, RbxPlace

log = logging.getLogger(__name__)

# Filesystem location of the AutoFpsEventDispatch ModuleScript body.
# Lives at the top of ``converter/runtime/`` (no ``gameplay/`` subdir) —
# matches the pre-PR-#75 layout that PR #80 restored.
_EVENT_DISPATCH_LUAU = (
    Path(__file__).resolve().parent.parent.parent / "runtime" / "event_dispatch.luau"
)


def detect_fps_game(place: RbxPlace) -> bool:
    """Check if the transpiled scripts indicate an FPS-style game.

    Looks for shooting mechanics (raycast-based), health/ammo systems,
    or RemoteEvent-based FPS patterns. Skips converter-generated
    scripts (carrying any of ``_AUTOGEN_MARKERS``) so the heuristic
    fires on user content, not on the auto-injected
    ``GameServerManager`` whose generic spawn-flow code mentions
    ``PlayerShoot`` + ``RemoteEvent``.
    """
    for script in place.scripts:
        src = script.source
        # Skip auto-generated scripts — their content can match the
        # heuristic even on non-FPS conversions.
        head = src[:512]
        if any(m in head for m in _AUTOGEN_MARKERS):
            continue
        src_lower = src.lower()
        # Server-authoritative FPS (RemoteEvent pattern)
        if "PlayerShoot" in src and "RemoteEvent" in src:
            return True
        # Client-side FPS (direct shooting via Raycast + ammo tracking)
        if "Raycast" in src and ("curAmmo" in src or "ammo" in src_lower) and "shoot" in src_lower:
            return True
        # FPS with health + weapon pickup
        if "curHealth" in src and "gotWeapon" in src and "Raycast" in src:
            return True
    return False


# Marker substrings at the top of converter-emitted scripts. The
# detector skips files carrying any of these — kept synchronised
# with ``Pipeline._AUTOGEN_MARKERS``; if a new auto-gen script type
# is added, append its canonical header here too.
_AUTOGEN_MARKERS: tuple[str, ...] = (
    "-- HUD Controller (auto-generated)",
    "-- FPS Client Controller (auto-generated)",
    "-- CollisionFidelityRecook (auto-generated)",
    "-- CollisionGroup Setup (auto-generated from Unity layers)",
    "-- Game Server Manager (auto-generated by Unity converter)",
    "-- EventDispatch: cross-class connect helper",
    "-- Auto-generated bootstrap:",
    "-- Auto-generated animation script",
    "-- Auto-generated Animator State Machine",
    "-- Auto-generated mesh loader",
)


def _has_client_fps_controller(place: RbxPlace) -> bool:
    """Check if a client-side FPS controller already exists.

    Checks both LocalScripts (auto-run) and ModuleScripts that handle
    FPS mechanics (camera, shooting, movement). ModuleScripts count
    because they get required by the ClientBootstrap LocalScript.
    """
    for script in place.scripts:
        src = script.source
        st = getattr(script, "script_type", "")

        # LocalScript with direct FPS input handling
        if st == "LocalScript" and "UserInputService" in src and "MouseButton1" in src:
            if "Raycast" in src or "shoot" in src.lower():
                return True

        # ModuleScript with FPS mechanics (camera + shooting + movement)
        if st == "ModuleScript" and "RenderStepped" in src:
            has_camera = "CameraType" in src or "updateCamera" in src
            has_shooting = "Raycast" in src or "shoot" in src.lower()
            has_movement = "Move(" in src or "Humanoid" in src
            if has_camera and has_shooting and has_movement:
                return True

    return False


def _has_hud_screen_gui(place: RbxPlace) -> bool:
    """Check if a HUD ScreenGui already exists from Canvas conversion."""
    for sg in place.screen_guis:
        if sg.name == "HUD":
            return True
    return False


def generate_fps_client_script() -> RbxScript:
    """Generate a LocalScript that handles FPS input: mouse look, shooting, item pickup."""
    source = '''\
-- FPS Client Controller (auto-generated)
-- Handles mouse look, shooting input, and item pickup triggers.

local Players = game:GetService("Players")
local UserInputService = game:GetService("UserInputService")
local RunService = game:GetService("RunService")
local ReplicatedStorage = game:GetService("ReplicatedStorage")

local player = Players.LocalPlayer
local mouse = player:GetMouse()

-- Remote events (created by server Player script)
local function waitForRemote(name)
    return ReplicatedStorage:WaitForChild(name, 10)
end

local ShootRemote = waitForRemote("PlayerShoot")
local GetItemRemote = waitForRemote("PlayerGetItem")

-- Mouse lock for FPS
UserInputService.MouseBehavior = Enum.MouseBehavior.LockCenter
UserInputService.MouseIconEnabled = false

-- Camera variables
local SENSITIVITY = 0.002
local pitchAngle = 0
local yawAngle = 0
local MAX_PITCH = math.rad(80)

-- First-person camera: follow character head with mouse look
local camera = workspace.CurrentCamera
camera.CameraType = Enum.CameraType.Scriptable

local function updateCamera()
	local character = player.Character
	if not character then return end
	local head = character:FindFirstChild("Head")
	if not head then return end

	local delta = UserInputService:GetMouseDelta()
	yawAngle = yawAngle - delta.X * SENSITIVITY
	pitchAngle = math.clamp(pitchAngle - delta.Y * SENSITIVITY, -MAX_PITCH, MAX_PITCH)

	local headPos = head.Position + Vector3.new(0, 0.5, 0)
	camera.CFrame = CFrame.new(headPos)
		* CFrame.Angles(0, yawAngle, 0)
		* CFrame.Angles(pitchAngle, 0, 0)
end

RunService.RenderStepped:Connect(updateCamera)

-- Viewmodel gun (simple block representation attached to camera)
local gunModel = Instance.new("Part")
gunModel.Name = "Viewmodel"
gunModel.Size = Vector3.new(0.3, 0.3, 1.5)
gunModel.Color = Color3.fromRGB(60, 60, 60)
gunModel.Material = Enum.Material.Metal
gunModel.Anchored = true
gunModel.CanCollide = false
gunModel.CastShadow = false
gunModel.Parent = camera

-- Muzzle flash light
local muzzleFlash = Instance.new("PointLight")
muzzleFlash.Color = Color3.fromRGB(255, 200, 100)
muzzleFlash.Brightness = 3
muzzleFlash.Range = 8
muzzleFlash.Enabled = false
muzzleFlash.Parent = gunModel

-- Shoot sound
local shootSound = Instance.new("Sound")
shootSound.SoundId = "rbxasset://sounds/impact_explosion_03.mp3"
shootSound.Volume = 0.5
shootSound.PlaybackSpeed = 1.5
shootSound.Parent = gunModel

-- Update gun position each frame (follows camera)
local function updateGun()
	if not camera then return end
	local cf = camera.CFrame
	-- Position gun at bottom-right of view
	gunModel.CFrame = cf * CFrame.new(0.5, -0.4, -1.2)
end
RunService.RenderStepped:Connect(updateGun)

-- Shooting
local SHOOT_COOLDOWN = 0.15
local lastShot = 0

UserInputService.InputBegan:Connect(function(input, gameProcessed)
    if gameProcessed or isPaused then return end

    if input.UserInputType == Enum.UserInputType.MouseButton1 then
        local now = tick()
        if now - lastShot < SHOOT_COOLDOWN then return end
        lastShot = now

        if not camera then return end

        local origin = camera.CFrame.Position
        local direction = camera.CFrame.LookVector

        -- Play shoot effects
        shootSound:Play()
        muzzleFlash.Enabled = true
        task.delay(0.05, function() muzzleFlash.Enabled = false end)

        -- Recoil effect (brief camera kick)
        pitchAngle = pitchAngle + math.rad(1.5)

        if ShootRemote then
            ShootRemote:FireServer(origin, direction)
        end
    end
end)

-- ESC to toggle pause
local isPaused = false
UserInputService.InputBegan:Connect(function(input, gameProcessed)
    if input.KeyCode == Enum.KeyCode.Escape then
        isPaused = not isPaused
        if isPaused then
            UserInputService.MouseBehavior = Enum.MouseBehavior.Default
            UserInputService.MouseIconEnabled = true
            camera.CameraType = Enum.CameraType.Custom
        else
            UserInputService.MouseBehavior = Enum.MouseBehavior.LockCenter
            UserInputService.MouseIconEnabled = false
            camera.CameraType = Enum.CameraType.Scriptable
        end
    end
end)

-- WASD movement direction relative to camera facing
local function getMovementDirection()
    local moveDir = Vector3.zero
    if UserInputService:IsKeyDown(Enum.KeyCode.W) then
        moveDir = moveDir + Vector3.new(0, 0, -1)
    end
    if UserInputService:IsKeyDown(Enum.KeyCode.S) then
        moveDir = moveDir + Vector3.new(0, 0, 1)
    end
    if UserInputService:IsKeyDown(Enum.KeyCode.A) then
        moveDir = moveDir + Vector3.new(-1, 0, 0)
    end
    if UserInputService:IsKeyDown(Enum.KeyCode.D) then
        moveDir = moveDir + Vector3.new(1, 0, 0)
    end
    if moveDir.Magnitude > 0 then
        -- Rotate movement direction by camera yaw
        moveDir = (CFrame.Angles(0, yawAngle, 0) * moveDir).Unit
    end
    return moveDir
end

-- Apply movement direction to humanoid + jump support
RunService.Heartbeat:Connect(function()
    local character = player.Character
    if not character or isPaused then return end
    local humanoid = character:FindFirstChildOfClass("Humanoid")
    if not humanoid then return end
    humanoid:Move(getMovementDirection())
end)

-- Jump on space
UserInputService.InputBegan:Connect(function(input, gameProcessed)
    if gameProcessed or isPaused then return end
    if input.KeyCode == Enum.KeyCode.Space then
        local character = player.Character
        if character then
            local humanoid = character:FindFirstChildOfClass("Humanoid")
            if humanoid then
                humanoid.Jump = true
            end
        end
    end
end)

-- Item pickup handling
-- Detect pickups by both name pattern and IsPickup attribute for flexibility.
-- The server Pickup script handles the actual touch-based collection;
-- this client-side code highlights nearby pickups and handles UI feedback.

local function isPickupPart(part)
    -- Check attribute first (set by converter for prefab instances)
    if part:GetAttribute("IsPickup") then
        return true
    end
    -- Fallback: check if name contains "Pickup" (case-insensitive)
    if string.find(string.lower(part.Name), "pickup") then
        return true
    end
    -- Check parent Model name
    if part.Parent and part.Parent:IsA("Model") then
        if part.Parent:GetAttribute("IsPickup") then
            return true
        end
        if string.find(string.lower(part.Parent.Name), "pickup") then
            return true
        end
    end
    return false
end

local function isSpawnPoint(part)
    if part:GetAttribute("IsSpawnPoint") then
        return true
    end
    if string.find(string.lower(part.Name), "spawnpoint") or string.find(string.lower(part.Name), "spawn_point") then
        return true
    end
    if part.Name == "SpawnPoint" then
        return true
    end
    return false
end

-- Highlight nearby pickups with a SelectionBox (visual feedback)
local character = player.Character or player.CharacterAdded:Wait()
local function setupPickupHighlights()
    for _, obj in ipairs(workspace:GetDescendants()) do
        if obj:IsA("BasePart") and isPickupPart(obj) then
            local highlight = Instance.new("Highlight")
            highlight.Name = "PickupHighlight"
            highlight.FillColor = Color3.new(1, 1, 0.3)
            highlight.FillTransparency = 0.7
            highlight.OutlineTransparency = 0.5
            highlight.Adornee = obj.Parent:IsA("Model") and obj.Parent or obj
            highlight.Parent = obj.Parent:IsA("Model") and obj.Parent or obj
        end
    end
end

task.defer(setupPickupHighlights)
'''
    return RbxScript(
        name="FPSController",
        source=source,
        script_type="LocalScript",
    )




def generate_hud_screen_gui() -> RbxScreenGui:
    """Generate a ScreenGui with health bar, ammo counter, crosshair, and item indicators."""

    # Crosshair (center dot)
    crosshair = RbxUIElement(
        class_name="TextLabel",
        name="Crosshair",
        position=(0.5, -4, 0.5, -4),
        size=(0, 8, 0, 8),
        background_color=(1, 1, 1),
        background_transparency=0.0,
        text="+",
        text_color=(1, 1, 1),
        text_size=18,
    )

    # Health bar background
    health_fill = RbxUIElement(
        class_name="Frame",
        name="Fill",
        position=(0, 0, 0, 0),
        size=(1, 0, 1, 0),
        background_color=(0.2, 0.8, 0.2),
        background_transparency=0.0,
    )

    health_bar = RbxUIElement(
        class_name="Frame",
        name="Health",
        position=(0, 10, 1, -50),
        size=(0, 200, 0, 20),
        background_color=(0.3, 0.3, 0.3),
        background_transparency=0.3,
        children=[health_fill],
    )

    # Ammo counter
    ammo_cur = RbxUIElement(
        class_name="TextLabel",
        name="Cur",
        position=(0, 0, 0, 0),
        size=(0.45, 0, 1, 0),
        background_transparency=1.0,
        text="0",
        text_color=(1, 1, 1),
        text_size=24,
    )

    ammo_slash = RbxUIElement(
        class_name="TextLabel",
        name="Slash",
        position=(0.45, 0, 0, 0),
        size=(0.1, 0, 1, 0),
        background_transparency=1.0,
        text="/",
        text_color=(0.7, 0.7, 0.7),
        text_size=20,
    )

    ammo_total = RbxUIElement(
        class_name="TextLabel",
        name="Total",
        position=(0.55, 0, 0, 0),
        size=(0.45, 0, 1, 0),
        background_transparency=1.0,
        text="250",
        text_color=(0.7, 0.7, 0.7),
        text_size=20,
    )

    ammo_frame = RbxUIElement(
        class_name="Frame",
        name="Ammo",
        position=(1, -160, 1, -50),
        size=(0, 150, 0, 30),
        background_color=(0.1, 0.1, 0.1),
        background_transparency=0.5,
        children=[ammo_cur, ammo_slash, ammo_total],
    )

    # Item indicators (battery, small battery, medium battery, gas can)
    item_names = ["Battery", "SmallBattery", "MediumBattery", "GasCan"]
    item_children = []
    for i, item_name in enumerate(item_names):
        indicator = RbxUIElement(
            class_name="TextLabel",
            name=item_name,
            position=(0, i * 80, 0, 0),
            size=(0, 75, 0, 30),
            background_color=(0.2, 0.2, 0.2),
            background_transparency=0.5,
            text=item_name,
            text_color=(0.6, 0.6, 0.6),
            text_size=11,
        )
        item_children.append(indicator)

    item_module = RbxUIElement(
        class_name="Frame",
        name="ItemModule",
        position=(0.5, -160, 1, -50),
        size=(0, 320, 0, 30),
        background_transparency=1.0,
        children=item_children,
    )

    # Pause menu (hidden by default)
    resume_button = RbxUIElement(
        class_name="TextButton",
        name="ResumeButton",
        position=(0.5, -75, 0.5, -20),
        size=(0, 150, 0, 40),
        background_color=(0.2, 0.6, 0.2),
        background_transparency=0.0,
        text="Resume",
        text_color=(1, 1, 1),
        text_size=18,
    )

    pause_menu = RbxUIElement(
        class_name="Frame",
        name="Pause",
        position=(0, 0, 0, 0),
        size=(1, 0, 1, 0),
        background_color=(0, 0, 0),
        background_transparency=0.5,
        visible=False,
        children=[resume_button],
    )

    # Main HUD container (Module)
    module = RbxUIElement(
        class_name="Frame",
        name="Module",
        position=(0, 0, 0, 0),
        size=(1, 0, 1, 0),
        background_transparency=1.0,
        children=[health_bar, ammo_frame],
    )

    screen_gui = RbxScreenGui(name="HUD")
    screen_gui.elements = [crosshair, module, item_module, pause_menu]
    # Marker attribute so opt-out cleanup can distinguish this
    # auto-gen ScreenGui from a user-authored "HUD" ScreenGui (e.g.
    # one produced by Canvas/UI conversion). Without it, dropping
    # by name alone would delete legitimate non-FPS HUDs that
    # happen to share the name.
    screen_gui.attributes["_AutoFpsHud"] = True

    return screen_gui




def generate_hud_client_script() -> RbxScript:
    """Generate a LocalScript that updates the HUD based on RemoteEvents from the server."""
    source = '''\
-- HUD Controller (auto-generated)
-- Updates health bar, ammo counter, and item indicators from server events.
-- Adapts to both auto-generated and Canvas-converted HUD layouts.

local Players = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local UserInputService = game:GetService("UserInputService")

local player = Players.LocalPlayer
local playerGui = player:WaitForChild("PlayerGui")
local hudGui = playerGui:WaitForChild("HUD", 10)

if not hudGui then
    warn("HUD ScreenGui not found")
    return
end

local module = hudGui:FindFirstChild("Module")
local itemModule = hudGui:FindFirstChild("ItemModule")

-- Find health fill element (adapts to different HUD layouts)
local healthFill = nil
if module then
    local healthBar = module:FindFirstChild("Health")
    if healthBar then
        -- Try Canvas-converted layout: Health > Back > CurHealth
        local back = healthBar:FindFirstChild("Back")
        if back then
            healthFill = back:FindFirstChild("CurHealth")
        end
        -- Try auto-generated layout: Health > Fill
        if not healthFill then
            healthFill = healthBar:FindFirstChild("Fill")
        end
    end
end

-- Find ammo text element
local ammoCur = nil
if module then
    local ammoFrame = module:FindFirstChild("Ammo")
    if ammoFrame then
        ammoCur = ammoFrame:FindFirstChild("Cur")
    end
end

local MAX_HEALTH = 100

-- Wait for remote events from server
local function waitForRemote(name)
    return ReplicatedStorage:WaitForChild(name, 10)
end

-- The producer side may be either a server RemoteEvent (FireClient) or
-- a client-side BindableEvent (e.g. published by Player.luau via the
-- hud_player_bindable_events coherence pack). They expose different
-- event members — RemoteEvent.OnClientEvent vs BindableEvent.Event —
-- so the dispatch helper forks on the instance class. Lives in the
-- shared ``AutoFpsEventDispatch`` runtime module — distinct name to
-- avoid colliding with user-authored ``EventDispatch.cs`` projects.
local EventDispatch = require(ReplicatedStorage:WaitForChild("AutoFpsEventDispatch"))
local connectClient = EventDispatch.connectClient

local HealthUpdateRemote = waitForRemote("HealthUpdate")
local AmmoUpdateRemote = waitForRemote("AmmoUpdate")
local ItemUpdateRemote = waitForRemote("ItemUpdate")

-- Health update
if HealthUpdateRemote and healthFill then
    connectClient(HealthUpdateRemote, function(curHealth)
        local pct = math.clamp(curHealth / MAX_HEALTH, 0, 1)
        healthFill.Size = UDim2.new(pct, 0, 1, 0)

        -- Color shift: green -> yellow -> red
        if pct > 0.5 then
            healthFill.BackgroundColor3 = Color3.new(0.2, 0.8, 0.2)
        elseif pct > 0.25 then
            healthFill.BackgroundColor3 = Color3.new(0.9, 0.7, 0.1)
        else
            healthFill.BackgroundColor3 = Color3.new(0.9, 0.2, 0.2)
        end
    end)
end

-- Ammo update
if AmmoUpdateRemote and ammoCur then
    connectClient(AmmoUpdateRemote, function(curAmmo)
        ammoCur.Text = tostring(curAmmo)
    end)
end

-- Item collected
if ItemUpdateRemote and itemModule then
    connectClient(ItemUpdateRemote, function(itemName)
        local indicator = itemModule:FindFirstChild(itemName)
        if indicator then
            indicator.BackgroundColor3 = Color3.new(0.2, 0.7, 0.2)
            indicator.TextColor3 = Color3.new(1, 1, 1)
            indicator.BackgroundTransparency = 0.1
        end
    end)
end

-- Pause menu toggle
local pauseMenu = hudGui:FindFirstChild("Pause")
if pauseMenu then
    local isPaused = false
    local resumeButton = pauseMenu:FindFirstChild("ResumeButton")

    local function togglePause()
        isPaused = not isPaused
        pauseMenu.Visible = isPaused
    end

    UserInputService.InputBegan:Connect(function(input, gameProcessed)
        if input.KeyCode == Enum.KeyCode.Escape then
            togglePause()
        end
    end)

    if resumeButton then
        resumeButton.Activated:Connect(function()
            isPaused = false
            pauseMenu.Visible = false
            UserInputService.MouseBehavior = Enum.MouseBehavior.LockCenter
            UserInputService.MouseIconEnabled = false
        end)
    end
end
'''
    return RbxScript(
        # Distinct from any user-authored ``HUDController.cs`` so the
        # transpiled .luau files don't collide on disk and clobber each
        # other. The script content is unchanged from the historic
        # auto-generated copy — only the name moved.
        name="AutoFpsHudController",
        source=source,
        script_type="LocalScript",
    )




def inject_fps_scripts(place: RbxPlace) -> int:
    """Inject FPS client controller, HUD ScreenGui, and HUDController LocalScript.

    The caller is responsible for deciding whether to invoke this — the
    pipeline gates it behind ``--scaffolding=fps``. The previous gate
    auto-detected FPS games via ``detect_fps_game`` and ran on every
    matching project, sweeping up converted projects whose scripts
    happened to match the heuristic. The opt-in flag keeps non-FPS
    projects (Gamekit3D, BoatAttack, ChopChop, RedRunner) free of
    unwanted UI/input scripts.

    Returns the number of scripts/guis added.
    """
    added = 0

    # Add FPS client controller (only if AI didn't already generate one)
    if not _has_client_fps_controller(place):
        place.scripts.append(generate_fps_client_script())
        added += 1
        log.info("Injected FPS client controller LocalScript")
    else:
        log.info("Skipping FPS controller injection (AI-generated client controller already exists)")

    # Only add HUD ScreenGui if Canvas conversion didn't already create one
    if not _has_hud_screen_gui(place):
        place.screen_guis.append(generate_hud_screen_gui())
        added += 1
        log.info("Injected HUD ScreenGui")
    else:
        log.info("Skipping HUD ScreenGui injection (Canvas-converted HUD already exists)")

    # Add HUD controller LocalScript only if a previous AUTO-GENERATED
    # HUD controller isn't already present. Match by marker comment
    # rather than name alone: a pre-PR rebuild path may have rehydrated
    # the LEGACY ``HUDController.luau`` (auto-gen, with marker) from
    # disk into ``place.scripts``. Name-only matching against
    # ``AutoFpsHudController`` would miss that legacy script and append
    # a second auto-gen HUD listener — both run, double-handling
    # HealthUpdate/AmmoUpdate/ItemUpdate.
    #
    # User-authored ``HUDController.cs`` (transpiled) won't carry the
    # canonical marker, so this dedupe leaves them untouched.
    has_autogen_hud = any(
        "-- HUD Controller (auto-generated)" in s.source
        and s.name in ("AutoFpsHudController", "HUDController")
        for s in place.scripts
    )
    if not has_autogen_hud:
        place.scripts.append(generate_hud_client_script())
        added += 1
        log.info("Injected AutoFpsHudController LocalScript")
    else:
        log.info(
            "Skipping AutoFpsHudController injection (auto-generated "
            "HUD listener already present from prior conversion)"
        )

    # AutoFpsEventDispatch ModuleScript at ReplicatedStorage. The
    # generated HUD pins ``WaitForChild("AutoFpsEventDispatch")``; emit
    # the module here so a ``--scaffolding=fps`` run is self-contained.
    if not any(s.name == AUTO_FPS_EVENT_DISPATCH_NAME for s in place.scripts):
        place.scripts.append(
            RbxScript(
                name=AUTO_FPS_EVENT_DISPATCH_NAME,
                source=_EVENT_DISPATCH_LUAU.read_text(encoding="utf-8"),
                script_type="ModuleScript",
                parent_path="ReplicatedStorage",
            )
        )
        added += 1
        log.info("Injected AutoFpsEventDispatch ModuleScript")
    else:
        log.info(
            "Skipping AutoFpsEventDispatch injection (already present)"
        )

    return added


# Canonical name for the auto-injected FPS event-dispatch alias.
# Distinct from a hypothetical user-authored ``EventDispatch`` script
# so the disk write doesn't collide. The auto-generated HUDController
# requires this exact name from ``ReplicatedStorage``; the pipeline
# emits an alias at this name that proxies to the canonical
# ``ReplicatedStorage.AutoGen.EventDispatch`` ModuleScript (PR #75).
# Kept here as the authoritative string constant so HUD-side code and
# pipeline-side code can't drift.
AUTO_FPS_EVENT_DISPATCH_NAME = "AutoFpsEventDispatch"
