"""PR6: write_output hard playability guard rail tests.

Covers ``Pipeline._check_runtime_playability_guard`` -- the safety net
that lands before PR7's default ``--scene-runtime=auto`` flip. The guard
ensures that under ``generic`` / ``auto`` modes the converter cannot
silently emit a non-playable place (runtime-bearing MonoBehaviours with
no valid plan + SceneRuntime host emit).

Test matrix from the design doc (PR6 row + line ~732):
  * Guard fires only under ``generic``/``auto``; legacy +
    resume/preserved-script unaffected.
  * ``--allow-nonplayable-output`` passes through with a warning.
  * Synthetic conversion with runtime-bearing MB + valid plan + valid
    host -> write_output succeeds under generic.
  * Synthetic conversion with runtime-bearing MB but NO plan ->
    write_output fails under generic; passes under
    ``--allow-nonplayable-output`` (with warning logged).
  * Same setup under legacy -> write_output succeeds.
  * Resume path with a complete cache -> guard doesn't re-fire.

PR7 cross-reference: PR7 flips the default mode to ``auto`` and relies
on this guard to backstop projects that lack a complete contract plan.
Its e2e test (no flag passed) MUST fail pre-PR6; once PR6 lands, the
fail surface migrates to this guard's RuntimeError. PR7 should land
strictly after PR6 (the design doc's merge order says exactly that;
this guard exists to make the flip safe).
"""

from __future__ import annotations

import sys
from pathlib import Path
from unittest.mock import MagicMock

import pytest

sys.path.insert(0, str(Path(__file__).parent.parent))

from core.conversion_context import ConversionContext  # noqa: E402
from core.roblox_types import RbxPlace, RbxScript  # noqa: E402
from converter.pipeline import Pipeline  # noqa: E402


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


def _make_pipeline_with_ctx(
    tmp_path: Path,
    scene_runtime_mode: str,
    scene_runtime: dict,
    allow_nonplayable: bool = False,
) -> Pipeline:
    """Minimal Pipeline for guard unit tests (mirrors the helper in
    ``test_scene_runtime_pipeline_emit.py``)."""
    p = Pipeline.__new__(Pipeline)
    p.ctx = ConversionContext(unity_project_path=str(tmp_path / "project"))
    p.ctx.scene_runtime_mode = scene_runtime_mode
    p.ctx.scene_runtime = scene_runtime
    p.ctx.allow_nonplayable_output = allow_nonplayable
    p.output_dir = tmp_path
    p.output_dir.mkdir(parents=True, exist_ok=True)

    state = MagicMock()
    state.rbx_place = RbxPlace()
    state.rbx_place.scripts = []
    state.animation_result = None
    state.transpilation_result = None
    state.material_mappings = {}
    state.rbx_place.unconverted_components = []
    p.state = state
    return p


def _valid_runtime_plan() -> dict:
    """A planner artefact carrying one runtime-bearing module with
    every PR3b field set -- the shape ``_subphase_inject_scene_runtime``
    consumes successfully under generic."""
    return {
        "modules": {
            "guid-foo": {
                "stem": "Foo",
                "runtime_bearing": True,
                "domain": "client",
                "module_path": "ReplicatedStorage.Foo",
            },
        },
        "scenes": {},
        "prefabs": {},
        "domain_overrides": {},
    }


def _host_scripts() -> list[RbxScript]:
    """The four scripts ``_subphase_inject_scene_runtime`` emits under
    generic with a runtime-bearing plan. Tests use these to simulate a
    clean post-host-emit state without having to invoke the subphase.

    Each script carries the autogen marker the real subphase stamps so
    the guard's marker-based "is this a real autogen emit?" check
    accepts them (codex R1-P1.B fix).
    """
    return [
        RbxScript(
            name="SceneRuntime",
            source="-- scene_runtime: PR4 generic host runtime\n",
            script_type="ModuleScript",
            parent_path="ReplicatedStorage",
        ),
        RbxScript(
            name="SceneRuntimePlan",
            source=(
                "-- SceneRuntimePlan (auto-generated by Unity converter; PR4)\n"
            ),
            script_type="ModuleScript",
            parent_path="ReplicatedStorage",
        ),
        RbxScript(
            name="SceneRuntimeClient",
            source=(
                "-- SceneRuntimeClient (auto-generated; "
                "PR4 scene-runtime host entrypoint)\n"
            ),
            script_type="LocalScript",
            parent_path="StarterPlayer.StarterPlayerScripts",
        ),
        RbxScript(
            name="SceneRuntimeServer",
            source=(
                "-- SceneRuntimeServer (auto-generated; "
                "PR4 scene-runtime host entrypoint)\n"
            ),
            script_type="Script",
            parent_path="ServerScriptService",
        ),
    ]


# ---------------------------------------------------------------------------
# Mode-gating: guard is silent under legacy + the auto->legacy fallback
# ---------------------------------------------------------------------------


class TestModeGating:
    """The guard MUST NOT fire under modes that never emit the host
    runtime, regardless of plan completeness. Pre-PR6 legacy / resume
    paths are byte-stable; firing here would regress that invariant."""

    def test_legacy_mode_is_noop_even_with_runtime_bearing(self, tmp_path):
        # Worst-case legacy: a runtime-bearing module in the plan but
        # no host emit. Legacy never honors the plan; guard short-
        # circuits before it could fail this run.
        p = _make_pipeline_with_ctx(
            tmp_path, "legacy", _valid_runtime_plan(),
        )
        # No host scripts in rbx_place -- mirrors a legacy assemble.
        p._check_runtime_playability_guard()  # must not raise

    def test_auto_mode_resolves_to_legacy_before_guard(self, tmp_path):
        # _check_auto_fail_closed rewrites scene_runtime_mode to
        # "legacy" on any fail-closed signal BEFORE the guard runs.
        # Simulate the post-fallback state: mode is "legacy" by the
        # time the guard sees ctx, so the guard must not fire even
        # if the plan still carries runtime-bearing rows.
        p = _make_pipeline_with_ctx(
            tmp_path, "legacy", _valid_runtime_plan(),
        )
        p._check_runtime_playability_guard()

    def test_empty_scene_runtime_under_legacy_is_noop(self, tmp_path):
        # Legacy + no plan at all (the default pre-PR1 shape). No
        # runtime-bearing modules to worry about.
        p = _make_pipeline_with_ctx(tmp_path, "legacy", {})
        p._check_runtime_playability_guard()

    def test_generic_no_runtime_bearing_modules_is_noop(self, tmp_path):
        # Generic mode but the plan carries only non-runtime-bearing
        # rows. The host emit subphase already short-circuited; the
        # guard must follow suit.
        plan = {
            "modules": {
                "guid-helper": {
                    "stem": "Helper",
                    "runtime_bearing": False,
                },
            },
            "scenes": {}, "prefabs": {}, "domain_overrides": {},
        }
        p = _make_pipeline_with_ctx(tmp_path, "generic", plan)
        p._check_runtime_playability_guard()


# ---------------------------------------------------------------------------
# Happy path: complete plan + complete host emit -> guard passes
# ---------------------------------------------------------------------------


class TestHappyPath:

    def test_generic_with_full_plan_and_host_emit_passes(self, tmp_path):
        p = _make_pipeline_with_ctx(
            tmp_path, "generic", _valid_runtime_plan(),
        )
        for s in _host_scripts():
            p.state.rbx_place.scripts.append(s)
        # No raise -> guard accepted the playable place.
        p._check_runtime_playability_guard()

    def test_generic_server_domain_module_passes(self, tmp_path):
        plan = {
            "modules": {
                "guid-server-only": {
                    "stem": "ServerOnly",
                    "runtime_bearing": True,
                    "domain": "server",
                    "module_path": "ServerScriptService.ServerOnly",
                },
            },
            "scenes": {}, "prefabs": {}, "domain_overrides": {},
        }
        p = _make_pipeline_with_ctx(tmp_path, "generic", plan)
        for s in _host_scripts():
            p.state.rbx_place.scripts.append(s)
        p._check_runtime_playability_guard()


# ---------------------------------------------------------------------------
# Hard fail surfaces
# ---------------------------------------------------------------------------


class TestHardFailures:

    def test_no_module_plan_at_all_fails(self, tmp_path):
        # Runtime-bearing module declared with no domain / no path.
        plan = {
            "modules": {
                "guid-foo": {
                    "stem": "Foo",
                    "runtime_bearing": True,
                    # no domain, no module_path -- PR3b classifier
                    # never ran (e.g. exception in _classify_storage)
                },
            },
            "scenes": {}, "prefabs": {}, "domain_overrides": {},
        }
        p = _make_pipeline_with_ctx(tmp_path, "generic", plan)
        # Host emit also missing (the subphase's own early-out would
        # have caught a planless run; we test the combined surface).
        with pytest.raises(RuntimeError) as exc_info:
            p._check_runtime_playability_guard()
        msg = str(exc_info.value)
        assert "PR6 playability guard" in msg
        assert "Foo" in msg or "guid-foo" in msg
        assert "--allow-nonplayable-output" in msg
        assert "--scene-runtime=legacy" in msg

    def test_invalid_domain_fails(self, tmp_path):
        plan = {
            "modules": {
                "guid-bad-domain": {
                    "stem": "BadDomain",
                    "runtime_bearing": True,
                    "domain": "shared",  # invalid; valid set is {client, server}
                    "module_path": "ReplicatedStorage.BadDomain",
                },
            },
            "scenes": {}, "prefabs": {}, "domain_overrides": {},
        }
        p = _make_pipeline_with_ctx(tmp_path, "generic", plan)
        for s in _host_scripts():
            p.state.rbx_place.scripts.append(s)
        with pytest.raises(RuntimeError) as exc_info:
            p._check_runtime_playability_guard()
        assert "domain=" in str(exc_info.value)
        assert "'shared'" in str(exc_info.value)

    def test_missing_module_path_fails(self, tmp_path):
        plan = {
            "modules": {
                "guid-no-path": {
                    "stem": "NoPath",
                    "runtime_bearing": True,
                    "domain": "client",
                    # module_path missing
                },
            },
            "scenes": {}, "prefabs": {}, "domain_overrides": {},
        }
        p = _make_pipeline_with_ctx(tmp_path, "generic", plan)
        for s in _host_scripts():
            p.state.rbx_place.scripts.append(s)
        with pytest.raises(RuntimeError) as exc_info:
            p._check_runtime_playability_guard()
        assert "module_path" in str(exc_info.value)

    def test_missing_host_scripts_fails(self, tmp_path):
        # Plan is valid; the host emit never happened (e.g. host
        # runtime file deleted from disk). The guard catches the
        # missing engine even when the plan claims everything is fine.
        p = _make_pipeline_with_ctx(
            tmp_path, "generic", _valid_runtime_plan(),
        )
        # Intentionally do NOT append host scripts.
        with pytest.raises(RuntimeError) as exc_info:
            p._check_runtime_playability_guard()
        msg = str(exc_info.value)
        assert "SceneRuntime" in msg
        assert "Missing SceneRuntime host scripts" in msg

    def test_partial_host_emit_fails(self, tmp_path):
        # Only SceneRuntime + SceneRuntimePlan present; both
        # entrypoints missing (e.g. autogen generator crashed
        # mid-emit). The guard treats partial as incomplete.
        p = _make_pipeline_with_ctx(
            tmp_path, "generic", _valid_runtime_plan(),
        )
        for s in _host_scripts()[:2]:  # first two only
            p.state.rbx_place.scripts.append(s)
        with pytest.raises(RuntimeError) as exc_info:
            p._check_runtime_playability_guard()
        msg = str(exc_info.value)
        assert "SceneRuntimeClient" in msg
        assert "SceneRuntimeServer" in msg


# ---------------------------------------------------------------------------
# Operator escape: --allow-nonplayable-output
# ---------------------------------------------------------------------------


class TestAllowNonplayableEscape:

    def test_escape_downgrades_invalid_module(self, tmp_path):
        # Same plan as ``test_invalid_domain_fails`` but with the
        # escape set -- the guard logs + writes UNCONVERTED.md, no
        # raise.
        plan = {
            "modules": {
                "guid-bad": {
                    "stem": "Bad",
                    "runtime_bearing": True,
                    "domain": "shared",
                    "module_path": "ReplicatedStorage.Bad",
                },
            },
            "scenes": {}, "prefabs": {}, "domain_overrides": {},
        }
        p = _make_pipeline_with_ctx(
            tmp_path, "generic", plan, allow_nonplayable=True,
        )
        for s in _host_scripts():
            p.state.rbx_place.scripts.append(s)
        # Must not raise.
        p._check_runtime_playability_guard()
        # Warning staged for downstream UNCONVERTED.md write.
        warnings = p.ctx.scene_runtime.get("nonplayable_warnings")
        assert isinstance(warnings, list) and len(warnings) == 1
        w = warnings[0]
        assert w["runtime_bearing_count"] == 1
        assert len(w["invalid_modules"]) == 1
        assert w["invalid_modules"][0]["script_id"] == "guid-bad"
        assert w["missing_host_scripts"] == []
        assert w["scene_runtime_mode"] == "generic"

    def test_escape_downgrades_missing_host(self, tmp_path):
        p = _make_pipeline_with_ctx(
            tmp_path, "generic", _valid_runtime_plan(),
            allow_nonplayable=True,
        )
        # No host scripts appended.
        p._check_runtime_playability_guard()
        warnings = p.ctx.scene_runtime["nonplayable_warnings"]
        assert warnings[0]["missing_host_scripts"] == [
            "SceneRuntime",
            "SceneRuntimePlan",
            "SceneRuntimeClient",
            "SceneRuntimeServer",
        ]

    def test_escape_renders_in_unconverted_md(self, tmp_path):
        # End-to-end: escape staged warning is rendered by the
        # downstream _write_unconverted_md.
        p = _make_pipeline_with_ctx(
            tmp_path, "generic", _valid_runtime_plan(),
            allow_nonplayable=True,
        )
        p._check_runtime_playability_guard()
        p._write_unconverted_md()
        unconverted = tmp_path / "UNCONVERTED.md"
        assert unconverted.exists(), (
            "guard downgrade must surface the warning into UNCONVERTED.md"
        )
        body = unconverted.read_text(encoding="utf-8")
        assert "Non-playable converted place" in body
        assert "--allow-nonplayable-output" in body
        assert "SceneRuntime" in body  # at least one missing host script listed

    def test_escape_without_guard_fire_does_not_write_warning(self, tmp_path):
        # Operator passed the flag but the run was actually playable
        # -- no warning should be staged.
        #
        # Codex R1-P2: the guard resets ``nonplayable_warnings`` to
        # an empty list at entry (so stale warnings from prior runs
        # never re-render). A clean run therefore leaves the list
        # PRESENT but empty -- semantically "the most recent run
        # asserted no playability issues". _write_unconverted_md
        # treats an empty list as no content (no section emitted).
        p = _make_pipeline_with_ctx(
            tmp_path, "generic", _valid_runtime_plan(),
            allow_nonplayable=True,
        )
        for s in _host_scripts():
            p.state.rbx_place.scripts.append(s)
        p._check_runtime_playability_guard()
        assert p.ctx.scene_runtime.get("nonplayable_warnings") == []
        # No UNCONVERTED.md write either -- the empty list must not
        # produce a stale "Non-playable" section.
        p._write_unconverted_md()
        unconverted = tmp_path / "UNCONVERTED.md"
        assert not unconverted.exists() or (
            "Non-playable" not in unconverted.read_text(encoding="utf-8")
        )


# ---------------------------------------------------------------------------
# Resume / rehydrate path (cached plan + cached host scripts)
# ---------------------------------------------------------------------------


class TestResumePath:
    """Rehydrate paths (``u2r publish``, ``convert_interactive upload``)
    reload ctx from disk and re-run write_output. A complete cache from
    a prior clean ``generic`` conversion must NOT trip the guard on
    rerun -- otherwise repeated upload calls would degrade into spurious
    failures."""

    def test_resume_with_complete_cache_passes(self, tmp_path):
        # Round-trip ctx through ConversionContext.save/load to model
        # what the resume path actually does.
        ctx_path = tmp_path / "conversion_context.json"
        ctx = ConversionContext(
            unity_project_path=str(tmp_path / "project"),
        )
        ctx.scene_runtime_mode = "generic"
        ctx.scene_runtime = _valid_runtime_plan()
        ctx.save(ctx_path)

        # Reload (matches u2r.publish / convert_interactive.upload).
        reloaded = ConversionContext.load(ctx_path)
        assert reloaded.scene_runtime_mode == "generic"
        assert reloaded.scene_runtime["modules"]["guid-foo"]["domain"] == "client"

        # Build a pipeline with the reloaded ctx + a fresh host emit
        # (which the rebuild's _subphase_inject_scene_runtime would
        # produce). Guard must accept this state.
        p = Pipeline.__new__(Pipeline)
        p.ctx = reloaded
        p.output_dir = tmp_path
        state = MagicMock()
        state.rbx_place = RbxPlace()
        state.rbx_place.scripts = list(_host_scripts())
        state.rbx_place.unconverted_components = []
        state.animation_result = None
        state.transpilation_result = None
        state.material_mappings = {}
        p.state = state
        # Default allow_nonplayable_output is False; cache is complete;
        # guard passes.
        p._check_runtime_playability_guard()

    def test_resume_persists_allow_flag(self, tmp_path):
        # The escape flag persists through ctx save/load so a subsequent
        # ``assemble`` or ``upload`` rerun without re-passing
        # --allow-nonplayable-output still honors the original opt-in.
        # This matches how scene_runtime_mode threads through resumes.
        ctx_path = tmp_path / "conversion_context.json"
        ctx = ConversionContext(
            unity_project_path=str(tmp_path / "project"),
        )
        ctx.scene_runtime_mode = "generic"
        ctx.allow_nonplayable_output = True
        ctx.scene_runtime = _valid_runtime_plan()
        ctx.save(ctx_path)
        reloaded = ConversionContext.load(ctx_path)
        assert reloaded.allow_nonplayable_output is True


# ---------------------------------------------------------------------------
# Hook ordering: guard runs after host emit, before encoder
# ---------------------------------------------------------------------------


class TestSubphaseOrder:
    """The order of write_output's subphases is load-bearing. Document
    and assert that the guard sits between ``_subphase_inject_scene_runtime``
    and the artifact emit subphases that follow it."""

    def test_subphase_order_places_guard_after_host_emit(self):
        order = Pipeline.SUBPHASE_ORDER
        assert "_subphase_inject_scene_runtime" in order
        assert "_check_runtime_playability_guard" in order
        host_idx = order.index("_subphase_inject_scene_runtime")
        guard_idx = order.index("_check_runtime_playability_guard")
        assert guard_idx == host_idx + 1, (
            "guard must run immediately after the host emit subphase so "
            "a clean generic run has its host scripts staged before the "
            "predicate fires"
        )

    def test_subphase_order_places_guard_before_finalize(self):
        order = Pipeline.SUBPHASE_ORDER
        guard_idx = order.index("_check_runtime_playability_guard")
        # Any subphase that writes the artifact (encode_terrain,
        # finalize_scripts_to_disk) must follow the guard.
        finalize_idx = order.index("_subphase_finalize_scripts_to_disk")
        assert guard_idx < finalize_idx


# ---------------------------------------------------------------------------
# Front-door plumbing (ctx field reachability from each CLI command)
# ---------------------------------------------------------------------------


class TestFrontDoorPlumbing:
    """The brief explicitly lists every front door that gets the flag:
    u2r convert/publish/eval, convert_interactive transpile/assemble/
    upload. Assert each command actually exposes ``--allow-nonplayable-
    output`` so the operator escape is consistent across entry points."""

    def test_u2r_convert_exposes_flag(self):
        from click.testing import CliRunner
        from u2r import main
        runner = CliRunner()
        result = runner.invoke(main, ["convert", "--help"])
        assert result.exit_code == 0
        assert "--allow-nonplayable-output" in result.output

    def test_u2r_publish_exposes_flag(self):
        from click.testing import CliRunner
        from u2r import main
        runner = CliRunner()
        result = runner.invoke(main, ["publish", "--help"])
        assert result.exit_code == 0
        assert "--allow-nonplayable-output" in result.output

    def test_u2r_eval_exposes_flag(self):
        from click.testing import CliRunner
        from u2r import main
        runner = CliRunner()
        result = runner.invoke(main, ["eval", "--help"])
        assert result.exit_code == 0
        assert "--allow-nonplayable-output" in result.output

    def test_convert_interactive_transpile_exposes_flag(self):
        from click.testing import CliRunner
        from convert_interactive import cli
        runner = CliRunner()
        result = runner.invoke(cli, ["transpile", "--help"])
        assert result.exit_code == 0
        assert "--allow-nonplayable-output" in result.output

    def test_convert_interactive_assemble_exposes_flag(self):
        from click.testing import CliRunner
        from convert_interactive import cli
        runner = CliRunner()
        result = runner.invoke(cli, ["assemble", "--help"])
        assert result.exit_code == 0
        assert "--allow-nonplayable-output" in result.output

    def test_convert_interactive_upload_exposes_flag(self):
        from click.testing import CliRunner
        from convert_interactive import cli
        runner = CliRunner()
        result = runner.invoke(cli, ["upload", "--help"])
        assert result.exit_code == 0
        assert "--allow-nonplayable-output" in result.output

    def test_conversion_context_default_is_false(self):
        ctx = ConversionContext()
        assert ctx.allow_nonplayable_output is False, (
            "default must be fail-closed; opt-in via the front-door flag"
        )


# ---------------------------------------------------------------------------
# Codex round 1 absorbed findings
# ---------------------------------------------------------------------------


class TestUserOwnedHostScriptCollision:
    """Codex R1-P1.B: a project that already ships scripts named
    ``SceneRuntime`` / ``SceneRuntimePlan`` / etc. would bypass the
    autogen emit (R3-P2 deliberately preserves user content), and the
    naive presence-by-name check would false-pass even though the
    engine binding logic is missing.

    The guard now narrows the host-script check to "name match AND
    autogen marker present in source", so the false-pass surface is
    closed.
    """

    def test_user_owned_scene_runtime_without_marker_fails(self, tmp_path):
        p = _make_pipeline_with_ctx(
            tmp_path, "generic", _valid_runtime_plan(),
        )
        # Three host scripts carry the marker; SceneRuntime is a
        # name-collision user script that survived the preserve path.
        host = _host_scripts()
        host[0] = RbxScript(
            name="SceneRuntime",
            source="-- user-owned module that happens to be named SceneRuntime",
            script_type="ModuleScript",
            parent_path="ReplicatedStorage",
        )
        for s in host:
            p.state.rbx_place.scripts.append(s)
        with pytest.raises(RuntimeError) as exc_info:
            p._check_runtime_playability_guard()
        msg = str(exc_info.value)
        assert "SceneRuntime" in msg
        assert "Missing SceneRuntime host scripts" in msg

    def test_all_four_marker_match_passes(self, tmp_path):
        # Sanity check that the marker-strict check still accepts a
        # clean autogen emit.
        p = _make_pipeline_with_ctx(
            tmp_path, "generic", _valid_runtime_plan(),
        )
        for s in _host_scripts():
            p.state.rbx_place.scripts.append(s)
        p._check_runtime_playability_guard()


class TestNonplayableWarningResetAcrossReruns:
    """Codex R1-P2: prior guard warnings stick around in
    ``ctx.scene_runtime["nonplayable_warnings"]`` across reruns,
    causing a later clean run to falsely render the stale warning
    into UNCONVERTED.md. The guard now resets the list at entry
    (BEFORE the mode gate, so a later legacy rerun also clears it).
    """

    def test_clean_rerun_clears_stale_warning(self, tmp_path):
        # First run: opt-in to escape, plan is incomplete -- warning
        # gets staged.
        plan_bad = {
            "modules": {
                "guid": {"stem": "X", "runtime_bearing": True,
                         "domain": "shared",  # invalid
                         "module_path": "ReplicatedStorage.X"},
            },
            "scenes": {}, "prefabs": {}, "domain_overrides": {},
        }
        p = _make_pipeline_with_ctx(
            tmp_path, "generic", plan_bad, allow_nonplayable=True,
        )
        for s in _host_scripts():
            p.state.rbx_place.scripts.append(s)
        p._check_runtime_playability_guard()
        assert len(p.ctx.scene_runtime["nonplayable_warnings"]) == 1

        # Second run on the same ctx: plan is now clean. Warning must
        # be cleared so a fresh UNCONVERTED.md doesn't render the
        # stale block.
        p.ctx.scene_runtime = _valid_runtime_plan()
        # _make_pipeline_with_ctx's reset of rbx_place.scripts -- in
        # the real pipeline rebuild this happens via
        # _subphase_emit_scripts_to_disk's wipe; for the unit test we
        # do it directly.
        p.state.rbx_place.scripts = list(_host_scripts())
        # Carry over the prior stale warning to simulate it surviving
        # ctx.save/load between runs.
        p.ctx.scene_runtime["nonplayable_warnings"] = [
            {"runtime_bearing_count": 1, "invalid_modules": [],
             "missing_host_scripts": [], "scene_runtime_mode": "generic"}
        ]
        p._check_runtime_playability_guard()
        # Clean run -> empty list (not absent).
        assert p.ctx.scene_runtime["nonplayable_warnings"] == []

    def test_legacy_rerun_also_clears_stale_warning(self, tmp_path):
        # The reset must run BEFORE the mode gate so an auto->legacy
        # fallback after a downgraded run also wipes the stale
        # warning (the fallback's UNCONVERTED.md must not falsely
        # carry the prior generic run's playability complaint).
        p = _make_pipeline_with_ctx(
            tmp_path, "legacy", _valid_runtime_plan(),
        )
        # Simulate a prior generic run's persisted warning.
        p.ctx.scene_runtime["nonplayable_warnings"] = [
            {"runtime_bearing_count": 1, "invalid_modules": [],
             "missing_host_scripts": ["SceneRuntime"],
             "scene_runtime_mode": "generic"}
        ]
        p._check_runtime_playability_guard()
        # Legacy short-circuit still must have cleared the list.
        assert p.ctx.scene_runtime["nonplayable_warnings"] == []


class TestStickyOptInPersistsThroughResume:
    """Codex R1-P1.A: ``--allow-nonplayable-output`` must survive a
    resume rebuild even when the operator doesn't re-pass the flag.
    The front-door commands implement this as "sticky opt-in":
    explicit True overrides persisted; False (Click default) leaves
    the persisted value alone.

    These tests cover the ctx-level invariant; the front-door command
    behavior is validated by the integration tests in this file's
    plumbing class above.
    """

    def test_persisted_true_survives_unset_cli_flag(self):
        # Simulate the resume flow: ctx loaded from disk carries the
        # opt-in; CLI flag default is False; sticky logic must NOT
        # overwrite the persisted value.
        ctx = ConversionContext()
        ctx.allow_nonplayable_output = True

        # Sticky-opt-in mirror of the front-door code: only assign
        # when the CLI explicitly opted in.
        cli_flag = False  # operator didn't re-pass --allow-nonplayable-output
        if cli_flag:
            ctx.allow_nonplayable_output = True

        assert ctx.allow_nonplayable_output is True, (
            "persisted opt-in must survive a resume without the flag"
        )

    def test_explicit_true_overrides_persisted_false(self):
        ctx = ConversionContext()
        ctx.allow_nonplayable_output = False
        cli_flag = True
        if cli_flag:
            ctx.allow_nonplayable_output = True
        assert ctx.allow_nonplayable_output is True


# ---------------------------------------------------------------------------
# PR7 cross-reference: would PR7's auto-default e2e fail without PR6?
# ---------------------------------------------------------------------------


class TestPR7CrossReference:
    """The PR6 brief asserts: "Verified to land before PR7 by running
    PR7's test pre-PR6 and asserting it would fail." PR7 will flip
    the default mode to ``auto`` so a no-flag conversion routes
    through generic (or falls back to legacy on signal). The
    operator-safety contract is: "if a project would have produced a
    non-playable place under the new default, the guard MUST raise
    rather than silently writing a broken artifact."

    Pre-PR6, that contract had no enforcement -- write_output would
    happily emit the artifact. PR6 lands the enforcement; PR7 then
    safely flips the default.

    These tests assert the post-PR6 enforcement directly (we don't
    yet have PR7's e2e fixture; instead we exercise the auto path
    end-to-end against an incomplete plan and confirm the guard
    fires after the auto->generic routing).
    """

    def test_auto_clean_to_generic_then_guard_fires_on_incomplete_plan(
        self, tmp_path,
    ):
        # Mimic what PR7's e2e default conversion will exercise: the
        # user passes nothing, mode resolves to ``auto`` (PR7
        # default), then ``_check_auto_fail_closed`` routes to
        # ``generic`` because the plan is consistent enough to
        # transpile (no fail-closed signals were raised). But the
        # plan is incomplete -- the PR3b classifier never ran on this
        # synthetic fixture, so ``module_path`` is empty.
        plan = {
            "modules": {
                "guid": {"stem": "PartialPlan", "runtime_bearing": True,
                         "domain": "client",
                         # module_path empty -- PR6 catches this
                         "module_path": ""},
            },
            "scenes": {}, "prefabs": {}, "domain_overrides": {},
            # Empty auto_fail_closed list -- the auto router routes
            # to generic since no signals were detected.
            "auto_fail_closed": [],
        }
        p = _make_pipeline_with_ctx(tmp_path, "generic", plan)
        for s in _host_scripts():
            p.state.rbx_place.scripts.append(s)
        with pytest.raises(RuntimeError) as exc_info:
            p._check_runtime_playability_guard()
        msg = str(exc_info.value)
        # PR6 backstops PR7's default flip: even a "successful"
        # generic routing under auto cannot ship a broken place.
        assert "PR6 playability guard" in msg
        assert "module_path" in msg
