"""S3 (1.4) — NET / E2E witness for the rifle rig-retarget (Path A).

This slice is the END-TO-END witness over the whole Path A chain (resolver ->
read-reroute lowering -> binding-present verifier -> fixture), proving on the
REAL pipeline shape — not synthetic stubs — that the rifle binding is rerouted
through the per-instance rig resolver and seats under the ``_MainCameraRig``'s
``WeaponSlot``.

Three acceptance pillars (design-phase1 §5 S3 / §4 (d), (e), (g)):

1. **Deterministic RACE test (acceptance d)** — the crux the back-fill design
   LOST: Awake runs with the rig ABSENT -> the rig Model streams in LATE ->
   equip (``GetRifle``) fires -> the rifle ends up parented under the rig's
   ``WeaponSlot``. We extract BOTH the REAL emitted ``Player:_resolveWeaponSlot()``
   AND the REAL REWRITTEN ``Player:GetRifle()`` consumer (the exact Luau the
   lowering produces, where every ``self.<field>`` read became a
   ``self:_resolveWeaponSlot()`` call — NOT a re-typed copy) and drive the
   CONSUMER under an executable ``luau`` harness with a deterministic Roblox-API
   stub. ``task.wait`` is the deterministic clock: the rig is inserted on a chosen
   tick INSIDE the bounded retry, so the first sweep misses and the retry catches
   it — forced, no flake. Because we run the REWRITTEN consumer (not the resolver
   in isolation), a regression that fails to reroute the consumer's reads would
   leave a raw ``self.<field>`` read returning nil -> the rifle never seats -> the
   harness FAILS. Proves the LOAD-BEARING read-reroute discharge end-to-end.

2. **Deterministic BOUNDARY-FAILS-LOUD test (acceptance e / e-boundary)** — a
   conversion-shaped source where the AI factors the field OUT of the read path
   (or emits an unsupported boundary form) drives the WHOLE pipeline gate (the
   real ``Pipeline._run_contract_verifier`` hook, same hook the corpus gate
   uses) and asserts the project FAIL-CLOSES LOUD on the REAL pipeline surface:
   the promoted ``rig_binding_present`` error lands in ``pipeline.ctx.errors`` and
   flips ``conversion success`` (``len(ctx.errors) == 0``) to False. This is the
   fail-closed boundary firing END-TO-END (pipeline level), read off the SAME
   ``ctx.errors`` the hook populates — not a parallel re-computation — so a hook
   that stopped promoting rows would FAIL these tests.

3. **Fresh-conversion E2E (acceptance g — conversion half)** — asserts on the
   REAL captured pipeline OUTPUT (the corpus fixture regenerated by S2 from a
   real pipeline run, the conversion-output source of truth) that on the LIVE AI
   shape the Player ``rig_binding`` is ``present=True``, the consumer reads are
   rerouted to ``self:_resolveWeaponSlot()``, and the resolver targets the
   ``_MainCameraRig``'s ``WeaponSlot``. A ``@pytest.mark.slow`` test does the
   genuinely-fresh full conversion when the test-projects root is configured.
   *Design intent (load-bearing):* this asserts the read-reroute fires on the
   REAL live AI-output shape, the exact case the old write-anchored lowering
   abstained on (D-S2-REDESIGN).

GENERIC: every load-bearing assertion keys on the carrier's parameterized
``field``/``child`` (read from the fixture / fact), NOT on ``rifle``/
``weaponSlot``/``WeaponSlot``/``Camera`` string literals — where a SimpleFPS name
appears it is the fixture's DATA, not a hardcoded mechanism. A generic
field/child pair (``gunSlot``/``GunMount``) distinct from the SimpleFPS names is
exercised through the SAME producer -> lowering -> verifier chain so a
field-name-hardcoding regression in any stage FAILS.

The LIVE Roblox Studio gameplay witness (PlaceTo / playtest) is run SEPARATELY
from the main session — Roblox MCP tools are not available in this subagent
context (e2e-studio-half-needs-main-session) — so this file asserts on the
converted OUTPUT artifacts, never on a live Studio session.
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import TypedDict

import pytest

sys.path.insert(0, str(Path(__file__).parent.parent))

from converter.child_ref_resolver import (  # noqa: E402
    ChildRefScript,
    RigRootedRetargetFact,
    build_child_ref_map,
)
from converter.contract_verifier import (  # noqa: E402
    CONTRACT_ERROR_PREFIX,
    fail_closed_errors,
    verify_contract,
)
from converter.pipeline import Pipeline  # noqa: E402
from converter.rifle_rig_retarget_lowering import lower_rifle_rig_retarget  # noqa: E402
from core.roblox_types import RbxPlace, RbxScript  # noqa: E402
from core.unity_types import (  # noqa: E402
    GuidEntry,
    GuidIndex,
    PrefabComponent,
    PrefabLibrary,
    PrefabNode,
    PrefabTemplate,
)
from unity.script_analyzer import ScriptInfo  # noqa: E402
from utils.luau_analyze import luau_analyze_path  # noqa: E402

_FIXTURE_ROOT = Path(__file__).parent / "fixtures" / "contract_corpus"
_SIMPLEFPS_FIXTURE = _FIXTURE_ROOT / "SimpleFPS" / "fixture.json"
_TOPOLOGY = {"modules": {"Player": {"stem": "Player"}}}
_GUID = "44444444444444444444444444444444"


class _PlayerFixture(TypedDict):
    """The shape this test reads off a captured corpus ``scripts[]`` entry."""

    name: str
    source: str
    rig_binding: dict[str, object]


# ---------------------------------------------------------------------------
# Shared drivers (real lowering + real producer chain + real pipeline gate).
# ---------------------------------------------------------------------------
class _Script:
    """Minimal ``_HasLuauSourceAndPath`` for driving the REAL lowering."""

    def __init__(self, source: str, source_path: str = "/proj/Player.cs") -> None:
        self.luau_source = source
        self.source_path = source_path
        self.rig_binding: dict[str, object] | None = None


def _lower(
    source: str,
    *,
    field: str = "weaponSlot",
    child: str = "WeaponSlot",
    cam_receiver: str = "cam",
    source_path: str = "/proj/Player.cs",
) -> _Script:
    """Run S1's REAL lowering over ``source`` with a HAND-BUILT fact; return the
    edited script object. (The hand-built fact is acceptable in the race/boundary
    harnesses; the producer chain is exercised by ``_lower_via_real_producer``.)"""
    s = _Script(source, source_path)
    fact = RigRootedRetargetFact(
        field_name=field, child_name=child, cam_receiver=cam_receiver
    )
    crs = ChildRefScript(
        facts=(), getchild_total=1, resolved_total=1, rig_facts=(fact,)
    )
    lower_rifle_rig_retarget([s], {source_path: crs})
    return s


# --- the REAL producer chain (build_child_ref_map -> _resolve_rig_facts) ----
def _mono(guid: str) -> PrefabComponent:
    return PrefabComponent(
        component_type="MonoBehaviour",
        file_id="100",
        properties={"m_Script": {"fileID": 11500000, "guid": guid, "type": 3}},
    )


def _pnode(
    name: str,
    *,
    tag: str = "Untagged",
    children: list[PrefabNode] | None = None,
    comp_guid: str | None = None,
) -> PrefabNode:
    return PrefabNode(
        name=name,
        file_id=name,
        active=True,
        tag=tag,
        children=children or [],
        components=[_mono(comp_guid)] if comp_guid else [],
    )


def _fps_library(*, child: str, class_name: str) -> PrefabLibrary:
    """``<class_name>``(host) + a MainCamera-tagged node whose child[0] is uniquely
    ``child``. Generic over the child name + host class — no hardcode."""
    cam = _pnode("MainCamera", tag="MainCamera", children=[_pnode(child)])
    host = _pnode(class_name, children=[cam], comp_guid=_GUID)
    template = PrefabTemplate(
        prefab_path=Path(f"/p/{class_name}.prefab"), name=class_name, root=host
    )
    return PrefabLibrary(prefabs=[template])


def _guid_index(cs_path: Path) -> GuidIndex:
    idx = GuidIndex(project_root=cs_path.parent)
    idx.guid_to_entry[_GUID] = GuidEntry(
        guid=_GUID,
        asset_path=cs_path,
        relative_path=Path(cs_path.name),
        kind="script",
    )
    return idx


def _resolve_real_rig_fact(
    tmp_path: Path, *, field: str, child: str, class_name: str
) -> tuple[ChildRefScript, str]:
    """Drive the REAL producer chain (``build_child_ref_map`` ->
    ``_resolve_script`` -> ``_resolve_rig_facts``) over a real ``.cs`` file + a
    parsed hierarchy, returning the resolver-produced ``ChildRefScript`` (whose
    ``rig_facts`` was computed by the resolver, NOT hand-fabricated) and the
    canonical path key. Exercises the producer END for the producer->consumer
    ->verifier chain."""
    cs = (
        "using UnityEngine;\n"
        f"public class {class_name} : MonoBehaviour {{\n"
        f"  Transform cam; public Transform {field};\n"
        "  void Awake() {\n"
        "    cam = Camera.main.transform;\n"
        f"    {field} = cam.GetChild(0);\n"
        "  }\n"
        "}\n"
    )
    cs_path = tmp_path / f"{class_name}.cs"
    cs_path.write_text(cs, encoding="utf-8")
    info = ScriptInfo(
        path=cs_path, class_name=class_name, base_class="MonoBehaviour"
    )
    crm = build_child_ref_map(
        script_infos=[info],
        parsed_scenes=None,
        prefab_library=_fps_library(child=child, class_name=class_name),
        guid_index=_guid_index(cs_path),
    )
    key = str(cs_path.resolve())
    entry = crm.get(key)
    assert entry is not None, "the real producer must map the host script"
    return entry, key


class PipelineGate(TypedDict):
    """The REAL pipeline-gate outcome surface a contract breach produces."""

    errors: list[str]  # the contract-prefixed errors promoted onto ``ctx.errors``
    success: bool  # the real ``len(ctx.errors) == 0`` conversion-success flag
    rows: list[dict[str, object]]  # the recorded shadow-metric violation rows


def _run_pipeline_gate(scripts: list[RbxScript], tmp_path: Path) -> PipelineGate:
    """Drive the REAL ``Pipeline._run_contract_verifier`` hook (the same gate the
    corpus uses) and report the LOUD end-to-end failure surface read OFF THE REAL
    PIPELINE STATE — ``pipeline.ctx.errors`` (the promotion the hook performs) and
    the ``success`` flag (``len(ctx.errors) == 0``, pipeline.py:4340) — NOT a
    parallel re-computation. A hook that stopped promoting rows to ``ctx.errors``
    would flip ``success`` and DROP the contract errors, failing the boundary
    tests."""
    unity_project = tmp_path / "unity"
    (unity_project / "Assets").mkdir(parents=True)
    output = tmp_path / "out"
    output.mkdir()
    pipeline = Pipeline(str(unity_project), str(output))
    pipeline.state.rbx_place = RbxPlace()
    pipeline.state.rbx_place.scripts = scripts
    pipeline.ctx.scene_runtime = {}
    pipeline._run_contract_verifier({"topology": _TOPOLOGY})
    rows = pipeline.ctx.scene_runtime.get("contract_check_violations", [])
    # Read the REAL promotion off ``ctx.errors`` (what flips success), filtered to
    # this verifier's owned prefix; ``success`` is the pipeline's own predicate.
    contract_errs = [
        e for e in pipeline.ctx.errors if e.startswith(CONTRACT_ERROR_PREFIX)
    ]
    success = len(pipeline.ctx.errors) == 0
    return PipelineGate(errors=contract_errs, success=success, rows=rows)


# The on-corpus AI-output shape (mirrors the captured live Player): the Awake
# camera-child write + the GetRifle consumer reads + the ``return Player``
# epilogue. ``cam`` is the bare symbol seeded from ``Camera.main.transform``.
# Parameterized over class/field so a generic (non-SimpleFPS) variant runs the
# identical chain.
def _ai_output_shape(*, class_name: str = "Player", field: str = "weaponSlot") -> str:
    return f"""local {class_name} = {{}}
{class_name}.__index = {class_name}

function {class_name}.new()
    local self = setmetatable({{}}, {class_name})
    return self
end

function {class_name}:Awake()
    self.cam = workspace.CurrentCamera
    self.{field} = self.cam and self.cam:GetChildren()[1]
end

function {class_name}:GetRifle()
    local rifle = self.host.instantiatePrefab(self.riflePrefab, self.{field}, pivotOf(self.{field}))
    if self.{field} then rifle:PivotTo(pivotOf(self.{field})) end
    return rifle
end

return {class_name}
"""


_AI_OUTPUT_SHAPE = _ai_output_shape()


# ===========================================================================
# 1. DETERMINISTIC RACE TEST (acceptance d) — the crux.
# Awake-miss -> rig streams in LATE -> equip -> rifle on the rig's WeaponSlot.
# Runs the REAL emitted resolver AND the REAL REWRITTEN CONSUMER under an
# executable ``luau`` harness, so a read-reroute regression FAILS the harness.
# ===========================================================================
def _extract_method(
    luau_source: str, class_name: str, method: str, *, terminator: str
) -> str:
    """Extract the EXACT ``function <Class>:<method>() ... <terminator> ... end``
    block the REAL lowering emitted (not a re-typed copy), so the harness exercises
    shipped Luau. ``terminator`` is the literal final STATEMENT line of the method
    body (e.g. ``    return slot``); the method's closing ``end`` (the first ``end``
    at the start of a line AFTER the terminator) is included so the block is a
    complete, loadable function."""
    m = re.search(
        rf"function {re.escape(class_name)}:{re.escape(method)}\(\)"
        rf".*?\n{re.escape(terminator)}[^\n]*\nend",
        luau_source,
        re.S,
    )
    assert m is not None, f"could not extract {class_name}:{method} from the lowering"
    return m.group(0)


def _lowered_resolver_and_consumer(
    *, field: str = "weaponSlot", child: str = "WeaponSlot", class_name: str = "Player"
) -> tuple[str, str]:
    """Run the REAL lowering and extract BOTH the emitted resolver method AND the
    REWRITTEN consumer ``GetRifle`` (where ``self.<field>`` reads became
    ``self:_resolve<Child>()`` calls). Returns ``(resolver_method, consumer_method)``
    — both verbatim from the live lowering output."""
    lowered = _lower(
        _ai_output_shape(class_name=class_name, field=field),
        field=field,
        child=child,
    )
    resolver = _extract_method(
        lowered.luau_source, class_name, f"_resolve{child}", terminator="    return slot"
    )
    consumer = _extract_method(
        lowered.luau_source, class_name, "GetRifle", terminator="    return rifle"
    )
    # Sanity: the lowering MUST have rerouted the consumer's reads (the load-bearing
    # discharge). If a regression left a raw ``self.<field>`` read, the harness
    # below would resolve nil and FAIL — but assert it here too for a clear message.
    assert f"self:_resolve{child}()" in consumer, (
        "the lowered consumer must reroute its reads through the resolver"
    )
    assert f"self.{field}" not in consumer, (
        "no raw self.<field> read may survive in the rerouted consumer"
    )
    return resolver, consumer


# A deterministic Roblox-API stub: ``task.wait`` is the clock. The rig Model is
# inserted into ``workspace`` ON a chosen tick INSIDE the bounded retry, so the
# first ``findSlot()`` sweep MISSES (Awake-with-rig-absent) and the retry catches
# the late-streaming rig. The whole schedule is forced — no real time, no flake.
# The harness drives the REWRITTEN CONSUMER (GetRifle), so the rifle seats via the
# consumer's own ``self:_resolve<Child>()``-rerouted reads — the load-bearing path.
def _race_harness(
    resolver_method: str,
    consumer_method: str,
    *,
    rig_appears_on_tick: int,
    child: str = "WeaponSlot",
    class_name: str = "Player",
) -> str:
    return f"""
-- ===== Deterministic Roblox-API stub (task.wait is the clock) =====
local WORKSPACE_CHILDREN = {{}}
local TICK = 0
local RIG_APPEARS_ON_TICK = {rig_appears_on_tick}

local function makeInstance(className, attrs)
    local inst
    inst = {{
        _class = className,
        _attrs = attrs or {{}},
        _children = {{}},
        Parent = nil,
        IsA = function(self, c) return self._class == c end,
        GetAttribute = function(self, k) return self._attrs[k] end,
        GetChildren = function(self) return self._children end,
        GetPivot = function(self) return self end,
        PivotTo = function(self, _cf) end,
        FindFirstChild = function(self, name, _recursive)
            local function walk(node)
                for _, ch in node._children do
                    if ch._name == name then return ch end
                    local found = walk(ch)
                    if found then return found end
                end
                return nil
            end
            return walk(self)
        end,
    }}
    return inst
end

-- The rig Model + its slot child (the late-streaming target).
local weaponSlot = makeInstance("BasePart", {{}})
weaponSlot._name = "{child}"
local rig = makeInstance("Model", {{ _MainCameraRig = true }})
rig._name = "_MainCameraRig"
weaponSlot.Parent = rig
rig._children = {{ weaponSlot }}

-- workspace:GetDescendants() flattens whatever has streamed in so far.
local workspace = {{
    CurrentCamera = makeInstance("Camera", {{}}),
    GetDescendants = function(self)
        local out = {{}}
        local function collect(node)
            for _, ch in node._children do
                table.insert(out, ch)
                collect(ch)
            end
        end
        for _, top in WORKSPACE_CHILDREN do
            table.insert(out, top)
            collect(top)
        end
        return out
    end,
}}

-- task.wait is the deterministic clock: it advances TICK and, on the chosen
-- tick, STREAMS THE RIG IN (the late-arrival the bounded retry exists for).
local task = {{
    wait = function(_dt)
        TICK = TICK + 1
        if TICK == RIG_APPEARS_ON_TICK then
            table.insert(WORKSPACE_CHILDREN, rig)
        end
        return _dt
    end,
}}

-- ``pivotOf`` is nil-safe and expects a real Instance (the on-corpus :13 helper).
local function pivotOf(obj)
    if not obj then return "ORIGIN" end
    if obj.GetPivot then return obj:GetPivot() end
    return "ORIGIN"
end

-- ``self.host.instantiatePrefab`` seats the rifle under the resolved slot (the
-- runtime host: ``clone.Parent = parent or workspace``, scene_runtime.luau:2025).
local function makeHost()
    return {{
        instantiatePrefab = function(_prefab, parent, _pivot)
            local clone = makeInstance("Model", {{}})
            clone.Parent = parent  -- a real slot Instance, or nil -> workspace
            return clone
        end,
    }}
end

-- ===== The REAL emitted resolver + REWRITTEN consumer, verbatim =====
local {class_name} = {{}}
{class_name}.__index = {class_name}
{resolver_method}
{consumer_method}

-- ===== Drive the failing schedule THROUGH the consumer =====
local self = setmetatable({{}}, {class_name})
self.host = makeHost()
self.riflePrefab = makeInstance("Model", {{}})

-- (1) Awake runs with the rig ABSENT (no _MainCameraRig in workspace yet).
assert(#workspace:GetDescendants() == 0, "rig must be absent at Awake")

-- (2) equip fires: the REWRITTEN GetRifle calls self:_resolve{child}(); the first
--     sweep MISSES, the bounded retry runs, the rig streams in on the chosen tick,
--     and the consumer parents the rifle under the resolved slot.
local rifle = self:GetRifle()

-- (3) assert the rifle ends up parented under the rig's slot (NOT nil, NOT
--     workspace-origin) — the read reroute seated the binding under the race.
assert(rifle ~= nil, "FAIL: GetRifle returned nil")
assert(rifle.Parent ~= nil, "FAIL: rifle did not seat under any slot (read not rerouted?)")
assert(rifle.Parent._name == "{child}", "FAIL: rifle seated under the wrong child")
assert(rifle.Parent.Parent == rig, "FAIL: the slot is not under the _MainCameraRig")
assert(rifle.Parent.Parent:GetAttribute("_MainCameraRig") == true,
    "FAIL: parent is not the rig")

-- (4) memoization: a SECOND GetRifle on the SAME instance reuses the cached slot,
--     and a FRESH instance resolves its OWN slot (per-instance, no shared state).
local rifle2 = self:GetRifle()
assert(rifle2.Parent == rifle.Parent, "FAIL: resolver is not memoized per-instance")
local other = setmetatable({{}}, {class_name})
other.host = makeHost()
other.riflePrefab = makeInstance("Model", {{}})
local other_rifle = other:GetRifle()
assert(other_rifle.Parent == weaponSlot, "FAIL: second instance did not resolve the slot")

print("RACE_OK")
"""


def _run_luau(source: str, timeout: float = 20.0) -> "subprocess.CompletedProcess[str]":
    f = tempfile.NamedTemporaryFile(
        mode="w", suffix=".luau", delete=False, encoding="utf-8"
    )
    path = f.name
    try:
        f.write(source)
        f.close()
        return subprocess.run(
            ["luau", path], capture_output=True, text=True, timeout=timeout
        )
    finally:
        Path(path).unlink(missing_ok=True)


def _luau_available() -> bool:
    from shutil import which

    return which("luau") is not None


@pytest.mark.skipif(not _luau_available(), reason="luau interpreter not installed")
def test_race_awake_miss_then_late_rig_seats_under_weaponslot() -> None:
    """ACCEPTANCE (d) — THE CRUX. The rig is absent at Awake and streams in on a
    LATE tick (tick 5, well inside the 30-tick budget); the REWRITTEN consumer's
    first ``self:_resolveWeaponSlot()`` sweep misses, the bounded retry catches the
    late rig, and the rifle seats under the ``_MainCameraRig``'s slot. Forced
    schedule, no flake. The back-fill design FAILED this; the consumer-side lazy
    resolve passes by construction — AND because the harness drives the REWRITTEN
    consumer, a read-reroute regression (raw ``self.<field>`` left in GetRifle)
    fails it too."""
    resolver, consumer = _lowered_resolver_and_consumer()
    harness = _race_harness(resolver, consumer, rig_appears_on_tick=5)
    proc = _run_luau(harness)
    assert proc.returncode == 0, (
        f"race harness FAILED:\nstdout={proc.stdout}\nstderr={proc.stderr}"
    )
    assert "RACE_OK" in proc.stdout, proc.stdout


@pytest.mark.skipif(not _luau_available(), reason="luau interpreter not installed")
def test_race_rig_present_before_first_sweep_resolves_synchronously() -> None:
    """ACCEPTANCE (d) variant — the rig is present BEFORE the first sweep (tick 1,
    the resolver's very first ``task.wait`` streams it in). The bounded retry's
    first tick catches it: a deterministic forced schedule, the other end of the
    interleaving (no flake either way)."""
    resolver, consumer = _lowered_resolver_and_consumer()
    harness = _race_harness(resolver, consumer, rig_appears_on_tick=1)
    proc = _run_luau(harness)
    assert proc.returncode == 0, (
        f"early-rig harness FAILED:\nstdout={proc.stdout}\nstderr={proc.stderr}"
    )
    assert "RACE_OK" in proc.stdout, proc.stdout


@pytest.mark.skipif(not _luau_available(), reason="luau interpreter not installed")
def test_race_non_rerouted_consumer_fails_the_harness() -> None:
    """NON-TAUTOLOGY GUARD — a consumer whose reads were NOT rerouted (a raw
    ``self.<field>`` read, the regression the reroute exists to prevent) reads nil
    and the rifle never seats -> the harness FAILS. Proves the race test witnesses
    the read-reroute, not merely the resolver in isolation."""
    resolver, _ = _lowered_resolver_and_consumer()
    # A hand-built NON-rerouted consumer (raw self.weaponSlot reads survive).
    raw_consumer = (
        "function Player:GetRifle()\n"
        "    local rifle = self.host.instantiatePrefab(self.riflePrefab, "
        "self.weaponSlot, pivotOf(self.weaponSlot))\n"
        "    if self.weaponSlot then rifle:PivotTo(pivotOf(self.weaponSlot)) end\n"
        "    return rifle\n"
        "end"
    )
    harness = _race_harness(resolver, raw_consumer, rig_appears_on_tick=5)
    proc = _run_luau(harness)
    assert proc.returncode != 0, (
        "a NON-rerouted consumer must FAIL the race harness (the rifle would never "
        f"seat under the rig slot):\nstdout={proc.stdout}\nstderr={proc.stderr}"
    )


@pytest.mark.skipif(not _luau_available(), reason="luau interpreter not installed")
def test_race_generic_different_field_and_child_no_hardcode() -> None:
    """GENERIC — the SAME race passes for a DIFFERENT field AND child name
    (``gunSlot`` / ``GunMount``), proving the harness + the lowered reroute key on
    the carrier's ``field``/``child`` projections, not hardcoded ``weaponSlot`` /
    ``WeaponSlot`` mechanisms. The emitted resolver, the rewritten consumer reads,
    and the rig lookup are all parameterized by the fact."""
    resolver, consumer = _lowered_resolver_and_consumer(
        field="gunSlot", child="GunMount"
    )
    harness = _race_harness(
        resolver, consumer, rig_appears_on_tick=3, child="GunMount"
    )
    proc = _run_luau(harness)
    assert proc.returncode == 0, (
        f"generic race harness FAILED:\nstdout={proc.stdout}\nstderr={proc.stderr}"
    )
    assert "RACE_OK" in proc.stdout, proc.stdout


# ===========================================================================
# 2. DETERMINISTIC BOUNDARY-FAILS-LOUD (acceptance e / e-boundary) — END-TO-END.
# A conversion-shaped source the lowering CANNOT discharge drives the REAL
# pipeline gate; the project FAIL-CLOSES LOUD (success -> False) on the REAL
# ``ctx.errors`` surface, never silently ships a wrong rifle.
# ===========================================================================
def test_boundary_field_factored_out_of_reads_fails_closed_end_to_end(
    tmp_path: Path,
) -> None:
    """ACCEPTANCE (e.ii) END-TO-END — the AI factors the field OUT of the read
    path (the write+return survive, but NO ``self.<field>`` consumer read remains
    to reroute). The lowering abstains (``present=False``); driven through the
    REAL ``_run_contract_verifier`` pipeline hook, the ``rig_binding_present``
    warning PROMOTES to a fail-closed error in ``pipeline.ctx.errors`` -> the
    project fail-closes LOUD (``success=False``)."""
    # Run the REAL lowering on the shape — it abstains, stamping present=False.
    factored = (
        "function Player:Awake()\n"
        "    self.cam = workspace.CurrentCamera\n"
        "    self.weaponSlot = self.cam and self.cam:GetChildren()[1]\n"
        "end\n\n"
        "return Player\n"  # no consumer read of self.weaponSlot anywhere
    )
    lowered = _lower(factored)
    # REDESIGN r3 — the carrier is the 5-key shape: field/child/present PLUS the
    # deterministic anchor cam_receiver (the C# camera symbol, "cam") + cam_ordinal
    # (the 0-based GetChild ordinal). present=False: the field was factored out of
    # every read so the read-reroute discharge could not fire (fail-closed).
    assert lowered.rig_binding == {
        "field": "weaponSlot", "child": "WeaponSlot", "present": False,
        "cam_receiver": "cam", "cam_ordinal": 0,
    }
    script = RbxScript(
        name="Player", source=lowered.luau_source, rig_binding=lowered.rig_binding
    )
    gate = _run_pipeline_gate([script], tmp_path)
    # The boundary fired LOUD end-to-end on the REAL pipeline surface: the promoted
    # rig_binding_present error landed in ctx.errors AND flipped success -> False.
    assert gate["success"] is False, (
        "an un-discharged binding must flip conversion success to False"
    )
    assert any("rig_binding_present" in e for e in gate["errors"]), (
        f"expected a promoted rig_binding_present error in ctx.errors, got "
        f"{gate['errors']}"
    )
    assert any("Player" in e for e in gate["errors"])
    assert any(
        r["check"] == "rig_binding_present" and r["severity"] == "warning"
        for r in gate["rows"]
    )


def test_boundary_nonself_receiver_fails_closed_end_to_end(tmp_path: Path) -> None:
    """ACCEPTANCE (e-boundary.i) END-TO-END — an unsupported BOUNDARY form (a
    non-``self`` receiver read ``owner.weaponSlot`` surviving alongside the
    rerouted reads) is NOT silently passed. Driven through the real pipeline gate,
    the verifier's independent scan returns discharged=False -> a promoted
    ``rig_binding_present`` error in ``ctx.errors`` -> fail-closed LOUD
    (``success=False``). A bare 'no self.<field> survives' check would FALSE-PASS
    this (the codex fail-open hole)."""
    green = _lower(_AI_OUTPUT_SHAPE)
    # Splice a surviving non-self boundary read into the yielding GetRifle.
    boundary_source = green.luau_source.replace(
        "    return rifle\nend",
        "    local x = owner.weaponSlot\n    return rifle\nend",
        1,
    )
    # The carrier still claims present=True (the lowering rerouted the dot reads),
    # but the INDEPENDENT scan must catch the surviving non-self read.
    script = RbxScript(
        name="Player",
        source=boundary_source,
        rig_binding={"field": "weaponSlot", "child": "WeaponSlot", "present": True},
    )
    gate = _run_pipeline_gate([script], tmp_path)
    assert gate["success"] is False, (
        "a surviving non-self boundary read must flip success to False"
    )
    assert any("rig_binding_present" in e for e in gate["errors"]), (
        f"boundary form must fail closed end-to-end on ctx.errors, got "
        f"{gate['errors']}"
    )


def test_boundary_discharged_binding_does_not_fail_closed(tmp_path: Path) -> None:
    """REGRESSION GUARD — a correctly discharged binding (the real lowered shape,
    present=True, reads rerouted, no surviving raw read) does NOT trip the gate:
    the fail-closed boundary is precise, not a blanket reject. ``ctx.errors`` stays
    clean and ``success`` stays True."""
    green = _lower(_AI_OUTPUT_SHAPE)
    script = RbxScript(
        name="Player", source=green.luau_source, rig_binding=green.rig_binding
    )
    gate = _run_pipeline_gate([script], tmp_path)
    assert gate["success"] is True, (
        f"a discharged binding must NOT fail closed, got errors {gate['errors']}"
    )
    assert not any("rig_binding_present" in e for e in gate["errors"]), (
        f"a discharged binding must NOT fail closed, got {gate['errors']}"
    )


def test_boundary_generic_field_factored_out_fails_closed_end_to_end(
    tmp_path: Path,
) -> None:
    """GENERIC + END-TO-END (acceptance e.ii / g-generic) — a DIFFERENT field/child
    (``gunSlot`` / ``GunMount``) factored out of the read path drives the SAME real
    producer -> lowering -> verifier chain and fail-closes LOUD on ``ctx.errors``.
    The rig fact is produced by the REAL resolver (``build_child_ref_map`` ->
    ``_resolve_rig_facts``), NOT hand-fabricated, AND every load-bearing assertion
    keys on the carrier's ``field``/``child`` — a field-name-hardcoding regression
    in the producer, lowering, or verifier would let this FALSE-PASS."""
    field, child, class_name = "gunSlot", "GunMount", "Soldier"
    # REAL producer chain: the resolver computes the rig fact from the C# + parsed
    # hierarchy (not a hand-built RigRootedRetargetFact).
    entry, key = _resolve_real_rig_fact(
        tmp_path, field=field, child=child, class_name=class_name
    )
    assert entry.rig_facts and entry.rig_facts[0].field_name == field
    assert entry.rig_facts[0].child_name == child
    # REDESIGN r3 — the resolver fact carries the deterministic anchor (the C#
    # camera receiver text + the credited GetChild ordinal). Read it OFF THE FACT
    # so the carrier assertion below stays generic (no hardcoded "cam"/0 logic).
    fact = entry.rig_facts[0]
    cam_receiver, cam_ordinal = fact.cam_receiver, fact.ordinal
    assert cam_receiver, "an admitted fact must carry a non-empty cam_receiver"

    # An AI output that factored the field out of every read (no self.<field> read).
    factored = (
        f"function {class_name}:Awake()\n"
        "    self.cam = workspace.CurrentCamera\n"
        f"    self.{field} = self.cam and self.cam:GetChildren()[1]\n"
        "end\n\n"
        f"return {class_name}\n"
    )
    s = _Script(factored, source_path=key)
    # Drive the REAL lowering using the REAL producer's ChildRefScript.
    lower_rifle_rig_retarget([s], {key: entry})
    # 5-key r3 carrier: present=False (read factored out), and the deterministic
    # cam_receiver/cam_ordinal anchor threaded from the fact regardless of discharge.
    assert s.rig_binding == {
        "field": field, "child": child, "present": False,
        "cam_receiver": cam_receiver, "cam_ordinal": cam_ordinal,
    }

    script = RbxScript(
        name=class_name, source=s.luau_source, rig_binding=s.rig_binding
    )
    # Topology must carry the generic module name so the verifier joins it.
    topology = {"modules": {class_name: {"stem": class_name}}}
    unity_project = tmp_path / "unity"
    (unity_project / "Assets").mkdir(parents=True)
    output = tmp_path / "out"
    output.mkdir()
    pipeline = Pipeline(str(unity_project), str(output))
    pipeline.state.rbx_place = RbxPlace()
    pipeline.state.rbx_place.scripts = [script]
    pipeline.ctx.scene_runtime = {}
    pipeline._run_contract_verifier({"topology": topology})
    contract_errs = [
        e for e in pipeline.ctx.errors if e.startswith(CONTRACT_ERROR_PREFIX)
    ]
    assert len(pipeline.ctx.errors) != 0, "the generic boundary must fail closed"
    # The promoted error names THIS field/child — not a hardcoded weaponSlot.
    assert any(
        "rig_binding_present" in e and field in e and child in e
        for e in contract_errs
    ), f"the promoted error must key on the carrier's {field}/{child}: {contract_errs}"


def test_boundary_generic_discharged_binding_keys_on_field(tmp_path: Path) -> None:
    """GENERIC discharge (acceptance g-generic) — the SAME generic field/child
    (``gunSlot`` / ``GunMount``) DISCHARGES through the real producer -> lowering
    -> verifier chain: the resolver/reroute/verifier all key on the carrier's
    ``field``/``child``, the lowered output reroutes ``self:_resolveGunMount()``,
    and the verifier passes (no row). A field-name hardcode anywhere would break
    EITHER this (false RED) or the factored-out test above (false PASS)."""
    field, child, class_name = "gunSlot", "GunMount", "Soldier"
    entry, key = _resolve_real_rig_fact(
        tmp_path, field=field, child=child, class_name=class_name
    )
    fact = entry.rig_facts[0]
    cam_receiver, cam_ordinal = fact.cam_receiver, fact.ordinal
    s = _Script(_ai_output_shape(class_name=class_name, field=field), source_path=key)
    lower_rifle_rig_retarget([s], {key: entry})
    # Discharge keyed on the carrier's field/child; r3 5-key shape with the
    # deterministic cam_receiver/cam_ordinal anchor carried from the fact.
    assert s.rig_binding == {
        "field": field, "child": child, "present": True,
        "cam_receiver": cam_receiver, "cam_ordinal": cam_ordinal,
    }
    assert f"self:_resolve{child}()" in s.luau_source
    # The consumer GetRifle's reads were rerouted (no raw self.<field> read in it).
    getrifle = re.search(
        rf"function {class_name}:GetRifle\(\).*?\n    return rifle\nend",
        s.luau_source, re.S,
    )
    assert getrifle is not None and f"self.{field}" not in getrifle.group(0)

    script = RbxScript(
        name=class_name, source=s.luau_source, rig_binding=s.rig_binding
    )
    topology = {"modules": {class_name: {"stem": class_name}}}
    res = verify_contract(topology, [script])
    rig_rows = [v for v in res.violations if v.check == "rig_binding_present"]
    assert rig_rows == [], (
        f"a discharged generic binding ({field}/{child}) must verify clean: "
        f"{rig_rows}"
    )
    assert not any("rig_binding_present" in e for e in fail_closed_errors(res))


# ===========================================================================
# 2b. REDESIGN r3 — receiver/ordinal-anchored check-D exemption, END-TO-END.
# The original r1 bug: when the AI write IS a positional ordinal AND the Tier-2
# neutralize SKIPS (ambiguity), the dead ordinal write SURVIVES; check D at budget
# 0 fail-closed `child_ordinal_survivor` on a CORRECTLY discharged binding,
# BLOCKING a valid rifle conversion. r3 EXEMPTS that one credited dead write —
# POSITIVELY anchored on the carrier's `cam_receiver` + `cam_ordinal` (the
# deterministic upstream identity), never a blanket field-only mask. These tests
# drive the WHOLE producer/lowering/verifier chain: the carrier's 5-key shape is
# the load-bearing anchor end-to-end.
# ===========================================================================
def _lower_with_awake_write(
    awake_write: str,
    *,
    field: str = "weaponSlot",
    child: str = "WeaponSlot",
    cam_receiver: str = "cam",
    ordinal: int = 0,
) -> _Script:
    """Run the REAL lowering over an AI-output shape whose Awake carries a SPECIFIC
    camera-child write line (``awake_write``) — chosen so the Tier-2 neutralize
    SKIPS on ambiguity, leaving a surviving positional ordinal write — and the
    yielding GetRifle consumer reads (which the reroute discharges). The fact's
    ``cam_receiver``/``ordinal`` are stamped into the carrier (the r3 anchor). The
    consumer reads (NOT the Awake write) are what discharge; the Awake write here
    is a READ-FREE single statement so discharge stays True with a survivor present."""
    src = (
        "local Player = {}\n"
        "Player.__index = Player\n"
        "function Player.new()\n"
        "    local self = setmetatable({}, Player)\n"
        "    return self\n"
        "end\n"
        "function Player:Awake()\n"
        "    self.cam = workspace.CurrentCamera\n"
        f"    {awake_write}\n"
        "end\n"
        "function Player:GetRifle()\n"
        f"    local rifle = self.host.instantiatePrefab(self.riflePrefab, self.{field}, pivotOf(self.{field}))\n"
        f"    if self.{field} then rifle:PivotTo(pivotOf(self.{field})) end\n"
        "    return rifle\n"
        "end\n"
        "return Player\n"
    )
    s = _Script(src)
    fact = RigRootedRetargetFact(
        field_name=field, child_name=child, cam_receiver=cam_receiver, ordinal=ordinal
    )
    crs = ChildRefScript(
        facts=(), getchild_total=1, resolved_total=1, rig_facts=(fact,)
    )
    lower_rifle_rig_retarget([s], {s.source_path: crs})
    return s


def _verify_budget0(script: RbxScript) -> object:
    """Run the REAL verifier over ``script`` at check-D budget 0
    (``{getchild_total:1, resolved_total:1}`` — the resolved Player)."""
    script.child_ref_resolution = {"getchild_total": 1, "resolved_total": 1}
    return verify_contract(_TOPOLOGY, [script])


def test_r3_check_d_does_not_false_positive_on_discharged_rig_dead_write(
    tmp_path: Path,
) -> None:
    """REDESIGN r3 (acceptance f-r3.i) END-TO-END — THE r1 BUG IS GONE. A discharged
    rig binding whose credited dead ordinal write SURVIVES (Tier-2 neutralize
    skipped on the ambiguous single-line ``if self.cam then ... end``) drives the
    WHOLE chain: the lowering stamps ``present=True`` + the r3 anchor
    (``cam_receiver``/``cam_ordinal``), and check D at budget 0 EXEMPTS that one
    credited site — receiver ``self.cam`` AND ordinal ``cam_ordinal+1`` — so NO
    ``child_ordinal_survivor`` fires and the conversion is NOT blocked. Pre-r3 (a
    field-only / receiver-blind exemption) this fail-closed on a valid binding."""
    s = _lower_with_awake_write(
        "if self.cam then self.weaponSlot = self.cam:GetChildren()[1] end"
    )
    # Discharged via the read reroute, 5-key r3 carrier with the deterministic anchor.
    rb = s.rig_binding
    assert isinstance(rb, dict)
    assert rb["present"] is True
    assert rb["cam_receiver"] == "cam" and rb["cam_ordinal"] == 0
    # The credited dead ordinal write genuinely SURVIVES (the false-positive trigger).
    assert "self.cam:GetChildren()[1]" in s.luau_source, (
        "the credited dead ordinal write must survive (Tier-2 skipped) for this "
        "witness to exercise the exemption"
    )
    script = RbxScript(name="Player", source=s.luau_source, rig_binding=rb)
    res = _verify_budget0(script)
    survivor = [v for v in res.violations if v.check == "child_ordinal_survivor"]
    assert survivor == [], (
        "check D must EXEMPT the discharged rig's credited dead write (r1 bug "
        f"fixed): got {[v.detail for v in survivor]}"
    )
    rig_rows = [v for v in res.violations if v.check == "rig_binding_present"]
    assert rig_rows == [], f"a discharged binding must not fail the binding floor: {rig_rows}"
    assert fail_closed_errors(res) == [], (
        f"a discharged rig with a dead credited survivor must not fail closed: "
        f"{fail_closed_errors(res)}"
    )


def test_r3_check_d_still_fires_on_non_credited_ordinal_survivor() -> None:
    """REDESIGN r3 (acceptance f-r3.iii) END-TO-END — the exemption is the EXACT
    credited site, NOT a blanket field-only mask. A SAME-receiver write at a
    DIFFERENT ordinal (``self.cam:GetChildren()[2]`` when the credited init was
    ``[1]``/ordinal 0) is a genuine survivor: ``k=2 != cam_ordinal+1=1`` ⇒ COUNTED
    ⇒ check D fires ``child_ordinal_survivor`` and the conversion fails closed.
    Proves the ``cam_ordinal`` anchor is load-bearing (a field-only r8 mask would
    have FALSE-PASSED this — the silent-miss r3 closes)."""
    s = _lower_with_awake_write(
        "if self.cam then self.weaponSlot = self.cam:GetChildren()[2] end"
    )
    rb = s.rig_binding
    assert isinstance(rb, dict) and rb["present"] is True and rb["cam_ordinal"] == 0
    assert "self.cam:GetChildren()[2]" in s.luau_source
    script = RbxScript(name="Player", source=s.luau_source, rig_binding=rb)
    res = _verify_budget0(script)
    survivor = [v for v in res.violations if v.check == "child_ordinal_survivor"]
    assert survivor != [], (
        "a non-credited (different-ordinal) survivor must STILL fire check D — the "
        "exemption is the exact credited site, not a field-only mask"
    )
    assert any("child_ordinal_survivor" in e for e in fail_closed_errors(res))


def test_r3_check_d_still_fires_on_different_receiver_survivor() -> None:
    """REDESIGN r3 (acceptance f-r3.ii) END-TO-END — a SAME-field survivor through a
    DIFFERENT receiver (``self.muzzle:GetChildren()[1]``, not the credited
    ``self.cam``) is NOT the credited child-ref access ⇒ COUNTED ⇒ check D fires.
    Proves the ``cam_receiver`` anchor is load-bearing (codex r8: a receiver-blind
    exemption would have masked this genuine survivor)."""
    s = _lower_with_awake_write(
        "if self.cam then self.weaponSlot = self.muzzle:GetChildren()[1] end"
    )
    rb = s.rig_binding
    assert isinstance(rb, dict) and rb["present"] is True and rb["cam_receiver"] == "cam"
    assert "self.muzzle:GetChildren()[1]" in s.luau_source
    script = RbxScript(name="Player", source=s.luau_source, rig_binding=rb)
    res = _verify_budget0(script)
    survivor = [v for v in res.violations if v.check == "child_ordinal_survivor"]
    assert survivor != [], (
        "a different-receiver survivor must STILL fire check D — the exemption "
        "anchors on the carrier's cam_receiver, not the bare field"
    )
    assert any("child_ordinal_survivor" in e for e in fail_closed_errors(res))


def test_r3_check_d_exemption_anchors_on_generic_receiver_and_ordinal(
    tmp_path: Path,
) -> None:
    """REDESIGN r3 GENERIC (acceptance f-r3 / g-generic) — the exemption is keyed on
    the carrier's ``cam_receiver``/``cam_ordinal`` projections, NOT hardcoded
    ``cam``/0. A different camera symbol (``view``) and ordinal (``2``) credited by
    the fact EXEMPT exactly the matching survivor ``self.view:GetChildren()[3]``
    (``k = cam_ordinal+1 = 3``), while a stray ``self.view:GetChildren()[4]`` STILL
    fires. Drives the same lowering+verifier chain end-to-end."""
    s = _lower_with_awake_write(
        "if self.view then self.weaponSlot = self.view:GetChildren()[3] end",
        cam_receiver="view",
        ordinal=2,
    )
    rb = s.rig_binding
    assert isinstance(rb, dict)
    assert rb["cam_receiver"] == "view" and rb["cam_ordinal"] == 2
    assert rb["present"] is True
    assert "self.view:GetChildren()[3]" in s.luau_source
    script = RbxScript(name="Player", source=s.luau_source, rig_binding=rb)
    res = _verify_budget0(script)
    assert [v for v in res.violations if v.check == "child_ordinal_survivor"] == [], (
        "the credited generic (view/ordinal 2 -> [3]) dead write must be exempted"
    )
    assert fail_closed_errors(res) == []

    # The stray ordinal [4] on the SAME receiver is non-credited -> STILL fires.
    stray = _lower_with_awake_write(
        "if self.view then self.weaponSlot = self.view:GetChildren()[4] end",
        cam_receiver="view",
        ordinal=2,
    )
    stray_script = RbxScript(
        name="Player", source=stray.luau_source, rig_binding=stray.rig_binding
    )
    stray_res = _verify_budget0(stray_script)
    assert [v for v in stray_res.violations if v.check == "child_ordinal_survivor"] != [], (
        "a stray non-credited ordinal on the credited receiver must STILL fire"
    )


# ---------------------------------------------------------------------------
# REAL-CHAIN check-D witness — NO hand-built fact, NO hardcoded anchor (r3 fix).
# The tests above use a HAND-BUILT RigRootedRetargetFact (acceptable to unit-
# witness check-D logic in isolation), but 1.4 is the END-TO-END witness slice and
# must witness the FULL fact->carrier PROMOTION: the real resolver computes
# cam_receiver/ordinal, the real lowering STAMPS them into the carrier, and the
# real verifier's check-D exemption matches on THOSE stamped keys. So if the
# lowering's promotion regresses (drops/garbles cam_receiver/cam_ordinal), the
# exemption silently reverts to a field-only mask and these tests RED.
# ---------------------------------------------------------------------------
def _real_chain_ai_output_with_survivor(*, class_name: str, field: str) -> str:
    """An AI-output Player shape whose Awake carries a SURVIVING credited dead
    ordinal write — the ambiguous single-line ``if self.cam then self.<field> =
    self.cam:GetChildren()[1] end`` Tier-2 SKIPS — plus the yielding GetRifle
    consumer reads the read-reroute discharges. ``cam`` matches the real
    resolver's cam_receiver and ``[1]`` matches its credited ordinal+1 (the C# in
    ``_resolve_real_rig_fact`` is ``cam = Camera.main.transform; <field> =
    cam.GetChild(0)`` -> cam_receiver='cam', ordinal=0). The PROMOTION (not this
    source) decides whether the survivor is exempt."""
    return (
        f"local {class_name} = {{}}\n"
        f"{class_name}.__index = {class_name}\n"
        f"function {class_name}.new()\n"
        f"    local self = setmetatable({{}}, {class_name})\n"
        "    return self\n"
        "end\n"
        f"function {class_name}:Awake()\n"
        "    self.cam = workspace.CurrentCamera\n"
        f"    if self.cam then self.{field} = self.cam:GetChildren()[1] end\n"
        "end\n"
        f"function {class_name}:GetRifle()\n"
        f"    local rifle = self.host.instantiatePrefab(self.riflePrefab, self.{field}, pivotOf(self.{field}))\n"
        f"    if self.{field} then rifle:PivotTo(pivotOf(self.{field})) end\n"
        "    return rifle\n"
        "end\n"
        f"return {class_name}\n"
    )


def _lower_via_real_producer_with_survivor(
    tmp_path: Path, *, field: str, child: str, class_name: str
) -> tuple[_Script, RigRootedRetargetFact]:
    """Drive the WHOLE r3 promotion chain with NO hand-built carrier: the REAL
    resolver (``build_child_ref_map`` -> ``_resolve_rig_facts``) computes the
    ``RigRootedRetargetFact`` (and thus its ``cam_receiver``/``ordinal``); the REAL
    lowering then STAMPS those values FROM the fact INTO the ``rig_binding``
    carrier. Returns ``(edited_script, real_fact)`` so the caller asserts the
    carrier's anchor came from the fact, never a literal."""
    entry, key = _resolve_real_rig_fact(
        tmp_path, field=field, child=child, class_name=class_name
    )
    assert entry.rig_facts, "the real producer must admit the rig fact"
    fact = entry.rig_facts[0]
    s = _Script(
        _real_chain_ai_output_with_survivor(class_name=class_name, field=field),
        source_path=key,
    )
    # The lowering reads cam_receiver/ordinal OFF THE REAL FACT (not hand-built).
    lower_rifle_rig_retarget([s], {key: entry})
    return s, fact


def _verify_budget0_for(script: RbxScript, topology: dict[str, object]) -> object:
    """Check-D budget 0 (resolved Player) over an arbitrary-module ``script``."""
    script.child_ref_resolution = {"getchild_total": 1, "resolved_total": 1}
    return verify_contract(topology, [script])


def test_r3_real_chain_check_d_exempts_promoted_anchor_end_to_end(
    tmp_path: Path,
) -> None:
    """REAL-CHAIN END-TO-END WITNESS (acceptance f-r3.i, full promotion) — drives
    the WHOLE r3 chain with NO hand-built fact and NO hardcoded anchor: the REAL
    resolver computes ``cam_receiver``/``ordinal`` from the C# + hierarchy, the REAL
    lowering STAMPS them into the carrier, and the REAL verifier's check-D exemption
    matches the surviving credited dead write on THOSE stamped keys. The surviving
    site really exists (Tier-2 skipped), check D at budget 0 EXEMPTS it (no
    ``child_ordinal_survivor``, not blocked) — and because the matching keys came
    from the REAL fact via the REAL lowering, a promotion regression (lowering drops
    or garbles ``cam_receiver``/``cam_ordinal``) flips the exemption off and REDS
    this test. Generic: every load-bearing value is read from the fact/carrier."""
    field, child, class_name = "gunSlot", "GunMount", "Soldier"
    s, fact = _lower_via_real_producer_with_survivor(
        tmp_path, field=field, child=child, class_name=class_name
    )
    rb = s.rig_binding
    assert isinstance(rb, dict)
    # The carrier's anchor was PROMOTED from the real fact — assert equality against
    # the FACT's values (no literals), so this is a true promotion witness.
    assert rb["cam_receiver"] == fact.cam_receiver, (
        "the lowering must PROMOTE the resolver fact's cam_receiver into the carrier"
    )
    assert rb["cam_ordinal"] == fact.ordinal, (
        "the lowering must PROMOTE the resolver fact's ordinal into cam_ordinal"
    )
    assert rb["present"] is True, "the read reroute must discharge present=True"
    # The credited dead ordinal write GENUINELY survives (the exemption's target).
    # The surviving site is keyed on the REAL fact's receiver+ordinal, never a literal.
    survivor_site = (
        f"self.{field} = self.{fact.cam_receiver}:GetChildren()[{fact.ordinal + 1}]"
    )
    assert survivor_site in s.luau_source, (
        f"the credited dead ordinal write must survive Tier-2 for this witness: "
        f"{survivor_site!r}"
    )

    topology = {"modules": {class_name: {"stem": class_name}}}
    script = RbxScript(name=class_name, source=s.luau_source, rig_binding=rb)
    res = _verify_budget0_for(script, topology)
    survivor = [v for v in res.violations if v.check == "child_ordinal_survivor"]
    assert survivor == [], (
        "check D must EXEMPT the credited dead write whose anchor was PROMOTED from "
        f"the real fact (promotion intact): {[v.detail for v in survivor]}"
    )
    assert [v for v in res.violations if v.check == "rig_binding_present"] == []
    assert fail_closed_errors(res) == [], (
        f"a discharged rig with a promoted-anchor survivor must not fail closed: "
        f"{fail_closed_errors(res)}"
    )


def test_r3_real_chain_check_d_fires_when_survivor_ordinal_diverges_from_promotion(
    tmp_path: Path,
) -> None:
    """REAL-CHAIN ANCHOR-DISCRIMINATION WITNESS (acceptance f-r3.iii, full
    promotion) — proves the exemption READ the PROMOTED ``cam_ordinal`` (not a
    blanket field mask). Drive the SAME real producer->lowering promotion, then
    MUTATE the SURVIVING SITE to a DIFFERENT ordinal (``[k+1]``) than the one the
    real fact credited. The surviving site no longer matches the promoted anchor
    (``k != cam_ordinal+1``) -> check D FIRES ``child_ordinal_survivor`` and the
    conversion fails closed. If the promotion had dropped ``cam_ordinal`` the
    exemption could not discriminate; that this REDS only after the mutation proves
    the anchor came from the real fact and is load-bearing."""
    field, child, class_name = "gunSlot", "GunMount", "Soldier"
    s, fact = _lower_via_real_producer_with_survivor(
        tmp_path, field=field, child=child, class_name=class_name
    )
    rb = s.rig_binding
    assert isinstance(rb, dict) and rb["present"] is True
    credited = f"self.{fact.cam_receiver}:GetChildren()[{fact.ordinal + 1}]"
    diverged = f"self.{fact.cam_receiver}:GetChildren()[{fact.ordinal + 2}]"
    mutated_source = s.luau_source.replace(credited, diverged, 1)
    assert mutated_source != s.luau_source, "the surviving site must be present to mutate"
    assert diverged in mutated_source

    topology = {"modules": {class_name: {"stem": class_name}}}
    script = RbxScript(name=class_name, source=mutated_source, rig_binding=rb)
    res = _verify_budget0_for(script, topology)
    survivor = [v for v in res.violations if v.check == "child_ordinal_survivor"]
    assert survivor != [], (
        "a survivor at a DIFFERENT ordinal than the promoted cam_ordinal must FIRE "
        "check D — the exemption discriminates on the promoted anchor, not the field"
    )
    assert any("child_ordinal_survivor" in e for e in fail_closed_errors(res))


def test_r3_real_chain_check_d_fires_when_survivor_receiver_diverges_from_promotion(
    tmp_path: Path,
) -> None:
    """REAL-CHAIN ANCHOR-DISCRIMINATION WITNESS (acceptance f-r3.ii, full promotion)
    — proves the exemption READ the PROMOTED ``cam_receiver``. Same real
    producer->lowering promotion, but MUTATE the surviving site's RECEIVER to a
    different symbol than the fact credited. The site no longer matches the promoted
    receiver -> check D FIRES. A promotion that garbled ``cam_receiver`` (or a
    receiver-blind exemption) would FALSE-PASS this genuine survivor."""
    field, child, class_name = "gunSlot", "GunMount", "Soldier"
    s, fact = _lower_via_real_producer_with_survivor(
        tmp_path, field=field, child=child, class_name=class_name
    )
    rb = s.rig_binding
    assert isinstance(rb, dict) and rb["present"] is True
    assert fact.cam_receiver != "muzzle", "pick a receiver distinct from the credited one"
    credited = f"self.{fact.cam_receiver}:GetChildren()[{fact.ordinal + 1}]"
    diverged = f"self.muzzle:GetChildren()[{fact.ordinal + 1}]"
    mutated_source = s.luau_source.replace(credited, diverged, 1)
    assert mutated_source != s.luau_source and diverged in mutated_source

    topology = {"modules": {class_name: {"stem": class_name}}}
    script = RbxScript(name=class_name, source=mutated_source, rig_binding=rb)
    res = _verify_budget0_for(script, topology)
    survivor = [v for v in res.violations if v.check == "child_ordinal_survivor"]
    assert survivor != [], (
        "a survivor through a DIFFERENT receiver than the promoted cam_receiver must "
        "FIRE check D — the exemption discriminates on the promoted receiver anchor"
    )
    assert any("child_ordinal_survivor" in e for e in fail_closed_errors(res))


def test_r3_real_chain_exemption_dies_if_promotion_drops_anchor_keys(
    tmp_path: Path,
) -> None:
    """REAL-CHAIN NON-TAUTOLOGY GUARD — confirms the exemption is LOAD-BEARING on the
    promoted keys: if the lowering had NOT promoted ``cam_receiver``/``cam_ordinal``
    into the carrier (a regression), the same surviving credited dead write would
    NOT be exempted and check D would FIRE. Simulated by stripping the promoted keys
    from the REAL carrier (mimicking a promotion that dropped them), holding source +
    discharge fixed. This makes the exemption a genuine guard: the GREEN of the
    end-to-end exemption test above depends on the promotion actually happening."""
    field, child, class_name = "gunSlot", "GunMount", "Soldier"
    s, fact = _lower_via_real_producer_with_survivor(
        tmp_path, field=field, child=child, class_name=class_name
    )
    rb = s.rig_binding
    assert isinstance(rb, dict)
    # A carrier as it would be if the promotion DROPPED the anchor keys (regression).
    no_anchor = {"field": rb["field"], "child": rb["child"], "present": rb["present"]}
    topology = {"modules": {class_name: {"stem": class_name}}}
    script = RbxScript(name=class_name, source=s.luau_source, rig_binding=no_anchor)
    res = _verify_budget0_for(script, topology)
    survivor = [v for v in res.violations if v.check == "child_ordinal_survivor"]
    assert survivor != [], (
        "WITHOUT the promoted cam_receiver/cam_ordinal anchor the credited dead "
        "write must NOT be exempted -> check D FIRES. (Proves the end-to-end "
        "exemption witness depends on the real promotion, not on the source alone.)"
    )


# ===========================================================================
# 3. FRESH-CONVERSION E2E (acceptance g — conversion half).
# Assert on the REAL captured pipeline OUTPUT (the corpus fixture S2 regenerated
# from a real run) that on the LIVE AI shape the rifle binding is rerouted and
# seats under the rig's WeaponSlot. DESIGN INTENT: this asserts the read-reroute
# fires on the REAL live AI-output shape (the D-S2-REDESIGN case).
# ===========================================================================
def _load_fixture_player() -> _PlayerFixture:
    """Return the captured SimpleFPS Player entry — the real-pipeline
    conversion-output source of truth — typed as ``_PlayerFixture``."""
    fx = json.loads(_SIMPLEFPS_FIXTURE.read_text(encoding="utf-8"))
    player = next(s for s in fx["scripts"] if s["name"] == "Player")
    rb = player.get("rig_binding")
    assert isinstance(rb, dict), "the captured Player must carry a rig_binding carrier"
    return _PlayerFixture(
        name=str(player["name"]), source=str(player["source"]), rig_binding=rb
    )


@pytest.mark.skipif(
    not _SIMPLEFPS_FIXTURE.exists(), reason="SimpleFPS corpus fixture not present"
)
def test_e2e_captured_conversion_rifle_binding_present_on_live_shape() -> None:
    """ACCEPTANCE (g) — on the REAL captured pipeline output the Player binding is
    DISCHARGED present=True. This is the live AI shape the OLD write-anchored
    lowering abstained on (D-S2-REDESIGN: the cache collapsed the Camera.main
    ordinal to a non-ordinal write); Path A's read reroute discharges it. Keyed on
    the carrier's projections, not a hardcoded literal."""
    player = _load_fixture_player()
    rb = player["rig_binding"]
    assert rb.get("present") is True, (
        "the captured Player rig_binding must be discharged present=True on the "
        "real live shape (the Path A read-reroute fires regardless of write shape)"
    )
    field = rb.get("field")
    child = rb.get("child")
    assert isinstance(field, str) and field, "carrier must carry a field projection"
    assert isinstance(child, str) and child, "carrier must carry a child projection"
    # REDESIGN r3 — the captured carrier MUST carry the deterministic check-D anchor:
    # cam_receiver (the C# camera receiver text, NEVER "" for an admitted fact) and
    # cam_ordinal (the credited GetChild ordinal, an int). These are the load-bearing
    # upstream identity the check-D exemption keys on; if the regen capture / rehydrate
    # dropped either, the exemption silently reverts to the field-only r8 mask.
    cam_receiver = rb.get("cam_receiver")
    cam_ordinal = rb.get("cam_ordinal")
    assert isinstance(cam_receiver, str) and cam_receiver, (
        "the captured carrier must carry a non-empty cam_receiver (the deterministic "
        f"r3 check-D anchor); got {cam_receiver!r}"
    )
    assert isinstance(cam_ordinal, int), (
        f"the captured carrier must carry an int cam_ordinal; got {cam_ordinal!r}"
    )


@pytest.mark.skipif(
    not _SIMPLEFPS_FIXTURE.exists(), reason="SimpleFPS corpus fixture not present"
)
def test_e2e_captured_reads_rerouted_to_resolver_targeting_rig() -> None:
    """ACCEPTANCE (g) — on the REAL captured output: the ``self.<field>`` consumer
    reads are rerouted to ``self:_resolve<Child>()`` AND the resolver targets the
    ``_MainCameraRig``'s ``<Child>`` slot. Derives the resolver/call names from the
    carrier's ``field``/``child`` so this stays GENERIC (no hardcoded mechanism)."""
    player = _load_fixture_player()
    rb = player["rig_binding"]
    child = str(rb["child"])
    src = player["source"]
    resolver_def = f"function Player:_resolve{child}("
    resolver_call = f"self:_resolve{child}()"
    assert resolver_def in src, (
        f"the captured output must inject the per-instance resolver {resolver_def!r}"
    )
    assert resolver_call in src, (
        f"the captured output must reroute >=1 consumer read to {resolver_call!r}"
    )
    # The resolver seats on the rig: it scans for the _MainCameraRig attribute and
    # looks up the child by name under it (a real Instance via FindFirstChild).
    assert 'GetAttribute("_MainCameraRig")' in src, (
        "the resolver must target the _MainCameraRig Model (the rig anchor)"
    )
    assert f'FindFirstChild("{child}", true)' in src, (
        f"the resolver must look up the rig child {child!r} under the rig"
    )


@pytest.mark.skipif(
    not _SIMPLEFPS_FIXTURE.exists(), reason="SimpleFPS corpus fixture not present"
)
def test_e2e_captured_conversion_independently_verifies_green() -> None:
    """ACCEPTANCE (g) — running the REAL verifier over the captured Player (with
    its real ``rig_binding`` carrier + real source) produces ZERO
    ``rig_binding_present`` rows: the independent source scan AGREES the binding
    landed. This proves the captured discharge is REAL, not a stamp-only claim —
    the verifier re-derives discharge from the captured source itself."""
    player = _load_fixture_player()
    script = RbxScript(
        name="Player", source=player["source"], rig_binding=player["rig_binding"]
    )
    res = verify_contract(_TOPOLOGY, [script])
    rig_rows = [v for v in res.violations if v.check == "rig_binding_present"]
    assert rig_rows == [], (
        f"the captured discharged binding must verify clean, got {rig_rows}"
    )
    assert not any("rig_binding_present" in e for e in fail_closed_errors(res))


@pytest.mark.skipif(
    not _SIMPLEFPS_FIXTURE.exists(), reason="SimpleFPS corpus fixture not present"
)
def test_e2e_captured_player_passes_real_pipeline_gate_not_blocked(
    tmp_path: Path,
) -> None:
    """REDESIGN r3 (acceptance f-r3 / g) END-TO-END — the captured live Player,
    carried with its REAL 5-key ``rig_binding`` (incl. ``cam_receiver``/
    ``cam_ordinal``) and its real ``child_ref_resolution`` budget, drives the REAL
    ``Pipeline._run_contract_verifier`` gate and is NOT blocked: neither the rig
    binding floor NOR check D (the r1 false-positive) lands an error on
    ``ctx.errors`` -> conversion ``success`` stays True. This is the original r1
    bug — the rifle conversion blocked by check D — proven GONE on the real
    captured shape through the same hook the corpus gate uses."""
    player = _load_fixture_player()
    fx = json.loads(_SIMPLEFPS_FIXTURE.read_text(encoding="utf-8"))
    raw = next(s for s in fx["scripts"] if s["name"] == "Player")
    # Carry the captured child_ref_resolution budget so check D runs end-to-end.
    crr = raw.get("child_ref_resolution")
    assert isinstance(crr, dict), "the captured Player must carry child_ref_resolution"
    script = RbxScript(
        name="Player",
        source=player["source"],
        rig_binding=player["rig_binding"],
        child_ref_resolution=crr,
    )
    gate = _run_pipeline_gate([script], tmp_path)
    assert gate["success"] is True, (
        "the captured discharged Player must NOT be blocked end-to-end (r1 bug "
        f"fixed); got ctx.errors {gate['errors']}"
    )
    assert not any("child_ordinal_survivor" in e for e in gate["errors"]), (
        f"check D must not false-positive on the captured discharged Player: "
        f"{gate['errors']}"
    )
    assert not any("rig_binding_present" in e for e in gate["errors"])


@pytest.mark.skipif(
    not _SIMPLEFPS_FIXTURE.exists(), reason="SimpleFPS corpus fixture not present"
)
def test_e2e_captured_output_is_loadable_luau() -> None:
    """ACCEPTANCE (c-i, end-to-end) — the captured Player source (resolver spliced
    BEFORE ``return Player``) is valid, loadable Luau: the read reroute + the
    injected resolver did not produce unloadable output on the real shape."""
    if not luau_analyze_path():
        pytest.skip("luau-analyze not installed")
    from utils.luau_analyze import syntax_errors_for_source

    player = _load_fixture_player()
    errs = syntax_errors_for_source(player["source"])
    assert errs == [], f"captured Player Luau has syntax errors: {errs}"


# ---------------------------------------------------------------------------
# The genuinely-FRESH full conversion (slow). Excluded from ``-m "not slow"``
# CI; the captured-fixture tests above are the fast conversion-output proof.
# ---------------------------------------------------------------------------
@pytest.mark.slow
def test_e2e_fresh_simplefps_conversion_seats_rifle_binding(tmp_path: Path) -> None:
    """ACCEPTANCE (g — FRESH) — a genuinely fresh generic SimpleFPS conversion
    through the REAL pipeline produces a Player module whose rifle binding is
    rerouted + present, seated under the ``_MainCameraRig``'s ``WeaponSlot``.

    Runs ONLY when the test-projects root is configured (``regen_contract_corpus``
    points at the populated main checkout); otherwise SKIPS — the fresh
    conversion needs the full Unity project the CI image does not carry. The fast
    captured-fixture tests above cover the conversion-output assertion for CI."""
    import os

    projects_root = os.environ.get("CONTRACT_CORPUS_PROJECTS_ROOT")
    if not projects_root or not Path(projects_root).exists():
        pytest.skip(
            "set CONTRACT_CORPUS_PROJECTS_ROOT to a populated test_projects root "
            "to run the fresh full SimpleFPS conversion"
        )

    # Drive the corpus regen (warm cache) — it runs the REAL pipeline end-to-end
    # and captures the live output, refusing to write on any real violation.
    repo_tools = Path(__file__).parent.parent / "tools" / "regen_contract_corpus.py"
    out_fixture = tmp_path / "fixture.json"
    proc = subprocess.run(
        [sys.executable, str(repo_tools), "SimpleFPS", "--out", str(out_fixture)],
        capture_output=True,
        text=True,
        env={**os.environ, "CONTRACT_CORPUS_PROJECTS_ROOT": projects_root},
        timeout=1800,
    )
    assert proc.returncode == 0, (
        f"fresh conversion/regen failed:\nstdout={proc.stdout}\nstderr={proc.stderr}"
    )
    fx = json.loads(out_fixture.read_text(encoding="utf-8"))
    player = next(s for s in fx["scripts"] if s["name"] == "Player")
    rb = player.get("rig_binding")
    assert isinstance(rb, dict) and rb.get("present") is True, (
        "a FRESH conversion must discharge the Player rifle binding present=True "
        "on the live AI shape (the Path A read reroute fires RHS-agnostically)"
    )
    child = str(rb["child"])
    src = player["source"]
    assert f"function Player:_resolve{child}(" in src
    assert f"self:_resolve{child}()" in src
    assert 'GetAttribute("_MainCameraRig")' in src
    assert f'FindFirstChild("{child}", true)' in src
