"""Tests for the auto-generated CameraRigFollower client script.

The follower makes the converted Unity main-camera Model (tagged
``_MainCameraRig`` by ``scene_converter``) track ``workspace.CurrentCamera``
each frame, so camera-child objects ride the player's view.
"""

from converter.autogen import generate_camera_rig_follower_script


class TestCameraRigFollowerScript:
    def test_is_a_client_localscript(self) -> None:
        script = generate_camera_rig_follower_script()
        assert script.name == "CameraRigFollower"
        # The follower reads workspace.CurrentCamera, which is per-client,
        # so it must run client-side.
        assert script.script_type == "LocalScript"

    def test_carries_autogen_marker(self) -> None:
        """The leading marker comment lets dedupe / FPS-detection skip
        this converter-emitted script."""
        src = generate_camera_rig_follower_script().source
        assert src.startswith(
            "-- Camera Rig Follower (auto-generated by Unity converter)"
        )

    def test_pivots_rig_onto_live_camera_each_frame(self) -> None:
        src = generate_camera_rig_follower_script().source
        # Finds the rig by attribute, not by hardcoded name.
        assert 'GetAttribute("_MainCameraRig")' in src
        # Tracks the live camera via a per-frame PivotTo.
        assert "RenderStepped" in src
        assert "rig:PivotTo(cam.CFrame)" in src
        assert "workspace.CurrentCamera" in src

    def test_no_rig_is_a_clean_no_op(self) -> None:
        """When the scene has no rig, the script must return early
        rather than erroring or connecting a dead loop."""
        src = generate_camera_rig_follower_script().source
        assert "if not rig then return end" in src
