"""
api_mappings.py -- Unity C# API to Roblox Luau mapping tables.

Comprehensive lookup tables used by the code transpiler to replace Unity API
calls, types, lifecycle hooks, and service imports with Roblox equivalents.
"""

from __future__ import annotations


# ---------------------------------------------------------------------------
# API_CALL_MAP: Unity C# API -> Roblox Luau (100+ entries)
# ---------------------------------------------------------------------------

API_CALL_MAP: dict[str, str] = {
    # -- Debug --
    "Debug.Log": "print",
    "Debug.LogWarning": "warn",
    "Debug.LogError": "warn",
    # -- Physics --
    "Physics.Raycast": "workspace:Raycast",
    "Physics.RaycastAll": "workspace:Raycast",
    "Physics.OverlapSphere": "workspace:GetPartBoundsInRadius",
    "Physics.OverlapBox": "workspace:GetPartBoundsInBox",
    "Physics.SphereCast": "workspace:Spherecast",
    "Physics.Linecast": "workspace:Raycast",
    "Physics.gravity": "workspace.Gravity",
    # -- GameObject --
    "Instantiate": ".Clone",
    "Destroy": ".Destroy",
    "DestroyImmediate": ":Destroy()",
    "DontDestroyOnLoad": "-- DontDestroyOnLoad: parent to ReplicatedStorage",
    "SendMessage": ":SetAttribute",  # Approximate: use attributes for inter-component comms
    "BroadcastMessage": ":SetAttribute",  # Approximate
    "gameObject.SetActive(false)": "Transparency = 1; CanCollide = false",
    "gameObject.SetActive(true)": "Transparency = 0; CanCollide = true",
    ".activeSelf": ":GetAttribute('Active') ~= false",
    ".activeInHierarchy": ":GetAttribute('Active') ~= false",
    "gameObject.name": ".Name",
    "gameObject.tag": ":GetAttribute('Tag')",
    "gameObject.layer": "CollisionGroup",
    "CompareTag": ":GetAttribute('Tag') ==",
    "GameObject.Find": "workspace:FindFirstChild",
    "GameObject.FindWithTag": "CollectionService:GetTagged",
    "GameObject.FindGameObjectsWithTag": "CollectionService:GetTagged",
    # -- Transform --
    "transform.position": ".Position",
    "transform.localPosition": ".CFrame.Position",
    "transform.rotation": ".CFrame",
    "transform.localRotation": ".CFrame",
    "transform.eulerAngles": ".Orientation",
    "transform.localScale": ".Size",
    "transform.parent": ".Parent",
    "transform.SetParent": ".Parent =",
    "transform.Find": ":FindFirstChild",
    "transform.GetChild": ":GetChildren()",
    "transform.childCount": ":GetChildren()",
    "transform.forward": ".CFrame.LookVector",
    "transform.right": ".CFrame.RightVector",
    "transform.up": ".CFrame.UpVector",
    "transform.Translate": "CFrame.new",
    "transform.Rotate": "CFrame.Angles",
    "transform.LookAt": "CFrame.lookAt",
    "transform.TransformPoint": ":PointToWorldSpace",
    "transform.InverseTransformPoint": ":PointToObjectSpace",
    # -- GetComponent --
    "GetComponent": ":FindFirstChildOfClass",
    "GetComponentInChildren": ":FindFirstChildOfClass",
    "GetComponentInParent": ":FindFirstAncestorOfClass",
    "GetComponents": ":GetChildren",
    "GetComponentsInChildren": ":GetDescendants",
    "AddComponent": "Instance.new",
    # -- Time --
    "Time.time": "workspace:GetServerTimeNow()",
    "Time.deltaTime": "dt",
    "Time.fixedDeltaTime": "dt",
    "Time.timeScale": "workspace:SetAttribute('TimeScale', 1)",
    "Time.unscaledDeltaTime": "dt",
    "Time.realtimeSinceStartup": "os.clock()",
    "Time.frameCount": "-- frameCount: no direct Roblox equivalent",
    # -- Input --
    "Input.GetKey": "UserInputService:IsKeyDown",
    "Input.GetKeyDown": "UserInputService.InputBegan",
    "Input.GetKeyUp": "UserInputService.InputEnded",
    "Input.GetButton": "UserInputService:IsKeyDown",
    "Input.GetButtonDown": "UserInputService.InputBegan",
    "Input.GetButtonUp": "UserInputService.InputEnded",
    "Input.GetMouseButton": "UserInputService:IsMouseButtonPressed",
    "Input.GetMouseButtonDown": "UserInputService.InputBegan",
    "Input.GetAxis": "UserInputService:GetGamepadState(Enum.UserInputType.Gamepad1)",
    "Input.mousePosition": "UserInputService:GetMouseLocation()",
    "Input.GetTouch": "UserInputService.TouchStarted",
    "Input.anyKeyDown": "-- Input.anyKeyDown: use UserInputService.InputBegan",
    # -- Mathf --
    "Mathf.Abs": "math.abs",
    "Mathf.Ceil": "math.ceil",
    "Mathf.CeilToInt": "math.ceil",
    "Mathf.Clamp": "math.clamp",
    "Mathf.Clamp01": "math.clamp",
    "Mathf.Floor": "math.floor",
    "Mathf.FloorToInt": "math.floor",
    "Mathf.Lerp": "math.lerp",
    "Mathf.Max": "math.max",
    "Mathf.Min": "math.min",
    "Mathf.Pow": "math.pow",
    "Mathf.Round": "math.round",
    "Mathf.Sqrt": "math.sqrt",
    "Mathf.Sin": "math.sin",
    "Mathf.Cos": "math.cos",
    "Mathf.Tan": "math.tan",
    "Mathf.Asin": "math.asin",
    "Mathf.Acos": "math.acos",
    "Mathf.Atan2": "math.atan2",
    "Mathf.Log": "math.log",
    "Mathf.Exp": "math.exp",
    "Mathf.Sign": "math.sign",
    "Mathf.PI": "math.pi",
    "Mathf.Infinity": "math.huge",
    "Mathf.Deg2Rad": "math.rad(1)",
    "Mathf.Rad2Deg": "math.deg(1)",
    "Mathf.MoveTowards": "math.clamp",
    "Mathf.SmoothDamp": "TweenService:Create",
    "Mathf.PingPong": "math.abs",
    "Mathf.PerlinNoise": "math.noise",
    # -- Vector3 --
    "Vector3.zero": "Vector3.zero",
    "Vector3.one": "Vector3.one",
    "Vector3.up": "Vector3.yAxis",
    "Vector3.down": "-Vector3.yAxis",
    "Vector3.forward": "Vector3.zAxis",
    "Vector3.back": "-Vector3.zAxis",
    "Vector3.right": "Vector3.xAxis",
    "Vector3.left": "-Vector3.xAxis",
    "Vector3.Distance": "(a - b).Magnitude",
    "Vector3.Lerp": ":Lerp",
    "Vector3.Normalize": ".Unit",
    "Vector3.Cross": ":Cross",
    "Vector3.Dot": ":Dot",
    "Vector3.Angle": "math.acos",
    "Vector3.MoveTowards": ":Lerp",
    "Vector3.ClampMagnitude": ".Unit",
    "Vector3.SignedAngle": "-- SignedAngle: compute via atan2(cross.Y, dot)",
    "Vector3.ProjectOnPlane": "-- ProjectOnPlane: v - normal * v:Dot(normal)",
    "Vector3.Project": "-- Project: use dot product projection",
    "Vector3.Reflect": "-- Reflect: d - 2 * n:Dot(d) * n",
    "Vector3.SmoothDamp": ":Lerp",
    "new Vector3": "Vector3.new",
    # -- Vector2 --
    "Vector2.zero": "Vector2.zero",
    "Vector2.one": "Vector2.one",
    "Vector2.Distance": "(a - b).Magnitude",
    "new Vector2": "Vector2.new",
    # -- Quaternion --
    "Quaternion.identity": "CFrame.new()",
    "Quaternion.Euler": "CFrame.fromEulerAnglesXYZ",
    "Quaternion.LookRotation": "CFrame.lookAt",
    "Quaternion.Lerp": ":Lerp",
    "Quaternion.Slerp": ":Lerp",
    "Quaternion.Inverse": ":Inverse()",
    "Quaternion.AngleAxis": "CFrame.fromAxisAngle",
    "Quaternion.RotateTowards": ":Lerp",
    "Quaternion.Dot": "-- Quaternion.Dot: no direct CFrame equivalent",
    "Quaternion.FromToRotation": "-- FromToRotation: compute rotation between two directions",
    # -- Color --
    "Color.red": "Color3.new(1, 0, 0)",
    "Color.green": "Color3.new(0, 1, 0)",
    "Color.blue": "Color3.new(0, 0, 1)",
    "Color.white": "Color3.new(1, 1, 1)",
    "Color.black": "Color3.new(0, 0, 0)",
    "Color.yellow": "Color3.new(1, 1, 0)",
    "Color.cyan": "Color3.new(0, 1, 1)",
    "Color.magenta": "Color3.new(1, 0, 1)",
    "Color.gray": "Color3.new(0.5, 0.5, 0.5)",
    "new Color": "Color3.new",
    # -- Rigidbody --
    "rigidbody.velocity": ".AssemblyLinearVelocity",
    "rigidbody.angularVelocity": ".AssemblyAngularVelocity",
    "rigidbody.mass": ":GetMass()",
    "rigidbody.AddForce": ":ApplyImpulse",
    "rigidbody.AddTorque": ":ApplyAngularImpulse",
    "rigidbody.isKinematic": ".Anchored",
    "rigidbody.useGravity": "workspace.Gravity",
    "rigidbody.MovePosition": ".CFrame",
    # -- Collider events --
    "OnCollisionEnter": ".Touched",
    "OnCollisionExit": ".TouchEnded",
    "OnTriggerEnter": ".Touched",
    "OnTriggerExit": ".TouchEnded",
    # -- Coroutines --
    "StartCoroutine": "task.spawn",
    "StopCoroutine": "task.cancel",
    "StopAllCoroutines": "task.cancel",
    "yield return null": "task.wait()",
    "yield return new WaitForSeconds": "task.wait",
    "yield return new WaitForEndOfFrame": "task.wait()",
    "yield return new WaitForFixedUpdate": "task.wait()",
    # -- Scene --
    "SceneManager.LoadScene": "TeleportService:Teleport",
    "SceneManager.GetActiveScene": "game.PlaceId",
    # -- Audio --
    "AudioSource.Play": ":Play()",
    "AudioSource.Stop": ":Stop()",
    "AudioSource.Pause": ":Pause()",
    "AudioSource.PlayOneShot": ":Play()",
    "AudioSource.clip": ".SoundId",
    "AudioSource.volume": ".Volume",
    "AudioSource.pitch": ".PlaybackSpeed",
    "AudioSource.loop": ".Looped",
    "AudioSource.isPlaying": ".IsPlaying",
    # -- Animation --
    "Animator.SetBool": ":SetAttribute",
    "Animator.SetFloat": ":SetAttribute",
    "Animator.SetTrigger": "AnimationTrack:Play()",
    "Animator.Play": "AnimationTrack:Play()",
    "Animation.Play": "AnimationTrack:Play()",
    # -- Camera --
    "Camera.main": "workspace.CurrentCamera",
    "Camera.fieldOfView": ".FieldOfView",
    "Camera.ScreenToWorldPoint": ":ScreenPointToRay",
    "Camera.WorldToScreenPoint": ":WorldToScreenPoint",
    # -- UI --
    "Canvas": "ScreenGui",
    "Text.text": ".Text",
    "Image.sprite": ".Image",
    "Button.onClick": ".Activated",
    "RectTransform": "UDim2",
    # -- PlayerPrefs --
    "PlayerPrefs.SetInt": "DataStoreService:GetDataStore('PlayerPrefs'):SetAsync",
    "PlayerPrefs.GetInt": "DataStoreService:GetDataStore('PlayerPrefs'):GetAsync",
    "PlayerPrefs.SetFloat": "DataStoreService:GetDataStore('PlayerPrefs'):SetAsync",
    "PlayerPrefs.GetFloat": "DataStoreService:GetDataStore('PlayerPrefs'):GetAsync",
    "PlayerPrefs.SetString": "DataStoreService:GetDataStore('PlayerPrefs'):SetAsync",
    "PlayerPrefs.GetString": "DataStoreService:GetDataStore('PlayerPrefs'):GetAsync",
    "PlayerPrefs.Save": "-- DataStoreService auto-saves",
    "PlayerPrefs.DeleteKey": "DataStoreService:GetDataStore('PlayerPrefs'):RemoveAsync",
    # -- Networking --
    "[Command]": "RemoteEvent:FireServer",
    "[ClientRpc]": "RemoteEvent:FireAllClients",
    "[SyncVar]": ":SetAttribute",
    # -- Random --
    "Random.Range": "math.random",
    "Random.value": "math.random()",
    "Random.insideUnitSphere": "Random.new():NextUnitVector()",
    "Random.insideUnitCircle": "Vector2.new(math.random() * 2 - 1, math.random() * 2 - 1).Unit",
    "UnityEngine.Random": "Random.new()",
    # -- String --
    "string.Format": "string.format",
    "string.IsNullOrEmpty": "(s == nil or s == '')",
    # -- Collections --
    # List<> and Dictionary<> handled by the variable declaration regex
    # (stripping generic types). Don't replace inline — it breaks lines.
    ".Clear()": "table.clear",
    "foreach": "for _, v in",
    # -- TextMeshPro --
    "TextMeshProUGUI": "TextLabel",
    "TextMeshPro": "TextLabel",
    "TMP_Text": "TextLabel",
    "TMP_InputField": "TextBox",
    ".SetText(": ".Text =",
    # -- DOTween --
    "DOTween.To": "TweenService:Create",
    ".DOMove(": "-- DOMove: use TweenService:Create(part, info, {Position = target})",
    ".DORotate(": "-- DORotate: use TweenService:Create(part, info, {CFrame = target})",
    ".DOScale(": "-- DOScale: use TweenService:Create(part, info, {Size = target})",
    ".DOFade(": "-- DOFade: use TweenService:Create(part, info, {Transparency = target})",
    ".DOColor(": "-- DOColor: use TweenService:Create(part, info, {Color = target})",
    ".DOLocalMove(": "-- DOLocalMove: use TweenService:Create with relative CFrame",
    ".DOKill(": "-- DOKill: cancel tween",
    ".SetEase(": "-- SetEase: use TweenInfo EasingStyle",
    ".SetDelay(": "-- SetDelay: use TweenInfo DelayTime",
    ".SetLoops(": "-- SetLoops: use TweenInfo RepeatCount",
    # -- Timeline / Playable Director --
    "PlayableDirector": "-- PlayableDirector: use animation scripts or TweenService sequences",
    "playableDirector.Play()": "-- PlayableDirector.Play: trigger animation sequence",
    "playableDirector.Stop()": "-- PlayableDirector.Stop: stop animation sequence",
    "playableDirector.Pause()": "-- PlayableDirector.Pause: pause animation sequence",
    "PlayableDirector.played": "-- PlayableDirector.played: use BindableEvent for sequence start",
    "PlayableDirector.stopped": "-- PlayableDirector.stopped: use BindableEvent for sequence end",
    ".OnComplete(": "-- OnComplete: use Tween.Completed:Connect()",
    # -- NavMesh --
    "NavMeshAgent": "-- NavMeshAgent: use Roblox PathfindingService",
    "NavMesh.CalculatePath": "PathfindingService:CreatePath()",
    ".SetDestination(": "-- SetDestination: use Path:ComputeAsync(target)",
    ".remainingDistance": "-- remainingDistance: compute from waypoints",
    ".isStopped": "-- isStopped: track manually",
    "navMeshAgent.speed": "-- NavMeshAgent.speed: set Humanoid.WalkSpeed",
    "agent.speed": "-- NavMeshAgent.speed: set Humanoid.WalkSpeed",
    "NavMeshObstacle": "-- NavMeshObstacle: no direct equivalent",
    # -- New Input System --
    "InputAction": "-- InputAction: use ContextActionService or UserInputService",
    ".ReadValue<Vector2>()": "-- ReadValue: use UserInputService input events",
    ".performed": "-- performed: use InputBegan/InputChanged",
    ".canceled": "-- canceled: use InputEnded",
    "PlayerInput": "-- PlayerInput: use UserInputService",
    # -- async/await --
    "async Task": "-- async Task: use task.spawn(function()",
    "async void": "-- async void: use task.spawn(function()",
    "await Task.Delay": "task.wait",
    "await Task.Yield()": "task.wait()",
    "UniTask": "-- UniTask: use task library",
    "await UniTask.Delay": "task.wait",
    "await UniTask.Yield()": "task.wait()",
    # -- LINQ --
    ".Where(": "-- Where: use manual loop filter",
    ".Select(": "-- Select: use manual loop map",
    ".FirstOrDefault(": "-- FirstOrDefault: use manual find",
    ".First(": "-- First: use manual find",
    ".Any(": "-- Any: use manual loop check",
    ".All(": "-- All: use manual loop check",
    ".OrderBy(": "-- OrderBy: use table.sort",
    ".OrderByDescending(": "-- OrderByDescending: use table.sort with reverse",
    ".ToList()": "-- ToList: already a table",
    ".ToArray()": "-- ToArray: already a table",
    ".Sum(": "-- Sum: use manual loop accumulator",
    ".Max(": "-- Max: use math.max in loop",
    ".Min(": "-- Min: use math.min in loop",
    ".Count(": "-- Count: use # operator or manual loop",
    ".Distinct()": "-- Distinct: use dictionary-based dedup",
    ".GroupBy(": "-- GroupBy: use manual dictionary grouping",
    # -- Cinemachine --
    "CinemachineVirtualCamera": "-- CinemachineVirtualCamera: configure workspace.CurrentCamera",
    "CinemachineBrain": "-- CinemachineBrain: use workspace.CurrentCamera",
    ".m_Lens.FieldOfView": ".FieldOfView",
    # -- Terrain --
    "Terrain.activeTerrain": "-- Terrain: use Roblox Terrain object",
    "TerrainData": "-- TerrainData: use workspace.Terrain",
    ".GetHeight(": "-- GetHeight: no direct equivalent",
    "SplatPrototype": "-- SplatPrototype: use Terrain:FillBall/FillBlock with materials",
    # -- 2D Physics --
    "Rigidbody2D": "-- Rigidbody2D: no 2D physics in Roblox",
    "Physics2D.Raycast": "workspace:Raycast",
    "Collider2D": "BasePart",
    # -- Misc --
    "Application.targetFrameRate": "-- targetFrameRate: no equivalent",
    "Application.persistentDataPath": "-- persistentDataPath: use DataStoreService",
    "Application.isPlaying": "-- isPlaying: always true at runtime",
    "Application.platform": "-- platform: use UserInputService:GetPlatform()",
    "Application.Quit": "-- Quit: no equivalent",
    "Resources.Load": "-- Resources.Load: use ReplicatedStorage:FindFirstChild",
    "Addressables.LoadAssetAsync": "-- Addressables: use ReplicatedStorage:WaitForChild",
    "Object.FindObjectOfType": "-- FindObjectOfType: use workspace:FindFirstChildOfClass",
    "Object.FindObjectsOfType": "-- FindObjectsOfType: use workspace:GetDescendants()",
    "LayerMask": "-- LayerMask: use CollisionGroups",
    "Physics.IgnoreCollision": "-- IgnoreCollision: use CollisionGroups",
    "WaitUntil": "-- WaitUntil: use while loop with task.wait()",
    "WaitWhile": "-- WaitWhile: use while loop with task.wait()",
    "Invoke(\"": "task.delay(",  # MonoBehaviour.Invoke("method", delay)
    "InvokeRepeating(": "-- InvokeRepeating: use task.spawn with while loop and task.wait",
    "CancelInvoke": "-- CancelInvoke: cancel spawned task",
    # -- UnityEvent --
    ".AddListener(": ".Event:Connect(",
    ".RemoveListener(": "-- RemoveListener: disconnect the connection",
    ".RemoveAllListeners()": "-- RemoveAllListeners: disconnect all connections",
    # -- System.Action / delegates --
    "Action<": "-- Action: use function type",
    "Func<": "-- Func: use function type",
    # -- Events / Delegates --
    # Note: "event Action<" is handled by the sanitizer, not here
    # to avoid conflicts with the "Action<" mapping
    # -- Mathf additional --
    "Mathf.Repeat": "-- Mathf.Repeat: use val % length",
    "Mathf.DeltaAngle": "-- Mathf.DeltaAngle: compute angular difference",
    "Mathf.LerpAngle": "-- Mathf.LerpAngle: interpolate angles",
    "Mathf.InverseLerp": "-- Mathf.InverseLerp: (value - a) / (b - a)",
    "Mathf.SmoothStep": "-- Mathf.SmoothStep: use TweenService easing",
    "Mathf.Approximately": "-- Mathf.Approximately: math.abs(a-b) < 0.001",
    "Mathf.NegativeInfinity": "-math.huge",
    "Mathf.Epsilon": "1e-7",
    "Mathf.NextPowerOfTwo": "-- NextPowerOfTwo: use bit32 operations",
    # -- Rigidbody additional --
    "rigidbody.drag": "-- drag: set CustomPhysicalProperties",
    "rigidbody.constraints": "-- constraints: set Anchored or use constraints",
    "rigidbody.Sleep": "-- Sleep: no Roblox equivalent",
    "rigidbody.WakeUp": "-- WakeUp: no Roblox equivalent",
    "rigidbody.IsSleeping": "-- IsSleeping: no Roblox equivalent",
    # -- Physics additional --
    "Physics.CheckSphere": "workspace:GetPartBoundsInRadius",
    "Physics.CheckBox": "workspace:GetPartBoundsInBox",
    "Physics.defaultContactOffset": "-- defaultContactOffset: no equivalent",
    # -- String additional --
    "string.Replace": "string.gsub",
    "string.Contains": "string.find",
    "string.StartsWith": "string.sub",
    "string.EndsWith": "string.sub",
    "string.Split": "string.split",
    "string.Trim": "string.match",
    "string.ToLower": "string.lower",
    "string.ToUpper": "string.upper",
    "string.Substring": "string.sub",
    "string.Join": "table.concat",
    "string.Concat": "..",
    "int.Parse": "tonumber",
    "float.Parse": "tonumber",
    "double.Parse": "tonumber",
    "bool.Parse": "-- bool.Parse: use value == 'true'",
    ".Length": "#",  # array/string length
    # -- Math additional --
    "Math.Abs": "math.abs",
    "Math.Max": "math.max",
    "Math.Min": "math.min",
    "Math.Floor": "math.floor",
    "Math.Ceil": "math.ceil",
    "Math.Round": "math.round",
    "Math.Sqrt": "math.sqrt",
    "Math.PI": "math.pi",
    # -- Array/List --
    ".Add(": "table.insert(",
    ".Remove(": "table.remove(",
    ".RemoveAt(": "table.remove(",
    ".Insert(": "table.insert(",
    ".IndexOf(": "table.find(",
    ".Reverse()": "-- Reverse: reverse table in-place",
    ".Sort()": "table.sort",
    # ContainsKey and TryGetValue handled by luau_validator, not here
    # (inline comment replacement would break the code line)
    ".GetInstanceID()": "-- GetInstanceID: no Roblox equivalent",
    ".Equals(": "==",
    ".GetHashCode()": "-- GetHashCode: no equivalent",
    ".GetType()": "typeof",
    # -- Cursor --
    "Cursor.lockState": "-- Cursor.lockState: use UserInputService.MouseBehavior",
    "Cursor.visible": "-- Cursor.visible: use UserInputService.MouseIconEnabled",
    "CursorLockMode.Locked": "Enum.MouseBehavior.LockCenter",
    "CursorLockMode.None": "Enum.MouseBehavior.Default",
    "CursorLockMode.Confined": "Enum.MouseBehavior.LockCurrentPosition",
    # -- Application --
    "Application.isPlaying": "game:GetService('RunService'):IsRunning()",
    "Application.platform": "-- Application.platform: use game:GetService('UserInputService').TouchEnabled",
    "Application.isFocused": "game:GetService('UserInputService').WindowFocused",
    "Application.isEditor": "game:GetService('RunService'):IsStudio()",
    "Application.Quit()": "-- Application.Quit: use game.Players.LocalPlayer:Kick()",
    # -- Screen --
    "Screen.width": "workspace.CurrentCamera.ViewportSize.X",
    "Screen.height": "workspace.CurrentCamera.ViewportSize.Y",
    # -- Resources --
    "Resources.Load": "-- Resources.Load: use game.ReplicatedStorage:FindFirstChild",
    # -- SceneManager --
    "SceneManager.LoadScene": "game:GetService('TeleportService'):Teleport",
    "SceneManager.LoadSceneAsync": "game:GetService('TeleportService'):TeleportAsync",
    "SceneManager.GetActiveScene": "-- GetActiveScene: use game.PlaceId",
    # -- PlayerPrefs --
    "PlayerPrefs.GetFloat": "-- PlayerPrefs: use DataStoreService or Player:GetAttribute",
    "PlayerPrefs.SetFloat": "-- PlayerPrefs: use DataStoreService or Player:SetAttribute",
    "PlayerPrefs.GetInt": "-- PlayerPrefs: use DataStoreService",
    "PlayerPrefs.SetInt": "-- PlayerPrefs: use DataStoreService",
    "PlayerPrefs.GetString": "-- PlayerPrefs: use DataStoreService",
    "PlayerPrefs.SetString": "-- PlayerPrefs: use DataStoreService",
    "PlayerPrefs.Save": "-- PlayerPrefs.Save: DataStore saves automatically",
    "PlayerPrefs.DeleteAll": "-- PlayerPrefs.DeleteAll: clear DataStore",
    # -- Destroy with delay --
    "Destroy(gameObject,": "Debris:AddItem(",
    "Destroy(this.gameObject,": "Debris:AddItem(script.Parent,",
}


# ---------------------------------------------------------------------------
# TYPE_MAP: C# types -> Luau types (40+ entries)
# ---------------------------------------------------------------------------

TYPE_MAP: dict[str, str] = {
    # Numeric
    "int": "number",
    "float": "number",
    "double": "number",
    "long": "number",
    "short": "number",
    "byte": "number",
    "uint": "number",
    "ulong": "number",
    "ushort": "number",
    "sbyte": "number",
    "decimal": "number",
    # Boolean
    "bool": "boolean",
    "Boolean": "boolean",
    # String
    "string": "string",
    "String": "string",
    "char": "string",
    # Void
    "void": "()",
    # Inferred
    "var": "",
    "dynamic": "any",
    "object": "any",
    # Unity math types
    "Vector3": "Vector3",
    "Vector2": "Vector2",
    "Vector4": "Vector3",  # no Vector4 in Roblox; approximate
    "Quaternion": "CFrame",
    "Matrix4x4": "CFrame",
    # Unity color
    "Color": "Color3",
    "Color32": "Color3",
    # Unity core
    "Transform": "BasePart",
    "GameObject": "Instance",
    "Rigidbody": "BasePart",
    "Rigidbody2D": "BasePart",
    "Collider": "BasePart",
    "Collider2D": "BasePart",
    "BoxCollider": "BasePart",
    "SphereCollider": "BasePart",
    "CapsuleCollider": "BasePart",
    "MeshCollider": "BasePart",
    "CharacterController": "Humanoid",
    # Audio
    "AudioSource": "Sound",
    "AudioClip": "Sound",
    # Camera
    "Camera": "Camera",
    # Animation
    "Animator": "AnimationController",
    "AnimationClip": "Animation",
    "RuntimeAnimatorController": "AnimationController",
    # MonoBehaviour base
    "MonoBehaviour": "-- MonoBehaviour: Roblox script",
    "ScriptableObject": "-- ScriptableObject: use ModuleScript table",
    # Physics
    "RaycastHit": "RaycastResult",
    "Ray": "Ray",
    "Bounds": "Region3",
    "Rect": "UDim2",
    # UI types
    "Canvas": "ScreenGui",
    "RectTransform": "Frame",
    "Text": "TextLabel",
    "Image": "ImageLabel",
    "Button": "TextButton",
    "Slider": "Frame",
    "Toggle": "Frame",
    "InputField": "TextBox",
    "Dropdown": "Frame",
    "ScrollRect": "ScrollingFrame",
    "RawImage": "ImageLabel",
    # TextMeshPro
    "TextMeshProUGUI": "TextLabel",
    "TextMeshPro": "TextLabel",
    "TMP_Text": "TextLabel",
    "TMP_InputField": "TextBox",
    # Navigation
    "NavMeshAgent": "PathfindingService",
    # Networking
    "NetworkBehaviour": "-- NetworkBehaviour: use RemoteEvents",
    # Collections (generic)
    "List": "{}",
    "Dictionary": "{}",
    "HashSet": "{}",
    "Queue": "{}",
    "Stack": "{}",
    "Array": "{}",
    # Coroutine
    "IEnumerator": "() -> ()",
    "Coroutine": "thread",
    # Task
    "Task": "thread",
    "UniTask": "thread",
    # Events
    "UnityEvent": "BindableEvent",
    "UnityAction": "() -> ()",
    # Misc
    "LayerMask": "number",
    "Sprite": "string",  # rbxassetid URL
    "Texture2D": "string",
    "Material": "string",
    "Shader": "string",
    "Mesh": "string",
    "PhysicMaterial": "string",
    "WaitForSeconds": "number",
    "WaitForEndOfFrame": "number",
    "Object": "Instance",
    "Component": "Instance",
    "Behaviour": "Instance",
    "MonoBehaviour[]": "{}",
    "Light": "PointLight",
    "ParticleSystem": "ParticleEmitter",
    "Terrain": "Terrain",
    "LineRenderer": "Beam",
    "TrailRenderer": "Trail",
    "Cloth": "Instance",
    "Joint": "Constraint",
    "RectTransform": "Frame",
    "Canvas": "ScreenGui",
    "Animator": "AnimationController",
    "Animation": "AnimationController",
    "AudioClip": "Sound",
    "AnimationCurve": "NumberSequence",
    "Gradient": "ColorSequence",
    "ScriptableObject": "ModuleScript",
    "TextAsset": "string",
    "NavMeshAgent": "Instance",
    "GUIStyle": "Instance",
}


# ---------------------------------------------------------------------------
# LIFECYCLE_MAP: Unity lifecycle hooks -> Roblox equivalents (15+ entries)
# ---------------------------------------------------------------------------

LIFECYCLE_MAP: dict[str, str] = {
    "Awake": "-- Awake: runs at top of script (module initialization)",
    "Start": "-- Start: runs after all Awake calls (use task.defer or Players.PlayerAdded)",
    "Update": "RunService.Heartbeat:Connect(function(dt)",
    "FixedUpdate": "RunService.Stepped:Connect(function(dt)",
    "LateUpdate": "RunService.RenderStepped:Connect(function(dt)",
    "OnEnable": "-- OnEnable: connect events here",
    "OnDisable": "-- OnDisable: disconnect events here",
    "OnDestroy": "-- OnDestroy: use Instance.Destroying or Maid pattern",
    "OnCollisionEnter": "part.Touched:Connect(function(otherPart)",
    "OnCollisionExit": "part.TouchEnded:Connect(function(otherPart)",
    "OnTriggerEnter": "part.Touched:Connect(function(otherPart)",
    "OnTriggerExit": "part.TouchEnded:Connect(function(otherPart)",
    "OnMouseDown": "ClickDetector.MouseClick:Connect(function(player)",
    "OnMouseEnter": "ClickDetector.MouseHoverEnter:Connect(function(player)",
    "OnMouseExit": "ClickDetector.MouseHoverLeave:Connect(function(player)",
    "OnGUI": "-- OnGUI: use ScreenGui with Frames/TextLabels",
    "OnApplicationQuit": "game:BindToClose(function()",
    "OnApplicationPause": "-- OnApplicationPause: no direct equivalent",
}


# ---------------------------------------------------------------------------
# SERVICE_IMPORTS: Roblox service import statements (18+ entries)
# ---------------------------------------------------------------------------

SERVICE_IMPORTS: dict[str, str] = {
    "RunService": 'local RunService = game:GetService("RunService")',
    "UserInputService": 'local UserInputService = game:GetService("UserInputService")',
    "TweenService": 'local TweenService = game:GetService("TweenService")',
    "CollectionService": 'local CollectionService = game:GetService("CollectionService")',
    "Players": 'local Players = game:GetService("Players")',
    "ReplicatedStorage": 'local ReplicatedStorage = game:GetService("ReplicatedStorage")',
    "ServerStorage": 'local ServerStorage = game:GetService("ServerStorage")',
    "DataStoreService": 'local DataStoreService = game:GetService("DataStoreService")',
    "TeleportService": 'local TeleportService = game:GetService("TeleportService")',
    "SoundService": 'local SoundService = game:GetService("SoundService")',
    "Workspace": 'local Workspace = game:GetService("Workspace")',
    "PathfindingService": 'local PathfindingService = game:GetService("PathfindingService")',
    "ContextActionService": 'local ContextActionService = game:GetService("ContextActionService")',
    "GuiService": 'local GuiService = game:GetService("GuiService")',
    "MarketplaceService": 'local MarketplaceService = game:GetService("MarketplaceService")',
    "PhysicsService": 'local PhysicsService = game:GetService("PhysicsService")',
    "HttpService": 'local HttpService = game:GetService("HttpService")',
    "TextService": 'local TextService = game:GetService("TextService")',
    "Debris": 'local Debris = game:GetService("Debris")',
    "ContentProvider": 'local ContentProvider = game:GetService("ContentProvider")',
}
