"""Generic auto-generated scripts injected by every conversion.

Scripts the converter considers regardless of game genre:

- ``GameServerManager`` (server) — spawn point handling + player init.
- ``CollisionGroupSetup`` (server) — Unity layer → Roblox CollisionGroup
  bridging, only emitted when at least one part carries a
  ``UnityLayer`` attribute.
- ``CollisionFidelityRecook`` (server) — re-cooks MeshPart collision via
  ``AssetService:CreateMeshPartAsync`` for parts whose
  ``_DesiredCollisionFidelity`` attribute is set, only emitted when
  the scene contains at least one such part.
- ``CameraRigFollower`` (client) — pivots the converted Unity main-camera
  Model onto ``workspace.CurrentCamera`` each frame, only emitted when
  the scene contains a part carrying the ``_MainCameraRig`` attribute.

Genre-specific scaffolding (FPS controller, HUD ScreenGui, etc.) lives
in :mod:`converter.scaffolding`; this module stays project-agnostic.
"""
from __future__ import annotations

import logging
import re

from core.roblox_types import RbxScript

log = logging.getLogger(__name__)


# Luau bare-identifier rule (ASCII only). Python's ``str.isidentifier``
# accepts PEP 3131 Unicode letters which Luau's lexer rejects, so
# ``_plan_to_luau`` must use this regex to decide bare-vs-bracketed keys.
_LUAU_BARE_IDENT_RE: re.Pattern[str] = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")

# Luau reserved keywords that can't be used as bare table keys even
# when they match the identifier regex.
_LUAU_RESERVED_KEYWORDS: frozenset[str] = frozenset({
    "and", "break", "do", "else", "elseif", "end",
    "false", "for", "function", "if", "in", "local",
    "nil", "not", "or", "repeat", "return", "then",
    "true", "until", "while", "continue",
})


# The GameServerManager source is assembled from a base body plus a
# conditional shared-flag funnel fragment. The base carries spawn
# handling, the ``PlayerShoot`` + ``PlayerGetItem`` RemoteEvents, and the
# shoot/pickup handlers — all UNCONDITIONAL. The funnel fragment (the
# ``PlayerSetSharedFlag`` RemoteEvent + its ``OnServerEvent`` listener) is
# spliced in only when ``include_shared_flag_funnel`` is True (the
# default). Phase 2b slice 3 gates that flag on the
# ``shared_flag_channels`` topology fact at the pipeline inject site.
#
# Byte-identity contract: ``_GAME_SERVER_HEAD + _SHARED_FLAG_FUNNEL_FRAGMENT
# + _GAME_SERVER_TAIL`` reproduces the pre-slice-3 monolithic source
# exactly (verified by ``test_autogen_shared_flag_gate``). The blank line
# separating ``PlayerGetItem`` from the next block lives at the END of
# ``_GAME_SERVER_HEAD`` so the funnel-omitted case still has a clean blank
# separator before the visual-hit-feedback section.

_GAME_SERVER_HEAD: str = '''\
-- Game Server Manager (auto-generated by Unity converter)
-- Handles spawn system, player initialization, and game state.

local Players = game:GetService("Players")
local RunService = game:GetService("RunService")

-- Find the best spawn point in workspace
-- Prefer the default/unnumbered spawn point (matches Unity's initial spawn)
local function findSpawnPoint()
    local firstSpawn = nil
    local defaultSpawn = nil

    for _, obj in ipairs(workspace:GetDescendants()) do
        local isSpawn = obj:IsA("SpawnLocation")
        if not isSpawn and obj:IsA("BasePart") then
            if obj:GetAttribute("IsSpawnPoint") or obj.Name:lower():find("spawn") then
                isSpawn = true
            end
        end
        if isSpawn then
            if not firstSpawn then
                firstSpawn = obj
            end
            -- Prefer named spawn points: "SpawnPoint" (default) or "SpawnPoint (1)" (backup)
            if obj.Name == "SpawnPoint" then
                defaultSpawn = obj
            elseif obj.Name == "SpawnPoint (1)" and not defaultSpawn then
                defaultSpawn = obj
            end
        end
    end

    local chosen = defaultSpawn or firstSpawn
    if chosen then
        return chosen.CFrame + Vector3.new(0, 3, 0)
    end
    return CFrame.new(0, 10, 0)
end

local spawnCFrame = findSpawnPoint()

-- Setup each player when they join
local function onPlayerAdded(player)
    player.CharacterAdded:Connect(function(character)
        -- Teleport to spawn point
        local hrp = character:WaitForChild("HumanoidRootPart", 5)
        if hrp then
            task.wait(0.1) -- Wait for character to load
            hrp.CFrame = spawnCFrame
        end

        -- Apply character properties from converter attributes
        local humanoid = character:FindFirstChildOfClass("Humanoid")
        if humanoid then
            -- Check for custom walk speed from NavMeshAgent or CharacterController
            for _, obj in ipairs(workspace:GetDescendants()) do
                if obj:IsA("BasePart") then
                    local walkSpeed = obj:GetAttribute("_WalkSpeed")
                    if walkSpeed and obj:GetAttribute("_HasCharacterController") then
                        humanoid.WalkSpeed = walkSpeed
                        local jumpHeight = obj:GetAttribute("_JumpHeight")
                        if jumpHeight then
                            humanoid.JumpHeight = jumpHeight
                        end
                        local slopeAngle = obj:GetAttribute("_MaxSlopeAngle")
                        if slopeAngle then
                            humanoid.MaxSlopeAngle = slopeAngle
                        end
                        local hipHeight = obj:GetAttribute("_HipHeight")
                        if hipHeight then
                            humanoid.HipHeight = hipHeight
                        end
                        -- Check for health data from converted MonoBehaviour
                        local maxHealth = obj:GetAttribute("MaxHealth") or obj:GetAttribute("maxHitPoints") or obj:GetAttribute("MaxHP")
                        if maxHealth and maxHealth > 0 then
                            humanoid.MaxHealth = maxHealth
                            humanoid.Health = maxHealth
                        end
                        break
                    end
                end
            end
        end
    end)
end

Players.PlayerAdded:Connect(onPlayerAdded)
-- Handle players already in game (Studio test mode)
for _, player in ipairs(Players:GetPlayers()) do
    task.spawn(onPlayerAdded, player)
end

-- Create RemoteEvents for FPS mechanics
local ReplicatedStorage = game:GetService("ReplicatedStorage")

local shootRemote = Instance.new("RemoteEvent")
shootRemote.Name = "PlayerShoot"
shootRemote.Parent = ReplicatedStorage

local getItemRemote = Instance.new("RemoteEvent")
getItemRemote.Name = "PlayerGetItem"
getItemRemote.Parent = ReplicatedStorage

'''


# The shared-flag funnel: the ``PlayerSetSharedFlag`` RemoteEvent plus its
# ``OnServerEvent`` listener (writes the attribute on Player + Character).
# Spliced into the GameServerManager source only when the topology
# ``shared_flag_channels.PlayerSetSharedFlag.present`` fact is True (or
# absent — fail-safe). Leads with the comment (no leading blank — the
# blank separator lives at the tail of ``_GAME_SERVER_HEAD``) and ends
# with a trailing blank so the visual-hit-feedback section keeps its
# separator whether or not this fragment is present.
_SHARED_FLAG_FUNNEL_FRAGMENT: str = '''\
-- Canonical shared-flag mirror. Client-side scripts (Player.luau) FireServer
-- this when they record a player flag (hasKey, hasRifle, ...). The server
-- sets the Attribute on BOTH the character Model and the Player Instance so
-- cross-domain readers (server-domain Door, etc.) see the change. Server-set
-- attributes replicate down to every client, so client-side reads still work.
local sharedFlagRemote = Instance.new("RemoteEvent")
sharedFlagRemote.Name = "PlayerSetSharedFlag"
sharedFlagRemote.Parent = ReplicatedStorage

sharedFlagRemote.OnServerEvent:Connect(function(player, flagName, value)
    if type(flagName) ~= "string" or flagName == "" then return end
    -- Whitelist: only "hasX" / "got*" style identifiers, no nested attribute
    -- chains and nothing past 64 chars to keep the surface small + sane.
    if #flagName > 64 or not string.match(flagName, "^[%w_]+$") then return end
    -- Booleans / numbers / strings only -- skip tables/instances/nil-clears.
    local t = type(value)
    if t ~= "boolean" and t ~= "number" and t ~= "string" then return end
    player:SetAttribute(flagName, value)
    local char = player.Character
    if char then char:SetAttribute(flagName, value) end
end)

'''


_GAME_SERVER_TAIL: str = '''\
-- Visual hit feedback
local function flashHitPart(part)
    local ok, orig = pcall(function() return part.Color end)
    if not ok then return end
    part.Color = Color3.new(1, 0.3, 0.3)
    task.wait(0.1)
    pcall(function() part.Color = orig end)
end

-- Handle shooting: client sends origin + direction, server does raycast + damage
local SHOOT_RANGE = 1000
local SHOOT_DAMAGE = 25

shootRemote.OnServerEvent:Connect(function(player, origin, direction)
    if typeof(origin) ~= "Vector3" or typeof(direction) ~= "Vector3" then return end
    -- Sanity: origin should be near the player
    local char = player.Character
    if not char then return end
    local head = char:FindFirstChild("Head")
    if head and (head.Position - origin).Magnitude > 20 then return end

    local rayParams = RaycastParams.new()
    rayParams.FilterType = Enum.RaycastFilterType.Exclude
    rayParams.FilterDescendantsInstances = {char}
    local result = workspace:Raycast(origin, direction.Unit * SHOOT_RANGE, rayParams)

    if result and result.Instance then
        -- Check if we hit a humanoid (NPC or player)
        local hitPart = result.Instance
        local hitModel = hitPart:FindFirstAncestorOfClass("Model")
        local hitHumanoid = hitModel and hitModel:FindFirstChildOfClass("Humanoid")
        if hitHumanoid then
            hitHumanoid:TakeDamage(SHOOT_DAMAGE)
        end
        task.spawn(flashHitPart, hitPart)
    end
end)

-- Handle item pickup: player touches a pickup part
getItemRemote.OnServerEvent:Connect(function(player, pickupPart)
    if typeof(pickupPart) ~= "Instance" or not pickupPart:IsA("BasePart") then return end
    if not pickupPart.Parent then return end
    -- Check distance
    local char = player.Character
    if not char then return end
    local hrp = char:FindFirstChild("HumanoidRootPart")
    if not hrp or (hrp.Position - pickupPart.Position).Magnitude > 20 then return end
    -- Apply pickup effect based on name
    local name = pickupPart.Name:lower()
    local humanoid = char:FindFirstChildOfClass("Humanoid")
    if humanoid then
        if name:find("health") or name:find("hp") or name:find("medkit") then
            humanoid.Health = math.min(humanoid.Health + 25, humanoid.MaxHealth)
        end
    end
    -- Remove pickup (it will respawn if ObjectResetter is active)
    pickupPart.Parent = nil
end)

-- Player teleport (paradigm C ``host.player:teleport(cf)``, NON-load-bearing,
-- D7): the client REQUESTS a mid-game teleport; the server OWNS the character
-- move. Declared + handled here in the tail (no shared-flag-funnel dependency,
-- unlike PlayerShoot/PlayerGetItem). If the AI never calls it the remote simply
-- never fires -- respawn (above) is unaffected (server-owned).
local teleportRemote = Instance.new("RemoteEvent")
teleportRemote.Name = "PlayerTeleport"
teleportRemote.Parent = ReplicatedStorage

-- The server applies the teleport ONLY to the REQUESTING player's own character
-- (``player`` is the authenticated sender) -- a client can never move another
-- player. Mirrors the server-owned spawn teleport (hrp.CFrame = ...).
teleportRemote.OnServerEvent:Connect(function(player, cf)
    if typeof(cf) ~= "CFrame" then return end
    local char = player.Character
    if not char then return end
    local hrp = char:FindFirstChild("HumanoidRootPart")
    if hrp then
        hrp.CFrame = cf
    end
end)

print("[GameServer] Initialized. Spawn point at", spawnCFrame.Position)
'''


def generate_game_server_script(
    *, include_shared_flag_funnel: bool = True,
) -> RbxScript:
    """Generate a server Script that handles basic game infrastructure.

    This script runs in ServerScriptService and handles:
    - Player respawn at spawn points
    - Loading custom character properties from converted data
    - Initial game state setup
    - The ``PlayerShoot`` + ``PlayerGetItem`` RemoteEvents (unconditional)

    ``include_shared_flag_funnel`` (default ``True``): when ``True`` the
    ``PlayerSetSharedFlag`` funnel RemoteEvent + its ``OnServerEvent``
    listener are spliced in (today's behavior, byte-identical). When
    ``False`` only that funnel block is omitted; spawn handling +
    ``PlayerShoot`` + ``PlayerGetItem`` stay. Phase 2b slice 3 drives this
    from the ``shared_flag_channels`` topology fact at the inject site;
    the default preserves today's behavior for callers that don't pass it.
    """
    funnel = (
        _SHARED_FLAG_FUNNEL_FRAGMENT if include_shared_flag_funnel else ""
    )
    source = _GAME_SERVER_HEAD + funnel + _GAME_SERVER_TAIL
    return RbxScript(
        name="GameServerManager",
        source=source,
        script_type="Script",
    )




def generate_collision_group_script() -> RbxScript:
    """Generate a server Script that creates CollisionGroups from Unity layer attributes.

    Unity's layer system maps to Roblox's CollisionGroup system.
    Parts with UnityLayer attributes get assigned to named collision groups.
    """
    source = '''\
-- CollisionGroup Setup (auto-generated from Unity layers)
-- Maps UnityLayer attributes on parts to Roblox CollisionGroups.

local PhysicsService = game:GetService("PhysicsService")

-- Standard Unity layer names (index -> name)
local LAYER_NAMES = {
    [0] = "Default",
    [1] = "TransparentFX",
    [2] = "IgnoreRaycast",
    [4] = "Water",
    [5] = "UI",
    [8] = "Terrain",
}

-- Create collision groups for layers found in the scene
local createdGroups = {}

local function ensureGroup(layerIdx)
    if createdGroups[layerIdx] then return createdGroups[layerIdx] end
    local name = LAYER_NAMES[layerIdx] or ("UnityLayer" .. tostring(layerIdx))
    pcall(function()
        PhysicsService:RegisterCollisionGroup(name)
    end)
    createdGroups[layerIdx] = name
    return name
end

-- Scan all parts and assign CollisionGroups based on UnityLayer
task.wait(1)

for _, part in workspace:GetDescendants() do
    if part:IsA("BasePart") then
        local layer = part:GetAttribute("UnityLayer")
        if layer and layer ~= 0 then
            local groupName = ensureGroup(layer)
            part.CollisionGroup = groupName
        end
    end
end

-- Common Unity collision exclusions:
-- Layer 2 (IgnoreRaycast) doesn't collide with anything
if createdGroups[2] then
    for _, group in createdGroups do
        pcall(function()
            PhysicsService:CollisionGroupSetCollidable(createdGroups[2], group, false)
        end)
    end
end

print("[CollisionGroups] Setup complete:", createdGroups)
'''
    return RbxScript(
        name="CollisionGroupSetup",
        source=source,
        script_type="Script",
    )




def generate_collision_fidelity_recook_script() -> RbxScript:
    """Generate a server Script that re-cooks MeshPart collision at game start.

    Roblox doesn't re-cook collision when ``CollisionFidelity`` is set
    via the property — only ``AssetService:CreateMeshPartAsync(meshId,
    {CollisionFidelity = …})`` actually generates a cooked physics
    asset. So a freshly-loaded place with non-Default fidelity in the
    rbxlx silently snaps every MeshPart's collision back to ``Box``,
    leaving invisible bounding-box blockers behind shapes that should
    have hollow geometry (door frames, archways, fences, etc.).

    The rbxlx writer marks each affected MeshPart with the attribute
    ``_DesiredCollisionFidelity = "<EnumName>"``. This script iterates
    every such part on game start, calls CreateMeshPartAsync with the
    right option dict, transfers properties + children + parent over,
    and destroys the old part. The result behaves like the live
    published place's chunked-builder cook (``luau_place_builder.py``)
    but for locally-loaded rbxlx files where that path doesn't run.

    Failures are logged and the original part is kept as-is; the script
    never raises and never crashes the place if a single mesh fails to
    cook.
    """
    source = '''\
-- CollisionFidelityRecook (auto-generated)
--
-- Roblox doesn't re-cook MeshPart collision when CollisionFidelity is
-- set via the property — only AssetService:CreateMeshPartAsync(meshId,
-- {CollisionFidelity = ...}) actually generates a cooked physics
-- asset. The rbxlx writer marks parts that need recooking with the
-- attribute ``_DesiredCollisionFidelity``; this script performs the
-- cook at game start so locally-loaded rbxlx files behave like the
-- live published place.

local AssetService = game:GetService("AssetService")

local function _propsFromOld(old)
    return {
        Name = old.Name,
        CFrame = old.CFrame,
        Size = old.Size,
        Anchored = old.Anchored,
        CanCollide = old.CanCollide,
        CanQuery = old.CanQuery,
        CanTouch = old.CanTouch,
        Massless = old.Massless,
        Transparency = old.Transparency,
        Reflectance = old.Reflectance,
        Material = old.Material,
        Color = old.Color,
        TextureID = old.TextureID,
    }
end

local function _recookOne(old)
    local meshId = old.MeshId
    if not meshId or meshId == "" then return false end
    local desired = old:GetAttribute("_DesiredCollisionFidelity")
    if not desired then return false end
    local fidEnum
    local ok = pcall(function()
        fidEnum = Enum.CollisionFidelity[desired]
    end)
    if not ok or not fidEnum then return false end

    local newOk, newPart = pcall(function()
        return AssetService:CreateMeshPartAsync(meshId, {
            CollisionFidelity = fidEnum,
        })
    end)
    if not newOk or not newPart then
        warn("[CollisionFidelityRecook] failed to cook " .. old:GetFullName()
            .. " — " .. tostring(newPart))
        return false
    end

    -- Transfer properties + children + parent.
    local props = _propsFromOld(old)
    for k, v in pairs(props) do
        pcall(function() (newPart :: any)[k] = v end)
    end
    -- Move children (SurfaceAppearance, Welds, Sounds, Scripts, etc.)
    -- before reparenting so the new part inherits the same hierarchy.
    for _, child in ipairs(old:GetChildren()) do
        child.Parent = newPart
    end
    newPart.Parent = old.Parent
    -- Strip the marker so re-runs don't double-cook.
    pcall(function() newPart:SetAttribute("_DesiredCollisionFidelity", nil) end)
    old:Destroy()
    return true
end

local cooked, failed = 0, 0
for _, m in ipairs(workspace:GetDescendants()) do
    if m:IsA("MeshPart") and m:GetAttribute("_DesiredCollisionFidelity") then
        if _recookOne(m) then
            cooked = cooked + 1
        else
            failed = failed + 1
        end
    end
end

if cooked > 0 or failed > 0 then
    print(("[CollisionFidelityRecook] cooked=%d failed=%d"):format(cooked, failed))
end
'''
    return RbxScript(
        name="CollisionFidelityRecook",
        source=source,
        script_type="Script",
    )


def generate_camera_rig_follower_script() -> RbxScript:
    """Generate a client LocalScript that makes the Unity main-camera
    rig track the live Roblox camera.

    Unity's main-camera GameObject and its children (weapon slots,
    viewmodels, HUD anchors) are converted into a static Model carrying
    the ``_MainCameraRig`` attribute (set by ``scene_converter``).
    Roblox's ``workspace.CurrentCamera`` is a separate live instance, so
    the converted Model otherwise just sits where the Unity scene
    authored it.

    This script pivots the rig Model onto the live camera every frame.
    ``Model:PivotTo`` propagates to every descendant BasePart, so each
    camera-child object — and anything parented under the rig at runtime
    (e.g. an equipped weapon) — rides the player's view exactly as the
    Unity transform hierarchy did. This is the generic replacement for
    bespoke per-weapon camera-follow code.
    """
    source = '''\
-- Camera Rig Follower (auto-generated by Unity converter)
-- Pivots the converted Unity main-camera Model onto the live Roblox
-- camera each frame, so its child objects (weapon slots, viewmodels)
-- ride the player's view as they did under the Unity transform tree.

local RunService = game:GetService("RunService")

local function findRig()
    for _, m in workspace:GetDescendants() do
        if m:IsA("Model") and m:GetAttribute("_MainCameraRig") then
            return m
        end
    end
    return nil
end

local rig = findRig()
if not rig then
    -- The rig Model may stream in slightly after this script runs.
    for _ = 1, 30 do
        task.wait(0.1)
        rig = findRig()
        if rig then break end
    end
end
if not rig then return end

RunService.RenderStepped:Connect(function()
    local cam = workspace.CurrentCamera
    if cam and rig and rig.Parent then
        rig:PivotTo(cam.CFrame)
    end
end)
'''
    return RbxScript(
        name="CameraRigFollower",
        source=source,
        script_type="LocalScript",
    )


# ---------------------------------------------------------------------------
# PR4: scene-runtime host entrypoints + plan ModuleScript
# ---------------------------------------------------------------------------

def _plan_to_luau(plan: dict) -> str:
    """Render the scene-runtime plan as a Luau-literal ``return {...}``.

    Encodes the strict subset of the planner artifact the host runtime
    actually reads (modules / scenes / prefabs / domain_overrides /
    displaced_instances). The encoder mirrors a JSON dump but emits
    Luau table syntax so the ModuleScript is parsable and the host
    can ``require`` it without going through JSONDecode.
    """
    def _encode(value: object, depth: int = 0) -> str:
        pad = "    " * (depth + 1)
        close_pad = "    " * depth
        if value is None:
            return "nil"
        if isinstance(value, bool):
            return "true" if value else "false"
        if isinstance(value, (int, float)):
            # Roblox Luau accepts standard numeric literals; bool was
            # already filtered above (bool is int subclass).
            return repr(value)
        if isinstance(value, str):
            # Escape per Lua long-string rules; falling back to short
            # string with explicit backslash escapes to keep the encoder
            # trivially predictable.
            escaped = (value.replace("\\", "\\\\")
                            .replace("\"", "\\\"")
                            .replace("\n", "\\n")
                            .replace("\r", "\\r"))
            return f"\"{escaped}\""
        if isinstance(value, list):
            if not value:
                return "{}"
            parts = [f"{pad}{_encode(v, depth + 1)}" for v in value]
            return "{\n" + ",\n".join(parts) + f",\n{close_pad}}}"
        if isinstance(value, dict):
            if not value:
                return "{}"
            parts = []
            for k, v in value.items():
                key_str = str(k)
                # Reserved Luau keywords + non-identifier keys need
                # bracket-syntax.
                #
                # R4-P2.2: Python's ``str.isidentifier()`` accepts
                # Unicode identifier characters per PEP 3131
                # (``"变量".isidentifier() == True``). Luau's lexer is
                # ASCII-only, so an unquoted Unicode key is a parse
                # error. Tighten to an explicit ASCII regex; anything
                # else gets bracket-quoted.
                if (_LUAU_BARE_IDENT_RE.match(key_str) is not None
                        and key_str not in _LUAU_RESERVED_KEYWORDS):
                    encoded_key = key_str
                else:
                    encoded_key = f"[{_encode(key_str)}]"
                parts.append(f"{pad}{encoded_key} = {_encode(v, depth + 1)}")
            return "{\n" + ",\n".join(parts) + f",\n{close_pad}}}"
        # Last-resort: stringify; never reached for planner artifacts.
        return _encode(str(value), depth)

    return _encode(plan, 0)


# Keys of the planner artifact relevant to the host runtime. Other keys
# (operator-only diagnostic surfaces like ``low_confidence_modules``) are
# intentionally elided from the embedded plan -- the host doesn't read
# them and they bloat the place's plan ModuleScript.
#
# ``scriptable_objects`` is the R2-P1.3 guid -> dotted-DataModel-path map
# the host's ScriptableObject ref resolver consults; populated by
# ``_subphase_inject_scene_runtime`` before this encoder runs.
_PLAN_KEYS_FOR_HOST: tuple[str, ...] = (
    "modules", "scenes", "prefabs", "domain_overrides",
    "scriptable_objects", "scene_prefab_placements",
    # Phase 1 (relation #8): the scale-faithful base gravity target (studs/s²),
    # stashed by ``plan_scene_runtime``. The client clone-site gravity hook reads
    # it off the embedded plan; without it here the filter would silently elide
    # the field and the client would fall back to a frozen 9.81.
    "gravityDesiredBaseStuds",
)


def generate_scene_runtime_plan_module(scene_runtime: dict) -> RbxScript:
    """Emit the per-place ``SceneRuntimePlan`` ModuleScript.

    The PR1 planner persists the full artifact in
    ``conversion_plan.json``. PR4 embeds the host-relevant subset into
    the place as a ReplicatedStorage ModuleScript so the host runtime
    can ``require`` it without filesystem access at game time.
    """
    plan_subset: dict = {
        k: scene_runtime.get(k, {} if k != "modules" else {})
        for k in _PLAN_KEYS_FOR_HOST
        if k in scene_runtime
    }
    body = _plan_to_luau(plan_subset)
    source = (
        "-- SceneRuntimePlan (auto-generated by Unity converter; PR4)\n"
        "-- Per-place plan consumed by SceneRuntimeClient/Server via\n"
        "-- runtime/scene_runtime.luau. Shape mirrors\n"
        "-- ``scene_runtime`` in conversion_plan.json (modules / scenes\n"
        "-- / prefabs / domain_overrides).\n"
        "return " + body + "\n"
    )
    return RbxScript(
        name="SceneRuntimePlan",
        source=source,
        script_type="ModuleScript",
        parent_path="ReplicatedStorage",
    )


# Production entrypoint sources. The host runtime module is shared; each
# entrypoint wires it to its side's Roblox services and the embedded
# plan, then calls ``engine:start(domainFilter)``.

_SCENE_RUNTIME_CLIENT_SOURCE: str = '''\
-- SceneRuntimeClient (auto-generated; PR4 scene-runtime host entrypoint).
-- Wires the generic host runtime (ReplicatedStorage.SceneRuntime) to
-- Roblox client-side services + the embedded plan, then drives the
-- ``client`` domain partition's lifecycle.

local RS = game:GetService("ReplicatedStorage")
local RunService = game:GetService("RunService")
local Players = game:GetService("Players")

-- Resolve the live ``PlayerGui`` for the local player so UI-bound
-- ``_SceneRuntimeId`` lookups hit the interactive UI tree (Players
-- clone StarterGui into PlayerGui at spawn; runtime components must
-- attach to the live clone, not the template).
local LocalPlayer = Players.LocalPlayer
local PlayerGui = LocalPlayer and LocalPlayer:WaitForChild("PlayerGui", 10)

local SceneRuntime = require(RS:WaitForChild("SceneRuntime"))
local Plan = require(RS:WaitForChild("SceneRuntimePlan"))

-- The host-owned player embodiment authority (paradigm C) reuses the camera
-- service's vetted pure pose math via injected helpers — it never requires
-- SceneCameraInput at the host's top-of-file (the host loads with no ``game``
-- global). SceneCameraInput is emitted UNCONDITIONALLY alongside SceneRuntime
-- (pipeline.py), so this require always resolves on the client.
local SceneCameraInput = require(RS:WaitForChild("SceneCameraInput"))
local UserInputService = game:GetService("UserInputService")

local function workspaceFind(sceneRuntimeId)
    -- Linear scan; production builds may cache as needed. Hosts are
    -- stamped on the logical GameObject only (PR2), so this is
    -- bounded by the runtime-bearing GameObject count.
    for _, inst in workspace:GetDescendants() do
        if inst:GetAttribute("_SceneRuntimeId") == sceneRuntimeId then
            return inst
        end
    end
    -- UI lives under PlayerGui at runtime (StarterGui is the template
    -- that gets cloned per-player). Fall back to StarterGui only when
    -- PlayerGui isn't available (edge case during early lifecycle).
    if PlayerGui then
        for _, gui in PlayerGui:GetDescendants() do
            if gui:GetAttribute("_SceneRuntimeId") == sceneRuntimeId then
                return gui
            end
        end
    else
        for _, gui in game:GetService("StarterGui"):GetDescendants() do
            if gui:GetAttribute("_SceneRuntimeId") == sceneRuntimeId then
                return gui
            end
        end
    end
    return nil
end

-- Event-driven resolve for a UI-owned host whose StarterGui->PlayerGui
-- clone may not have landed yet at boot. The synchronous ``workspaceFind``
-- above is one-shot (it must never yield -- the host build loop relies on
-- ``start()`` never yielding to preserve Awake-before-Start); this helper
-- is the YIELDING counterpart the host calls ONLY for UI-owned instances
-- that missed, from an already-spawned coroutine (never the main build
-- loop). It does an initial scan, then waits on ``PlayerGui.DescendantAdded``
-- for the matching ``_SceneRuntimeId`` rather than polling on a fixed
-- timer -- a timeout is fail-closed diagnostics (return nil; the host
-- ``warn``s the id), never a silent nil correctness assumption, because
-- PlayerGui can exist before the StarterGui copy lands (and
-- ``CharacterAutoLoads=false`` delays the copy until ``LoadCharacterAsync``).
local function awaitUiHost(sceneRuntimeId)
    if not PlayerGui then
        -- No live PlayerGui: nothing to wait on. Fall back to the one-shot
        -- scan (covers the StarterGui-template edge) and return its result.
        return workspaceFind(sceneRuntimeId)
    end
    local resolved = nil
    local done = false
    local thread = coroutine.running()
    local conn
    -- The DescendantAdded handler resumes the (yielded) waiter. ``done`` is a
    -- check-then-set within one cooperative coroutine (events dispatch only
    -- at resumption points, never between two synchronous statements here),
    -- so the guard is atomic -- no double-resolve / double-resume.
    local function onAdded(desc)
        if done then return end
        if desc:GetAttribute("_SceneRuntimeId") == sceneRuntimeId then
            resolved = desc
            done = true
            if conn then conn:Disconnect(); conn = nil end
            task.spawn(thread)
        end
    end
    -- CONNECT FIRST, then scan: connecting before the initial
    -- ``GetDescendants`` scan closes the scan-vs-connect race -- a clone that
    -- lands after the connect but before/during the scan still fires the
    -- event, so it can't fall into a gap that would force a false 10s timeout
    -- (codex r1 MAJOR #5). The handler is a no-op until we yield (its
    -- ``task.spawn(thread)`` resume only takes effect once ``thread`` is
    -- suspended), and the ``done`` guard prevents a double-resolve if the
    -- initial scan also finds it.
    conn = PlayerGui.DescendantAdded:Connect(onAdded)
    -- Initial scan: the clone may already be present by the time the host
    -- gets here (the build loop ran first). Resolve inline + return WITHOUT
    -- yielding -- the thread hasn't suspended, so it must not be resumed.
    -- Setting ``done`` neutralises any event the connect above latched.
    for _, gui in PlayerGui:GetDescendants() do
        if not done and gui:GetAttribute("_SceneRuntimeId") == sceneRuntimeId then
            done = true
            if conn then conn:Disconnect(); conn = nil end
            return gui
        end
    end
    -- Timeout guard: if the clone never lands, wake the waiter so the host
    -- can warn rather than hang forever. Fail-closed diagnostics, never a
    -- silent nil correctness assumption.
    task.delay(10, function()
        if done then return end
        done = true
        if conn then conn:Disconnect(); conn = nil end
        task.spawn(thread)
    end)
    coroutine.yield()
    return resolved
end

local function resolveModule(scriptId, modulePath)
    -- modulePath is the live DataModel path, dot-joined
    -- (``"ReplicatedStorage.Foo"`` /
    -- ``"StarterPlayer.StarterPlayerScripts.Bar"``). The planner stamps
    -- this in scene_runtime_domain._stamp_container_and_path; the host
    -- splits on "." and walks game:FindFirstChild(...) down the chain.
    if type(modulePath) ~= "string" or modulePath == "" then return nil end
    local parts = string.split(modulePath, ".")
    local node = game
    for _, part in ipairs(parts) do
        node = node:FindFirstChild(part)
        if not node then return nil end
    end
    if node:IsA("ModuleScript") then
        local ok, mod = pcall(require, node)
        if ok then return mod end
    end
    return nil
end

-- SceneRuntimePlan carries ``plan.prefabs[prefab_id].template_name``
-- (R2-P1.2 resolution): the bare template name prefab_packages emitted
-- under ReplicatedStorage.Templates. Look up via that map so the
-- stable prefab_id resolves to the right Templates entry even when
-- two prefabs share a bare name in different folders.
local function _resolveTemplate(prefabId)
    local prefab = (Plan.prefabs or {})[prefabId]
    local templateName = prefab and prefab.template_name
    if type(templateName) ~= "string" or templateName == "" then
        return nil
    end
    local templates = RS:FindFirstChild("Templates")
    if not templates then return nil end
    return templates:FindFirstChild(templateName)
end

local services = {
    task = task,
    warn = warn,
    -- Player-embodiment authority (paradigm C) — CLIENT ONLY. ``isClient``
    -- is the deterministic client/server discriminator the authority gates
    -- on (NOT a RunService presence sniff); ``userInputService`` + the two
    -- pure camera helpers reach the in-runtime authority via this table. The
    -- SERVER table stamps ``isClient = false`` and omits these.
    isClient = true,
    userInputService = UserInputService,
    cameraAdvance = SceneCameraInput._advance,
    cameraComposeLook = SceneCameraInput._composeLook,
    cameraYawOf = SceneCameraInput._yawOf,
    -- Client teleport-request remote (paradigm C ``host.player:teleport(cf)``,
    -- NON-load-bearing, D7) — CLIENT ONLY; the server never requests, so the
    -- server services table omits it. The GameServer creates this remote, so a
    -- bounded WaitForChild resolves it on the client.
    playerTeleportRemote = RS:WaitForChild("PlayerTeleport", 10),
    -- CFrame type-guard for the teleport request (the host injects this rather
    -- than calling the ``typeof`` builtin directly so the predicate is testable).
    isCFrame = function(v) return typeof(v) == "CFrame" end,
    resolveModule = resolveModule,
    workspaceFind = workspaceFind,
    awaitUiHost = awaitUiHost,
    findFirstChildWhichIsA = function(inst, class)
        -- ``GetComponent("Rigidbody")`` etc. should hit a built-in
        -- attached directly to the GameObject AS WELL as nested
        -- children. Roblox's ``FindFirstChildWhichIsA`` skips the
        -- instance itself, so a Part-rooted GameObject with
        -- ``GetComponent("BasePart")`` returned nil pre-R3.
        if not inst then return nil end
        if type(inst.IsA) == "function" and inst:IsA(class) then
            return inst
        end
        return inst:FindFirstChildWhichIsA(class)
    end,
    heartbeat = RunService.Heartbeat,
    fixedStep = 0.02,
    now = function() return os.clock() end,
    players = Players,
    getInstanceId = function(inst)
        return inst and inst:GetAttribute("_SceneRuntimeId")
    end,
    clonePrefabTemplate = function(prefabId, parent, cframe)
        local tpl = _resolveTemplate(prefabId)
        if not tpl then return nil end
        local clone = tpl:Clone()
        clone.Parent = parent or workspace
        if cframe and clone:IsA("Model") then
            clone:PivotTo(cframe)
        end
        return clone
    end,
    resolveCloneChild = function(clone, gameObjectId)
        -- Check the clone root first (its own SRI may match -- the
        -- per-placement upfront stamp also rewrites the root attribute),
        -- then descendants. Returns nil on miss so callers can fall back
        -- to a different lookup id without confusing "miss" with "the
        -- root IS the match" (the prior sentinel-clone behaviour).
        if clone:GetAttribute("_SceneRuntimeId") == gameObjectId then
            return clone
        end
        for _, d in clone:GetDescendants() do
            if d:GetAttribute("_SceneRuntimeId") == gameObjectId then
                return d
            end
        end
        return nil
    end,
    collectDescendantIds = function(inst)
        -- DFS post-order (children deepest-first, then self), per the
        -- design doc's recursive-teardown contract. Reversing
        -- ``GetDescendants`` (BFS) is NOT equivalent.
        local out = {}
        local function walk(node)
            for _, child in node:GetChildren() do
                walk(child)
            end
            local id = node:GetAttribute("_SceneRuntimeId")
            if id then table.insert(out, id) end
        end
        walk(inst)
        return out
    end,
    collectSubtreeIdsWithParents = function(inst)
        -- R4-P1.2: DFS preorder (root first, then children) with each
        -- entry carrying its parent id so the host's setActive cascade
        -- can recompute ``activeInHierarchy`` correctly. Returns a list
        -- of ``{id = "...", parentId = "..." | nil}`` records; entries
        -- whose Roblox Instance has no ``_SceneRuntimeId`` are dropped
        -- but the walk still descends through them (mirrors how the
        -- existing collectDescendantIds skips unstamped nodes).
        local out = {}
        local function walk(node, parentId)
            local id = node:GetAttribute("_SceneRuntimeId")
            if id then
                table.insert(out, {id = id, parentId = parentId})
            end
            local childParentId = id or parentId
            for _, child in node:GetChildren() do
                walk(child, childParentId)
            end
        end
        walk(inst, nil)
        return out
    end,
    destroyInstance = function(inst)
        if inst and inst.Destroy then inst:Destroy() end
    end,
}

local engine = SceneRuntime.new(services, Plan)
engine:start("client")
'''


_SCENE_RUNTIME_SERVER_SOURCE: str = '''\
-- SceneRuntimeServer (auto-generated; PR4 scene-runtime host entrypoint).
-- Mirrors SceneRuntimeClient but drives the ``server`` domain partition.

local RS = game:GetService("ReplicatedStorage")
local RunService = game:GetService("RunService")
local Players = game:GetService("Players")

local SceneRuntime = require(RS:WaitForChild("SceneRuntime"))
local Plan = require(RS:WaitForChild("SceneRuntimePlan"))

local function workspaceFind(sceneRuntimeId)
    for _, inst in workspace:GetDescendants() do
        if inst:GetAttribute("_SceneRuntimeId") == sceneRuntimeId then
            return inst
        end
    end
    return nil
end

local function resolveModule(scriptId, modulePath)
    -- modulePath is the live DataModel path, dot-joined
    -- (``"ReplicatedStorage.Foo"`` /
    -- ``"ServerScriptService.Bar"``). Matches client entrypoint.
    if type(modulePath) ~= "string" or modulePath == "" then return nil end
    local parts = string.split(modulePath, ".")
    local node = game
    for _, part in ipairs(parts) do
        node = node:FindFirstChild(part)
        if not node then return nil end
    end
    if node:IsA("ModuleScript") then
        local ok, mod = pcall(require, node)
        if ok then return mod end
    end
    return nil
end

-- See SceneRuntimeClient for the rationale: prefab templates live
-- under ReplicatedStorage.Templates keyed by bare prefab name; the
-- plan's ``template_name`` field bridges the stable prefab_id.
local function _resolveTemplate(prefabId)
    local prefab = (Plan.prefabs or {})[prefabId]
    local templateName = prefab and prefab.template_name
    if type(templateName) ~= "string" or templateName == "" then
        return nil
    end
    local templates = RS:FindFirstChild("Templates")
    if not templates then return nil end
    return templates:FindFirstChild(templateName)
end

local services = {
    task = task,
    warn = warn,
    -- The server NEVER builds/drives the player-embodiment authority: the
    -- explicit ``isClient = false`` flag makes ``_initPlayerAuthority`` leave
    -- ``self._player = nil`` so the ``_tick`` brackets no-op. No UIS / camera
    -- helpers are injected here (the client table carries them).
    isClient = false,
    resolveModule = resolveModule,
    workspaceFind = workspaceFind,
    findFirstChildWhichIsA = function(inst, class)
        -- ``GetComponent("Rigidbody")`` etc. should hit a built-in
        -- attached directly to the GameObject AS WELL as nested
        -- children. Roblox's ``FindFirstChildWhichIsA`` skips the
        -- instance itself, so a Part-rooted GameObject with
        -- ``GetComponent("BasePart")`` returned nil pre-R3.
        if not inst then return nil end
        if type(inst.IsA) == "function" and inst:IsA(class) then
            return inst
        end
        return inst:FindFirstChildWhichIsA(class)
    end,
    heartbeat = RunService.Heartbeat,
    fixedStep = 0.02,
    now = function() return os.clock() end,
    players = Players,
    getInstanceId = function(inst)
        return inst and inst:GetAttribute("_SceneRuntimeId")
    end,
    clonePrefabTemplate = function(prefabId, parent, cframe)
        local tpl = _resolveTemplate(prefabId)
        if not tpl then return nil end
        local clone = tpl:Clone()
        clone.Parent = parent or workspace
        if cframe and clone:IsA("Model") then
            clone:PivotTo(cframe)
        end
        return clone
    end,
    resolveCloneChild = function(clone, gameObjectId)
        -- Check the clone root first (its own SRI may match -- the
        -- per-placement upfront stamp also rewrites the root attribute),
        -- then descendants. Returns nil on miss so callers can fall back
        -- to a different lookup id without confusing "miss" with "the
        -- root IS the match" (the prior sentinel-clone behaviour).
        if clone:GetAttribute("_SceneRuntimeId") == gameObjectId then
            return clone
        end
        for _, d in clone:GetDescendants() do
            if d:GetAttribute("_SceneRuntimeId") == gameObjectId then
                return d
            end
        end
        return nil
    end,
    collectDescendantIds = function(inst)
        -- DFS post-order (children deepest-first, then self), per the
        -- design doc's recursive-teardown contract. Reversing
        -- ``GetDescendants`` (BFS) is NOT equivalent.
        local out = {}
        local function walk(node)
            for _, child in node:GetChildren() do
                walk(child)
            end
            local id = node:GetAttribute("_SceneRuntimeId")
            if id then table.insert(out, id) end
        end
        walk(inst)
        return out
    end,
    collectSubtreeIdsWithParents = function(inst)
        -- R4-P1.2: DFS preorder (root first, then children) with each
        -- entry carrying its parent id so the host's setActive cascade
        -- can recompute ``activeInHierarchy`` correctly. Returns a list
        -- of ``{id = "...", parentId = "..." | nil}`` records; entries
        -- whose Roblox Instance has no ``_SceneRuntimeId`` are dropped
        -- but the walk still descends through them (mirrors how the
        -- existing collectDescendantIds skips unstamped nodes).
        local out = {}
        local function walk(node, parentId)
            local id = node:GetAttribute("_SceneRuntimeId")
            if id then
                table.insert(out, {id = id, parentId = parentId})
            end
            local childParentId = id or parentId
            for _, child in node:GetChildren() do
                walk(child, childParentId)
            end
        end
        walk(inst, nil)
        return out
    end,
    destroyInstance = function(inst)
        if inst and inst.Destroy then inst:Destroy() end
    end,
}

local engine = SceneRuntime.new(services, Plan)
engine:start("server")
'''


def generate_scene_runtime_client_entrypoint() -> RbxScript:
    """LocalScript that boots the host runtime's client partition."""
    return RbxScript(
        name="SceneRuntimeClient",
        source=_SCENE_RUNTIME_CLIENT_SOURCE,
        script_type="LocalScript",
        parent_path="StarterPlayer.StarterPlayerScripts",
    )


def generate_scene_runtime_server_entrypoint() -> RbxScript:
    """Server Script that boots the host runtime's server partition."""
    return RbxScript(
        name="SceneRuntimeServer",
        source=_SCENE_RUNTIME_SERVER_SOURCE,
        script_type="Script",
        parent_path="ServerScriptService",
    )


# ---------------------------------------------------------------------------
# Phase 1 (relation #8) -- scale-faithful per-assembly gravity correction.
#
# The converter scales geometry by STUDS_PER_METER but a converted dynamic body
# free-falls under Roblox's default workspace.Gravity (196.2 studs/s²) -- NOT the
# scale-faithful target |unity_g.y| * STUDS_PER_METER (≈35.03 at the 9.81 default).
# We correct each UNANCHORED 3D-Rigidbody assembly with one compensating
# VectorForce sized on AssemblyMass so the NET vertical accel matches the target
# (mass-independent because the force is mass-proportional).
#
# ``_GRAVITY_CORRECTION_HELPER_LUAU`` is the CANONICAL ``correctDynamicAssembly``
# text. It is baked into the standalone server script below AND mirrored into
# ``runtime/scene_runtime.luau`` (slice 1.3) for the client clone-site hook; a
# parity test (slice 1.4) pins the two emission sites identical.
#
# Force formula (the load-bearing contract):
#   force_Y = AssemblyMass * (g_live - desiredBaseStuds * gravityScale)
#     where g_live = workspace.Gravity, gravityScale = 0 if UseGravity==false
#     else 1.0 (in-scope 3D bodies have no GravityScale -- that is a 2D-only
#     fact, excluded with Rigidbody2D). Net accel = desiredBaseStuds*gravityScale.
_GRAVITY_CORRECTION_HELPER_LUAU: str = '''\
local function _isBasePart(inst)
    return (type(inst) == "table" or type(inst) == "userdata")
        and inst:IsA("BasePart")
end

-- factOf: read attribute ``key`` off the carrier FIRST; only if ABSENT on the
-- carrier, walk ancestor Models for the first holder (D-P1.6 root-first, then
-- ancestor-Model walk). Covers S1/S5 (facts on the carrier) and S2 mesh-wrap
-- (UseGravity stayed on the OUTER Model while only _UnityMass moved to the
-- inner *_Mesh carrier). The fallback is gated PER-ATTRIBUTE on "absent on the
-- carrier", NOT on an owning-Model lookup being nil -- so a factless parent
-- container (S5) is never consulted before the carrier.
local function factOf(carrier, key)
    local v = carrier:GetAttribute(key)
    if v ~= nil then
        return v
    end
    local owner = carrier:FindFirstAncestorWhichIsA("Model")
    while owner do
        local ov = owner:GetAttribute(key)
        if ov ~= nil then
            return ov
        end
        owner = owner:FindFirstAncestorWhichIsA("Model")
    end
    return nil
end

-- correctDynamicAssembly(carrier, desiredBaseStuds)
-- ``carrier`` is the instance the scan found carrying _UnityMass: a BasePart
-- (S1/S2/S4/S5) OR a Model carrier (S3/S6). Resolves a representative BasePart,
-- then its AssemblyRootPart, applies one compensating VectorForce, and tags the
-- root. Idempotent via the _ScaleGravityCorrected tag on the resolved root.
local function correctDynamicAssembly(carrier, desiredBaseStuds)
    if type(carrier) ~= "table" and type(carrier) ~= "userdata" then
        return
    end
    -- 0. resolve a representative BasePart from the carrier.
    local representativePart
    if _isBasePart(carrier) then
        representativePart = carrier
    elseif carrier:IsA("Model") then
        -- Model carrier (S3 no-mesh-parent / S6 multi-sub-mesh): PrimaryPart,
        -- else the first descendant BasePart. In TODAY's converter output these
        -- descendants are Anchored (no own Rigidbody) so step 2 skips them.
        representativePart = carrier.PrimaryPart
            or carrier:FindFirstChildWhichIsA("BasePart", true)
        if representativePart == nil then
            -- No BasePart to resolve. Defensive one-shot skip WITHOUT tagging --
            -- the body stays correctable if it later becomes resolvable. (A
            -- Clone() yields a fully-materialized subtree before parenting, so
            -- this is not a deferral mechanism.)
            return
        end
    else
        return
    end
    if not _isBasePart(representativePart) then
        return
    end
    -- 1. resolve the assembly root (mirrors applyImpulse 1518-1532, but off the
    --    representativePart since a Model carrier has no .AssemblyRootPart).
    local root = representativePart.AssemblyRootPart or representativePart
    -- 2. SKIP rules (each a no-op return BEFORE any VectorForce creation).
    if root:GetAttribute(TAG) ~= nil then
        return  -- already corrected (dedup across all surfaces)
    end
    if root.Anchored then
        return  -- static geometry (also skips Model-carrier shapes S3/S6)
    end
    -- Humanoid / character rig: a Humanoid is never a BasePart ancestor, so use
    -- the ancestor-Model-contains-Humanoid form (NOT FindFirstAncestorWhichIsA
    -- ("Humanoid"), which is dead).
    local ancestorModel = root:FindFirstAncestorWhichIsA("Model")
    while ancestorModel do
        if ancestorModel:FindFirstChildWhichIsA("Humanoid") then
            return  -- character assembly -- leave on native gravity
        end
        ancestorModel = ancestorModel:FindFirstAncestorWhichIsA("Model")
    end
    local mass = root.AssemblyMass
    if mass <= 0 then
        return  -- SKIP WITHOUT TAGGING -- stays correctable if mass later valid
    end
    -- 3. read scale/skip facts CARRIER-FIRST then ancestor-Model walk (D-P1.6).
    local useGravityAttr = factOf(carrier, "UseGravity")
    -- GravityScale is a 2D-only fact (Rigidbody2D branch); DEAD for in-scope 3D
    -- (always nil ⇒ 1.0). Kept defensively / self-documenting.
    local gravityScaleAttr = factOf(carrier, "GravityScale")
    local gravityScale = (useGravityAttr == false) and 0 or (gravityScaleAttr or 1.0)
    local desiredStuds = desiredBaseStuds * gravityScale
    -- 4. compensating force: net accel = g_live - force/mass = desiredStuds.
    local force = mass * (workspace.Gravity - desiredStuds)
    -- 5. one Attachment + VectorForce on the root (ApplyAtCenterOfMass, World).
    local att = Instance.new("Attachment")
    att.Parent = root
    local vf = Instance.new("VectorForce")
    vf.Attachment0 = att
    vf.Force = Vector3.new(0, force, 0)
    vf.RelativeTo = Enum.ActuatorRelativeTo.World
    vf.ApplyAtCenterOfMass = true
    vf.Parent = root
    -- 6. tag the resolved root (dedup keyed on the physical assembly).
    root:SetAttribute(TAG, true)
end
'''


def generate_gravity_correction_server_script(desired_g_studs_base: float) -> str:
    """Bake the standalone scale-faithful-gravity SERVER script source.

    Returns the Luau text for the ``SceneGravityCorrection`` Script
    (ServerScriptService). It bakes ``desired_g_studs_base`` (=
    ``|unity_g.y| * STUDS_PER_METER``) as a literal constant, embeds the
    canonical ``correctDynamicAssembly`` helper, and drives it from two
    tag-idempotent surfaces:

      1. a boot ``workspace:GetDescendants()`` sweep (welds/joints settled
         ⇒ ``AssemblyRootPart``/``AssemblyMass`` are final), and
      2. a ``workspace.DescendantAdded`` spawn hook (runtime-cloned dynamics;
         deferred a frame so a multi-part clone's welds settle).

    Both surfaces select CLASS-AGNOSTICALLY on ``_UnityMass`` presence
    (BasePart OR Model carrier) and SKIP ``_Rigidbody2D`` carriers (Physics2D
    OOS -- a 2D body carries ``_UnityMass`` indistinguishably from a 3D one).
    """
    source = (
        "-- SceneGravityCorrection (auto-generated; relation #8 scale-faithful gravity).\n"
        "-- One compensating VectorForce per UNANCHORED 3D-Rigidbody assembly so a\n"
        "-- converted dynamic body free-falls at the scale-faithful target accel\n"
        "-- (|unity_g.y| * STUDS_PER_METER) instead of Roblox's default 196.2.\n"
        "\n"
        "local DESIRED_G_STUDS_BASE = " + repr(float(desired_g_studs_base))
        + "   -- |unity_g.y| * STUDS_PER_METER\n"
        "local TAG = \"_ScaleGravityCorrected\"\n"
        "\n"
        + _GRAVITY_CORRECTION_HELPER_LUAU
        + "\n"
        "-- Surface 1: boot sweep. Welds/joints have settled, so AssemblyRootPart /\n"
        "-- AssemblyMass are final. CLASS-AGNOSTIC scan: select on _UnityMass presence\n"
        "-- regardless of class (BasePart S1/S2/S4 OR Model carrier S3/S6). A Model\n"
        "-- carrier resolves an Anchored representative part and is SKIPPED via\n"
        "-- skip-if-anchored (correct: that body is static). 2D EXCLUSION: a Rigidbody2D\n"
        "-- body also carries _UnityMass (stamped before the 2D/3D split) so it is flagged\n"
        "-- _Rigidbody2D=True and SKIPPED here (a 3D correction must not touch a 2D body).\n"
        "for _, d in workspace:GetDescendants() do\n"
        "    if d:GetAttribute(\"_UnityMass\") ~= nil and d:GetAttribute(\"_Rigidbody2D\") == nil then\n"
        "        correctDynamicAssembly(d, DESIRED_G_STUDS_BASE)\n"
        "    end\n"
        "end\n"
        "\n"
        "-- Surface 2: server spawn hook (runtime-cloned dynamics). task.defer lets a\n"
        "-- multi-part clone's welds settle before AssemblyMass is read; the tag makes\n"
        "-- later-arriving sibling parts no-op.\n"
        "workspace.DescendantAdded:Connect(function(d)\n"
        "    if d:GetAttribute(\"_UnityMass\") ~= nil and d:GetAttribute(\"_Rigidbody2D\") == nil then\n"
        "        task.defer(function() correctDynamicAssembly(d, DESIRED_G_STUDS_BASE) end)\n"
        "    end\n"
        "end)\n"
    )
    return source


def render_cross_domain_report(edges: list) -> str:
    """Render the conversion-time cross-domain edge report.

    ``edges`` is a list of dicts shaped like
    ``{"from_script": ..., "to_script": ..., "field": ...,
       "from_domain": ..., "to_domain": ...}``.

    The host runtime injects ``nil`` for these refs at start (v1
    cross-domain policy); this report lets operators see the boundary
    before runtime. Output is plaintext suitable for appending to
    ``UNCONVERTED.md``.
    """
    if not edges:
        return ""
    lines = [
        "## Cross-domain references (scene-runtime v1)",
        "",
        ("The host runtime injects ``nil`` for these serialized references "
         "and logs a warning at start. Brokering (RemoteEvent/attribute-mirror "
         "stubs) is deferred per the design doc."),
        "",
        f"Total edges: {len(edges)}",
        "",
        "| From class | Domain | Field | -> | To class | Domain |",
        "|---|---|---|---|---|---|",
    ]
    for e in edges:
        lines.append(
            f"| {e.get('from_script','?')} | {e.get('from_domain','?')} | "
            f"{e.get('field','?')} | -> | {e.get('to_script','?')} | "
            f"{e.get('to_domain','?')} |"
        )
    return "\n".join(lines) + "\n"

