"""Generic auto-generated scripts injected by every conversion.

Three scripts the converter ALWAYS considers regardless of game genre:

- ``GameServerManager`` (server) — spawn point handling + player init.
- ``CollisionGroupSetup`` (server) — Unity layer → Roblox CollisionGroup
  bridging, only emitted when at least one part carries a
  ``UnityLayer`` attribute.
- ``CollisionFidelityRecook`` (server) — re-cooks MeshPart collision via
  ``AssetService:CreateMeshPartAsync`` for parts whose
  ``_DesiredCollisionFidelity`` attribute is set, only emitted when
  the scene contains at least one such part.

Genre-specific scaffolding (FPS controller, HUD ScreenGui, etc.) lives
in :mod:`converter.scaffolding`; this module stays project-agnostic.
"""
from __future__ import annotations

import logging
from core.roblox_types import RbxScript

log = logging.getLogger(__name__)


def generate_game_server_script() -> RbxScript:
    """Generate a server Script that handles basic game infrastructure.

    This script runs in ServerScriptService and handles:
    - Player respawn at spawn points
    - Loading custom character properties from converted data
    - Initial game state setup
    """
    source = '''\
-- Game Server Manager (auto-generated by Unity converter)
-- Handles spawn system, player initialization, and game state.

local Players = game:GetService("Players")
local RunService = game:GetService("RunService")

-- Find the best spawn point in workspace
-- Prefer the default/unnumbered spawn point (matches Unity's initial spawn)
local function findSpawnPoint()
    local firstSpawn = nil
    local defaultSpawn = nil

    for _, obj in ipairs(workspace:GetDescendants()) do
        local isSpawn = obj:IsA("SpawnLocation")
        if not isSpawn and obj:IsA("BasePart") then
            if obj:GetAttribute("IsSpawnPoint") or obj.Name:lower():find("spawn") then
                isSpawn = true
            end
        end
        if isSpawn then
            if not firstSpawn then
                firstSpawn = obj
            end
            -- Prefer named spawn points: "SpawnPoint" (default) or "SpawnPoint (1)" (backup)
            if obj.Name == "SpawnPoint" then
                defaultSpawn = obj
            elseif obj.Name == "SpawnPoint (1)" and not defaultSpawn then
                defaultSpawn = obj
            end
        end
    end

    local chosen = defaultSpawn or firstSpawn
    if chosen then
        return chosen.CFrame + Vector3.new(0, 3, 0)
    end
    return CFrame.new(0, 10, 0)
end

local spawnCFrame = findSpawnPoint()

-- Setup each player when they join
local function onPlayerAdded(player)
    player.CharacterAdded:Connect(function(character)
        -- Teleport to spawn point
        local hrp = character:WaitForChild("HumanoidRootPart", 5)
        if hrp then
            task.wait(0.1) -- Wait for character to load
            hrp.CFrame = spawnCFrame
        end

        -- Apply character properties from converter attributes
        local humanoid = character:FindFirstChildOfClass("Humanoid")
        if humanoid then
            -- Check for custom walk speed from NavMeshAgent or CharacterController
            for _, obj in ipairs(workspace:GetDescendants()) do
                if obj:IsA("BasePart") then
                    local walkSpeed = obj:GetAttribute("_WalkSpeed")
                    if walkSpeed and obj:GetAttribute("_HasCharacterController") then
                        humanoid.WalkSpeed = walkSpeed
                        local jumpHeight = obj:GetAttribute("_JumpHeight")
                        if jumpHeight then
                            humanoid.JumpHeight = jumpHeight
                        end
                        local slopeAngle = obj:GetAttribute("_MaxSlopeAngle")
                        if slopeAngle then
                            humanoid.MaxSlopeAngle = slopeAngle
                        end
                        local hipHeight = obj:GetAttribute("_HipHeight")
                        if hipHeight then
                            humanoid.HipHeight = hipHeight
                        end
                        -- Check for health data from converted MonoBehaviour
                        local maxHealth = obj:GetAttribute("MaxHealth") or obj:GetAttribute("maxHitPoints") or obj:GetAttribute("MaxHP")
                        if maxHealth and maxHealth > 0 then
                            humanoid.MaxHealth = maxHealth
                            humanoid.Health = maxHealth
                        end
                        break
                    end
                end
            end
        end
    end)
end

Players.PlayerAdded:Connect(onPlayerAdded)
-- Handle players already in game (Studio test mode)
for _, player in ipairs(Players:GetPlayers()) do
    task.spawn(onPlayerAdded, player)
end

-- Create RemoteEvents for FPS mechanics
local ReplicatedStorage = game:GetService("ReplicatedStorage")

local shootRemote = Instance.new("RemoteEvent")
shootRemote.Name = "PlayerShoot"
shootRemote.Parent = ReplicatedStorage

local getItemRemote = Instance.new("RemoteEvent")
getItemRemote.Name = "PlayerGetItem"
getItemRemote.Parent = ReplicatedStorage

-- Visual hit feedback
local function flashHitPart(part)
    local ok, orig = pcall(function() return part.Color end)
    if not ok then return end
    part.Color = Color3.new(1, 0.3, 0.3)
    task.wait(0.1)
    pcall(function() part.Color = orig end)
end

-- Handle shooting: client sends origin + direction, server does raycast + damage
local SHOOT_RANGE = 1000
local SHOOT_DAMAGE = 25

shootRemote.OnServerEvent:Connect(function(player, origin, direction)
    if typeof(origin) ~= "Vector3" or typeof(direction) ~= "Vector3" then return end
    -- Sanity: origin should be near the player
    local char = player.Character
    if not char then return end
    local head = char:FindFirstChild("Head")
    if head and (head.Position - origin).Magnitude > 20 then return end

    local rayParams = RaycastParams.new()
    rayParams.FilterType = Enum.RaycastFilterType.Exclude
    rayParams.FilterDescendantsInstances = {char}
    local result = workspace:Raycast(origin, direction.Unit * SHOOT_RANGE, rayParams)

    if result and result.Instance then
        -- Check if we hit a humanoid (NPC or player)
        local hitPart = result.Instance
        local hitModel = hitPart:FindFirstAncestorOfClass("Model")
        local hitHumanoid = hitModel and hitModel:FindFirstChildOfClass("Humanoid")
        if hitHumanoid then
            hitHumanoid:TakeDamage(SHOOT_DAMAGE)
        end
        task.spawn(flashHitPart, hitPart)
    end
end)

-- Handle item pickup: player touches a pickup part
getItemRemote.OnServerEvent:Connect(function(player, pickupPart)
    if typeof(pickupPart) ~= "Instance" or not pickupPart:IsA("BasePart") then return end
    if not pickupPart.Parent then return end
    -- Check distance
    local char = player.Character
    if not char then return end
    local hrp = char:FindFirstChild("HumanoidRootPart")
    if not hrp or (hrp.Position - pickupPart.Position).Magnitude > 20 then return end
    -- Apply pickup effect based on name
    local name = pickupPart.Name:lower()
    local humanoid = char:FindFirstChildOfClass("Humanoid")
    if humanoid then
        if name:find("health") or name:find("hp") or name:find("medkit") then
            humanoid.Health = math.min(humanoid.Health + 25, humanoid.MaxHealth)
        end
    end
    -- Remove pickup (it will respawn if ObjectResetter is active)
    pickupPart.Parent = nil
end)

print("[GameServer] Initialized. Spawn point at", spawnCFrame.Position)
'''
    return RbxScript(
        name="GameServerManager",
        source=source,
        script_type="Script",
    )




def generate_collision_group_script() -> RbxScript:
    """Generate a server Script that creates CollisionGroups from Unity layer attributes.

    Unity's layer system maps to Roblox's CollisionGroup system.
    Parts with UnityLayer attributes get assigned to named collision groups.
    """
    source = '''\
-- CollisionGroup Setup (auto-generated from Unity layers)
-- Maps UnityLayer attributes on parts to Roblox CollisionGroups.

local PhysicsService = game:GetService("PhysicsService")

-- Standard Unity layer names (index -> name)
local LAYER_NAMES = {
    [0] = "Default",
    [1] = "TransparentFX",
    [2] = "IgnoreRaycast",
    [4] = "Water",
    [5] = "UI",
    [8] = "Terrain",
}

-- Create collision groups for layers found in the scene
local createdGroups = {}

local function ensureGroup(layerIdx)
    if createdGroups[layerIdx] then return createdGroups[layerIdx] end
    local name = LAYER_NAMES[layerIdx] or ("UnityLayer" .. tostring(layerIdx))
    pcall(function()
        PhysicsService:RegisterCollisionGroup(name)
    end)
    createdGroups[layerIdx] = name
    return name
end

-- Scan all parts and assign CollisionGroups based on UnityLayer
task.wait(1)

for _, part in workspace:GetDescendants() do
    if part:IsA("BasePart") then
        local layer = part:GetAttribute("UnityLayer")
        if layer and layer ~= 0 then
            local groupName = ensureGroup(layer)
            part.CollisionGroup = groupName
        end
    end
end

-- Common Unity collision exclusions:
-- Layer 2 (IgnoreRaycast) doesn't collide with anything
if createdGroups[2] then
    for _, group in createdGroups do
        pcall(function()
            PhysicsService:CollisionGroupSetCollidable(createdGroups[2], group, false)
        end)
    end
end

print("[CollisionGroups] Setup complete:", createdGroups)
'''
    return RbxScript(
        name="CollisionGroupSetup",
        source=source,
        script_type="Script",
    )




def generate_collision_fidelity_recook_script() -> RbxScript:
    """Generate a server Script that re-cooks MeshPart collision at game start.

    Roblox doesn't re-cook collision when ``CollisionFidelity`` is set
    via the property — only ``AssetService:CreateMeshPartAsync(meshId,
    {CollisionFidelity = …})`` actually generates a cooked physics
    asset. So a freshly-loaded place with non-Default fidelity in the
    rbxlx silently snaps every MeshPart's collision back to ``Box``,
    leaving invisible bounding-box blockers behind shapes that should
    have hollow geometry (door frames, archways, fences, etc.).

    The rbxlx writer marks each affected MeshPart with the attribute
    ``_DesiredCollisionFidelity = "<EnumName>"``. This script iterates
    every such part on game start, calls CreateMeshPartAsync with the
    right option dict, transfers properties + children + parent over,
    and destroys the old part. The result behaves like the live
    published place's chunked-builder cook (``luau_place_builder.py``)
    but for locally-loaded rbxlx files where that path doesn't run.

    Failures are logged and the original part is kept as-is; the script
    never raises and never crashes the place if a single mesh fails to
    cook.
    """
    source = '''\
-- CollisionFidelityRecook (auto-generated)
--
-- Roblox doesn't re-cook MeshPart collision when CollisionFidelity is
-- set via the property — only AssetService:CreateMeshPartAsync(meshId,
-- {CollisionFidelity = ...}) actually generates a cooked physics
-- asset. The rbxlx writer marks parts that need recooking with the
-- attribute ``_DesiredCollisionFidelity``; this script performs the
-- cook at game start so locally-loaded rbxlx files behave like the
-- live published place.

local AssetService = game:GetService("AssetService")

local function _propsFromOld(old)
    return {
        Name = old.Name,
        CFrame = old.CFrame,
        Size = old.Size,
        Anchored = old.Anchored,
        CanCollide = old.CanCollide,
        CanQuery = old.CanQuery,
        CanTouch = old.CanTouch,
        Massless = old.Massless,
        Transparency = old.Transparency,
        Reflectance = old.Reflectance,
        Material = old.Material,
        Color = old.Color,
        TextureID = old.TextureID,
    }
end

local function _recookOne(old)
    local meshId = old.MeshId
    if not meshId or meshId == "" then return false end
    local desired = old:GetAttribute("_DesiredCollisionFidelity")
    if not desired then return false end
    local fidEnum
    local ok = pcall(function()
        fidEnum = Enum.CollisionFidelity[desired]
    end)
    if not ok or not fidEnum then return false end

    local newOk, newPart = pcall(function()
        return AssetService:CreateMeshPartAsync(meshId, {
            CollisionFidelity = fidEnum,
        })
    end)
    if not newOk or not newPart then
        warn("[CollisionFidelityRecook] failed to cook " .. old:GetFullName()
            .. " — " .. tostring(newPart))
        return false
    end

    -- Transfer properties + children + parent.
    local props = _propsFromOld(old)
    for k, v in pairs(props) do
        pcall(function() (newPart :: any)[k] = v end)
    end
    -- Move children (SurfaceAppearance, Welds, Sounds, Scripts, etc.)
    -- before reparenting so the new part inherits the same hierarchy.
    for _, child in ipairs(old:GetChildren()) do
        child.Parent = newPart
    end
    newPart.Parent = old.Parent
    -- Strip the marker so re-runs don't double-cook.
    pcall(function() newPart:SetAttribute("_DesiredCollisionFidelity", nil) end)
    old:Destroy()
    return true
end

local cooked, failed = 0, 0
for _, m in ipairs(workspace:GetDescendants()) do
    if m:IsA("MeshPart") and m:GetAttribute("_DesiredCollisionFidelity") then
        if _recookOne(m) then
            cooked = cooked + 1
        else
            failed = failed + 1
        end
    end
end

if cooked > 0 or failed > 0 then
    print(("[CollisionFidelityRecook] cooked=%d failed=%d"):format(cooked, failed))
end
'''
    return RbxScript(
        name="CollisionFidelityRecook",
        source=source,
        script_type="Script",
    )


