"""generate_prefab_packages.

Converts each Unity PrefabTemplate that gameplay scripts actually
reference into an RbxPart tree, attached to the rbxlx's
``ReplicatedStorage.Templates`` folder. Scripts then do:

    local rifle = ReplicatedStorage.Templates:WaitForChild("Rifle"):Clone()

or use the generated ``PrefabSpawner.luau`` companion module for
convenience + optional placement.

The folder name is exported as :data:`PREFAB_PACKAGES_FOLDER` so other
pipeline passes (notably ``script_coherence._fix_prefab_lookups``) can
reference the same value without duplicating the literal — the folder
legitimately lives in ReplicatedStorage and must be exempted from any
RS-to-workspace lookup rewrite.

**Filtering:** only prefabs referenced by at least one script's
serialized field (via ``serialized_field_refs``) are
emitted. Emitting every parsed prefab would bloat the rbxlx with
assets no script ever spawns. Unreferenced prefabs still expand
inline inside scene hierarchies via ``scene_converter`` — that path
isn't affected by this module.

**Inline-over-runtime compliance:** the generated PrefabSpawner is a
thin stateless helper (one ``Clone`` + property assignment). It does
not gate any gameplay and is not required — scripts can still call
``Templates:WaitForChild(...):Clone()`` directly. Per
``docs/design/inline-over-runtime-wrappers.md`` this pattern is
allowed for pure convenience helpers.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from core.roblox_types import RbxPart, RbxScript
from core.unity_types import GuidIndex, PrefabLibrary
from converter.material_mapper import MaterialMapping

log = logging.getLogger(__name__)

# Folder under ``ReplicatedStorage`` that holds the prefab templates.
# Single source of truth — referenced by:
#   - the generated PrefabSpawner.luau body in this file
#   - script_coherence._fix_prefab_lookups (exempted from the
#     RS-to-workspace rewrite, since the folder legitimately lives in RS)
PREFAB_PACKAGES_FOLDER = "Templates"


@dataclass
class PrefabPackagesResult:
    """Outcome of ``generate_prefab_packages``."""
    templates: list[RbxPart] = field(default_factory=list)
    spawner_script: RbxScript | None = None
    manifest: dict[str, Any] = field(default_factory=dict)
    unconverted: list[dict[str, str]] = field(default_factory=list)


# Companion spawner module. Generated verbatim; attached at the tail
# of write_output whenever at least one template gets emitted.
_SPAWNER_LUAU = """\
-- Auto-generated by prefab_packages
-- Thin wrapper around ReplicatedStorage.Templates:Clone() — see
-- docs/design/inline-over-runtime-wrappers.md for the policy.

local PrefabSpawner = {}

local ReplicatedStorage = game:GetService("ReplicatedStorage")

local function _templatesFolder()
\treturn ReplicatedStorage:WaitForChild("Templates")
end

function PrefabSpawner.spawn(name, parent, cframe)
\tlocal template = _templatesFolder():FindFirstChild(name)
\tif not template then
\t\twarn("[PrefabSpawner] Template not found: " .. tostring(name))
\t\treturn nil
\tend
\tlocal clone = template:Clone()
\tif cframe then
\t\tlocal primary = clone.PrimaryPart or clone:FindFirstChildWhichIsA("BasePart")
\t\tif primary then
\t\t\tclone:PivotTo(cframe)
\t\tend
\tend
\tclone.Parent = parent or workspace
\treturn clone
end

-- Returns the variant chain for a template by walking the
-- VariantParentTemplate attribute. The chain is ordered from the named
-- template up to its root parent. Useful for diagnostics and for
-- composers that need to walk the inheritance chain.
function PrefabSpawner.variantChain(name)
\tlocal chain = {name}
\tlocal seen = {[name] = true}
\tlocal cur = _templatesFolder():FindFirstChild(name)
\twhile cur do
\t\tlocal parentName = cur:GetAttribute("VariantParentTemplate")
\t\tif not parentName or seen[parentName] then break end
\t\tseen[parentName] = true
\t\ttable.insert(chain, parentName)
\t\tcur = _templatesFolder():FindFirstChild(parentName)
\tend
\treturn chain
end

return PrefabSpawner
"""


def _collect_referenced_prefab_names(
    serialized_field_refs: dict[str, dict[str, str]] | None,
) -> set[str]:
    """Extract the set of prefab names referenced by any serialized field.

    The serialized_field_refs map uses the convention from 4.9:
    prefab references are the raw prefab stem; audio references are
    ``audio:<path>``. We filter out the latter.
    """
    names: set[str] = set()
    for fields in (serialized_field_refs or {}).values():
        for _field_name, target in fields.items():
            if isinstance(target, str) and not target.startswith("audio:"):
                names.add(target)
    return names


_BASEPART_CLASSES = (
    "Part", "MeshPart", "Cylinder", "Ball", "TrussPart",
    "Seat", "VehicleSeat", "SpawnLocation",
    "WedgePart", "CornerWedgePart",
)


def _first_baseparts_in_order(part: RbxPart) -> list[RbxPart]:
    """Depth-first list of every BasePart-like descendant of ``part``.
    Children are visited in declaration order; ``part`` itself is
    excluded.
    """
    out: list[RbxPart] = []
    stack = [part]
    while stack:
        cur = stack.pop()
        if cur is not part and getattr(cur, "class_name", "Part") in _BASEPART_CLASSES:
            out.append(cur)
        # Reversed so the depth-first traversal returns
        # children in declaration order.
        for child in reversed(getattr(cur, "children", []) or []):
            stack.append(child)
    return out


# Classes that are intentionally invisible in gameplay but are still
# valid pivot anchors — e.g., SpawnLocation rendering is suppressed by
# default but the part itself is the prefab's logical root.
_TRANSPARENCY_IMMUNE = frozenset({
    "SpawnLocation", "Seat", "VehicleSeat",
})


def _is_marker_part(p: RbxPart) -> bool:
    """A marker is anything invisible (transparency >= 1) and not one
    of the transparency-immune classes (SpawnLocation/Seat/VehicleSeat).
    Visible Parts — with or without an explicit ``shape`` — are real
    geometry: Roblox renders ``shape=None`` as a default Block. The
    previous form ``Part with shape=None → marker`` over-filtered
    plain-block prefab roots.
    """
    cls = getattr(p, "class_name", None)
    transparency = getattr(p, "transparency", 0.0) or 0.0
    if transparency >= 1.0 and cls not in _TRANSPARENCY_IMMUNE:
        return True
    return False


def _find_root_anchor_part(
    part: RbxPart, *, root_name: str | None = None,
) -> RbxPart | None:
    """Pick the wrapped root geometry, or ``None`` if no clear anchor.

    Only fires on the wrapped-root shape — a Model whose direct
    children include a ``<root>_Mesh`` child produced by
    ``scene_converter._wrap_geometry_with_children_into_model``. That
    wrap shape is the one the plan's algorithm explicitly targets:
    geometry + child markers/triggers, where the geometry is the
    intended pivot anchor.

    Returns ``None`` for everything else (single-mesh templates,
    multi-submesh FBX prefabs without a wrap, primitive-only models).
    The caller then falls back to the legacy identity wipe, which
    preserves prior behaviour for those shapes — the heuristic is
    unreliable when there is no clear "wrapped root" signal.
    """
    """Pick the BasePart that represents the prefab root's geometry.

    Order of preference:
      1. A direct child named ``<root_name>_Mesh`` — the wrapped root
         geometry inserted by
         ``scene_converter._wrap_geometry_with_children_into_model``
         when a Unity node has both a mesh AND child transforms.
      2. A direct non-marker BasePart child — MeshPart, or a Part with
         primitive shape / visible transparency. Excludes invisible
         marker Parts (Origin, Muzzle, Spawn, …).
      3. Any non-marker descendant BasePart, depth-first.
      4. Any descendant BasePart at all (markers included) as a
         last-resort fallback.

    Returns ``None`` for an empty Model OR a single-part template
    (no descendants). The caller falls through to the legacy
    wipe-to-identity in that case — single-part templates' cframe
    is the part's CFrame (not a Model WorldPivot), and the wipe lets
    callers ``:Clone()`` and parent at origin without inheriting the
    template's authored source position.

    Known limitation: when a runtime script assigns
    ``clone.PrimaryPart = ...`` before ``clone:PivotTo(...)``, Roblox
    derives the pivot from ``PrimaryPart.CFrame * PrimaryPart.PivotOffset``
    and ignores the WorldPivot written here. Full resolution requires
    emitting an explicit ``Model.PrimaryPart`` referent and writing
    ``PivotOffset`` on that part — the rbxlx writer does not currently
    support either, so a small per-part drift remains for templates
    whose runtime callers set PrimaryPart eagerly.
    """
    direct = part.children or []
    # Candidates for the wrapped root child's name: the prefab's
    # current name AND the pre-rename root GameObject name. The wrap
    # function uses the GameObject's name; the caller may have since
    # renamed ``part`` to the prefab asset name.
    candidate_mesh_names = {f"{part.name}_Mesh"}
    if root_name:
        candidate_mesh_names.add(f"{root_name}_Mesh")
    for c in direct:
        if (
            getattr(c, "name", None) in candidate_mesh_names
            and getattr(c, "class_name", None) in _BASEPART_CLASSES
            and not _is_marker_part(c)
        ):
            return c
    return None


def generate_prefab_packages(
    prefab_library: PrefabLibrary | None,
    serialized_field_refs: dict[str, dict[str, str]] | None,
    guid_index: GuidIndex | None,
    material_mappings: dict[str, MaterialMapping] | None = None,
    uploaded_assets: dict[str, str] | None = None,
    include_all: bool = False,
    legacy_prefab_pivot: bool = False,
) -> PrefabPackagesResult:
    """Build ``ReplicatedStorage.Templates`` entries from Unity prefabs.

    Args:
        prefab_library: Parsed PrefabLibrary from ``unity.prefab_parser``.
        serialized_field_refs: ``{relative_cs_path: {field_name: target}}``.
            When provided, only prefabs named in any script's field
            values are emitted.
        guid_index: GUID index for resolving nested asset references.
        material_mappings: GUID → MaterialMapping for applying
            SurfaceAppearances to converted parts.
        uploaded_assets: Asset-path → rbxassetid URL map.
        include_all: When True, emit every parsed prefab regardless of
            script references. Useful for tests; off by default so
            production runs don't bloat the rbxlx.

    Returns:
        ``PrefabPackagesResult`` with the template parts, an optional
        companion spawner script, a manifest dict, and a list of
        unconverted entries for prefabs that couldn't be emitted.
    """
    result = PrefabPackagesResult()
    if prefab_library is None or not getattr(prefab_library, "prefabs", None):
        return result

    referenced = _collect_referenced_prefab_names(serialized_field_refs)
    target_set = referenced if not include_all else None

    # Lazy import to keep scene_converter out of this module's top-level
    # import graph (avoids circular-import risk during pipeline setup).
    from converter.scene_converter import _convert_prefab_node

    # Build a variant→parent name lookup so variant templates carry a
    # ``VariantParentTemplate`` attribute pointing at their source
    # prefab's name. The runtime can either clone the variant directly
    # (current path: the variant template is the fully-resolved tree)
    # or compose at clone time by cloning the parent and re-applying
    # overrides. Metadata emits regardless; the runtime composer is
    # opt-in via the PrefabSpawner module.
    variant_parent_by_name: dict[str, str] = {}
    by_guid = getattr(prefab_library, "by_guid", None) or {}
    for prefab in prefab_library.prefabs:
        if not getattr(prefab, "is_variant", False):
            continue
        parent_guid = getattr(prefab, "source_prefab_guid", None)
        if not parent_guid:
            continue
        parent = by_guid.get(parent_guid)
        if parent is None:
            continue
        parent_name = getattr(parent, "name", None)
        child_name = getattr(prefab, "name", None)
        if parent_name and child_name:
            variant_parent_by_name[child_name] = parent_name

    for template in prefab_library.prefabs:
        name = getattr(template, "name", None)
        if not name:
            continue
        if target_set is not None and name not in target_set:
            continue
        root = getattr(template, "root", None)
        if root is None:
            result.unconverted.append({
                "category": "prefab_package",
                "item": name,
                "reason": "no root node in parsed prefab",
            })
            continue
        try:
            part = _convert_prefab_node(
                root,
                guid_index=guid_index,
                material_mappings=material_mappings or {},
                uploaded_assets=uploaded_assets or {},
            )
        except Exception as exc:
            result.unconverted.append({
                "category": "prefab_package",
                "item": name,
                "reason": f"conversion raised {type(exc).__name__}: {exc}",
            })
            continue
        if part is None:
            result.unconverted.append({
                "category": "prefab_package",
                "item": name,
                "reason": "_convert_prefab_node returned None (depth limit or empty)",
            })
            continue
        # Capture the original root GameObject name before the rename
        # so the anchor picker can still find the wrapped
        # ``<root_name>_Mesh`` child that
        # ``scene_converter._wrap_geometry_with_children_into_model``
        # emitted (the wrap uses the GameObject's name, which may
        # differ from the prefab asset name).
        original_root_name = getattr(part, "name", None)
        # Force the top-level name to match the prefab name so
        # WaitForChild(name) resolves.
        part.name = name
        # Prefab template pivot:
        # - Legacy (default-off, env ``U2R_LEGACY_PREFAB_PIVOT=1``):
        #   wipe to identity. Studio's runtime then falls back to the
        #   geometric centroid for ``Model:GetPivot()``.
        # - New (default-on): set ``WorldPivot.Position`` to a root-
        #   geometry anchor's world position. ``Model:GetPivot()``
        #   then returns where the rendered root geometry sits, which
        #   matches Unity ``Instantiate(prefab, target)`` for the
        #   common case where the prefab root's Unity local is
        #   ``(0, 0, 0)`` and FBX baking adds the only offset.
        #
        # Known limitations (full resolution requires per-part Unity-
        # local-position tracking and PrimaryPart emission, neither of
        # which the converter currently has):
        # 1. When the anchor child has a non-zero Unity local position
        #    (rare for typical wrapped prefabs), ``Model:PivotTo()``
        #    lands the rendered geometry on the target instead of the
        #    Unity root. The exact formula
        #    ``WorldPivot = roblox_world - unity_local * scale``
        #    requires threading Unity local positions through the
        #    ``RbxPart`` tree, which the converter does not yet carry.
        # 2. When a runtime script assigns ``clone.PrimaryPart =``
        #    before ``clone:PivotTo(...)``, Roblox derives the pivot
        #    from PrimaryPart and ignores this WorldPivot. The rbxlx
        #    writer does not currently emit ``Model.PrimaryPart``
        #    referents, so we can't pre-pin a sane PrimaryPart.
        from core.roblox_types import RbxCFrame
        if legacy_prefab_pivot:
            part.cframe = RbxCFrame()
        else:
            anchor = _find_root_anchor_part(part, root_name=original_root_name)
            if anchor is None:
                # Empty Model / single-part template: legacy wipe.
                # ``part.cframe`` is the part's CFrame (Part/MeshPart)
                # rather than a Model WorldPivot, so wiping lets
                # callers ``:Clone()`` and parent at origin without
                # inheriting the template's authored source position.
                part.cframe = RbxCFrame()
            else:
                root_cf = part.cframe
                anchor_cf = anchor.cframe
                # Translation: anchor's world position so PivotTo lands
                # the root geometry on the target. Rotation: prefab
                # root's rotation, preserved verbatim.
                part.cframe = RbxCFrame(
                    x=anchor_cf.x, y=anchor_cf.y, z=anchor_cf.z,
                    r00=root_cf.r00, r01=root_cf.r01, r02=root_cf.r02,
                    r10=root_cf.r10, r11=root_cf.r11, r12=root_cf.r12,
                    r20=root_cf.r20, r21=root_cf.r21, r22=root_cf.r22,
                )

        # Tag variants with their parent template name so the runtime
        # spawner can compose at clone time (and so a follow-up parent-
        # template update propagates to variants).
        parent_name = variant_parent_by_name.get(name)
        if parent_name:
            part.attributes["VariantParentTemplate"] = parent_name

        result.templates.append(part)

    if result.templates:
        result.spawner_script = RbxScript(
            name="PrefabSpawner",
            source=_SPAWNER_LUAU,
            script_type="ModuleScript",
            parent_path="ReplicatedStorage",
            source_path="packages/PrefabSpawner.luau",
        )
    emitted_names = {t.name for t in result.templates}
    variant_chains = {
        name: parent
        for name, parent in variant_parent_by_name.items()
        if name in emitted_names
    }
    result.manifest = {
        "total_templates": len(result.templates),
        "emitted_names": sorted(emitted_names),
        "referenced_but_missing": sorted(referenced - emitted_names),
        # Per emitted variant, the parent template name. Lets tools
        # and the runtime composer reconstruct the inheritance chain.
        "variant_chains": variant_chains,
    }
    log.info(
        "[prefab_packages] emitted %d templates "
        "(%d referenced, %d unconverted)",
        len(result.templates), len(referenced), len(result.unconverted),
    )
    return result


def write_packages_manifest(out_dir: Path, manifest: dict[str, Any]) -> Path:
    """Persist the package manifest to ``<out>/packages/manifest.json``."""
    import json
    pkg_dir = out_dir / "packages"
    pkg_dir.mkdir(parents=True, exist_ok=True)
    path = pkg_dir / "manifest.json"
    path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    return path
