"""generate_prefab_packages.

Converts each Unity PrefabTemplate that gameplay scripts actually
reference into an RbxPart tree, attached to the rbxlx's
``ReplicatedStorage.Templates`` folder. Scripts then do:

    local rifle = ReplicatedStorage.Templates:WaitForChild("Rifle"):Clone()

or use the generated ``PrefabSpawner.luau`` companion module for
convenience + optional placement.

The folder name is exported as :data:`PREFAB_PACKAGES_FOLDER` so other
pipeline passes (notably ``script_coherence._fix_prefab_lookups``) can
reference the same value without duplicating the literal — the folder
legitimately lives in ReplicatedStorage and must be exempted from any
RS-to-workspace lookup rewrite.

**Filtering:** only prefabs referenced by at least one script's
serialized field (via ``serialized_field_refs``) are
emitted. Emitting every parsed prefab would bloat the rbxlx with
assets no script ever spawns. Unreferenced prefabs still expand
inline inside scene hierarchies via ``scene_converter`` — that path
isn't affected by this module.

**Inline-over-runtime compliance:** the generated PrefabSpawner is a
thin stateless helper (one ``Clone`` + property assignment). It does
not gate any gameplay and is not required — scripts can still call
``Templates:WaitForChild(...):Clone()`` directly. Per
``docs/design/inline-over-runtime-wrappers.md`` this pattern is
allowed for pure convenience helpers.
"""

from __future__ import annotations

import logging
from collections.abc import Mapping
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from core.roblox_types import RbxPart, RbxScript
from core.unity_types import GuidIndex, PrefabLibrary
from converter.material_mapper import MaterialMapping

log = logging.getLogger(__name__)

# Folder under ``ReplicatedStorage`` that holds the prefab templates.
# Single source of truth — referenced by:
#   - the generated PrefabSpawner.luau body in this file
#   - script_coherence._fix_prefab_lookups (exempted from the
#     RS-to-workspace rewrite, since the folder legitimately lives in RS)
PREFAB_PACKAGES_FOLDER = "Templates"


@dataclass
class PrefabPackagesResult:
    """Outcome of ``generate_prefab_packages``."""
    templates: list[RbxPart] = field(default_factory=list)
    spawner_script: RbxScript | None = None
    manifest: dict[str, Any] = field(default_factory=dict)
    unconverted: list[dict[str, str]] = field(default_factory=list)


# Companion spawner module. Generated verbatim; attached at the tail
# of write_output whenever at least one template gets emitted.
_SPAWNER_LUAU = """\
-- Auto-generated by prefab_packages
-- Thin wrapper around ReplicatedStorage.Templates:Clone() — see
-- docs/design/inline-over-runtime-wrappers.md for the policy.

local PrefabSpawner = {}

local ReplicatedStorage = game:GetService("ReplicatedStorage")

local function _templatesFolder()
\treturn ReplicatedStorage:WaitForChild("Templates")
end

function PrefabSpawner.spawn(name, parent, cframe)
\tlocal template = _templatesFolder():FindFirstChild(name)
\tif not template then
\t\twarn("[PrefabSpawner] Template not found: " .. tostring(name))
\t\treturn nil
\tend
\tlocal clone = template:Clone()
\tif cframe then
\t\tlocal primary = clone.PrimaryPart or clone:FindFirstChildWhichIsA("BasePart")
\t\tif primary then
\t\t\tclone:PivotTo(cframe)
\t\tend
\tend
\tclone.Parent = parent or workspace
\treturn clone
end

-- Returns the variant chain for a template by walking the
-- VariantParentTemplate attribute. The chain is ordered from the named
-- template up to its root parent. Useful for diagnostics and for
-- composers that need to walk the inheritance chain.
function PrefabSpawner.variantChain(name)
\tlocal chain = {name}
\tlocal seen = {[name] = true}
\tlocal cur = _templatesFolder():FindFirstChild(name)
\twhile cur do
\t\tlocal parentName = cur:GetAttribute("VariantParentTemplate")
\t\tif not parentName or seen[parentName] then break end
\t\tseen[parentName] = true
\t\ttable.insert(chain, parentName)
\t\tcur = _templatesFolder():FindFirstChild(parentName)
\tend
\treturn chain
end

return PrefabSpawner
"""


def _collect_referenced_prefab_names(
    serialized_field_refs: dict[str, dict[str, str]] | None,
) -> set[str]:
    """Extract the set of prefab names referenced by any serialized field.

    The serialized_field_refs map uses the convention from 4.9:
    prefab references are the raw prefab stem; audio references are
    ``audio:<path>``. We filter out the latter.
    """
    names: set[str] = set()
    for fields in (serialized_field_refs or {}).values():
        for _field_name, target in fields.items():
            if isinstance(target, str) and not target.startswith("audio:"):
                names.add(target)
    return names


def _guid6_of(prefab_id: str) -> str | None:
    """Return the first 6 hex chars of ``prefab_id``'s leading guid, or None.

    A ``prefab_id`` is ``"<guid>:<rel>"`` or a colon-free bare guid. Returns
    None when no guid can be detected (a colon-free path, or a non-hex head) —
    the caller then keeps the bare name (cannot disambiguate).
    """
    head, sep, _rest = prefab_id.partition(":")
    if sep:
        if not head or not all(c in "0123456789abcdefABCDEF" for c in head):
            return None
        return head[:6]
    # Colon-free: only a canonical 32-hex guid counts; a bare path does not.
    if len(head) == 32 and all(c in "0123456789abcdefABCDEF" for c in head):
        return head[:6]
    return None


def resolve_template_child_names(
    prefab_bases: Mapping[str, str],
) -> dict[str, str]:
    """Resolve each prefab's on-disk Templates child name, disambiguating collisions.

    The caller must pass only the EMITTED prefab set (``{prefab_id:
    bare_template_name}``); scoping to it is load-bearing, so a non-emitted
    same-base sibling never forces a suffix.

    Returns ``{prefab_id: resolved_child_name}``: a base unique within the input
    keeps its bare name; a base shared by 2+ prefabs becomes ``f"{base}__{guid6}"``
    (or the bare name when the prefab_id has no guid to disambiguate by). Pure
    and idempotent — a function of the input map alone.
    """
    by_base: dict[str, list[str]] = {}
    for prefab_id, base in prefab_bases.items():
        by_base.setdefault(base, []).append(prefab_id)

    resolved: dict[str, str] = {}
    for base, ids in by_base.items():
        if len(ids) == 1:
            resolved[ids[0]] = base
            continue
        for prefab_id in ids:
            guid6 = _guid6_of(prefab_id)
            # No guid → cannot disambiguate → keep the bare name.
            resolved[prefab_id] = f"{base}__{guid6}" if guid6 else base
    return resolved


def select_emitted_prefab_ids(
    prefab_library: PrefabLibrary | None,
    serialized_field_refs: dict[str, dict[str, str]] | None,
    addressable_prefab_ids: set[str] | None,
    guid_index: GuidIndex | None = None,
) -> set[str]:
    """prefab_ids that will be emitted to ``ReplicatedStorage.Templates``.

    The bare-name ``referenced`` selection (prefabs whose ``template.name`` is in
    ``_collect_referenced_prefab_names``) unioned with ``addressable_prefab_ids``.
    Shared by the planner (collision domain) and the emitter so the two target
    sets never diverge. Each prefab_id is derived the same way the emitter does,
    via ``scene_converter._prefab_stable_id``; ``guid_index`` is optional (omitted
    → ids fall back to guid-less posix paths).
    """
    if prefab_library is None or not getattr(prefab_library, "prefabs", None):
        return set(addressable_prefab_ids or set())

    referenced = _collect_referenced_prefab_names(serialized_field_refs)

    # Lazy import (mirrors generate_prefab_packages) to avoid a top-level
    # scene_converter import cycle during pipeline setup.
    from converter.scene_converter import _prefab_stable_id

    by_guid = getattr(prefab_library, "by_guid", None) or {}
    project_root = (
        getattr(guid_index, "project_root", None) if guid_index else None
    )

    emitted: set[str] = set()
    for template in prefab_library.prefabs:
        name = getattr(template, "name", None)
        if not name or name not in referenced:
            continue
        prefab_id = _prefab_stable_id(
            template, guid_index, by_guid, project_root,
        )
        emitted.add(prefab_id)

    emitted |= set(addressable_prefab_ids or set())
    return emitted


_BASEPART_CLASSES = (
    "Part", "MeshPart", "Cylinder", "Ball", "TrussPart",
    "Seat", "VehicleSeat", "SpawnLocation",
    "WedgePart", "CornerWedgePart",
)


def _first_baseparts_in_order(part: RbxPart) -> list[RbxPart]:
    """Depth-first list of every BasePart-like descendant of ``part``.
    Children are visited in declaration order; ``part`` itself is
    excluded.
    """
    out: list[RbxPart] = []
    stack = [part]
    while stack:
        cur = stack.pop()
        if cur is not part and getattr(cur, "class_name", "Part") in _BASEPART_CLASSES:
            out.append(cur)
        # Reversed so the depth-first traversal returns
        # children in declaration order.
        for child in reversed(getattr(cur, "children", []) or []):
            stack.append(child)
    return out


# Classes that are intentionally invisible in gameplay but are still
# valid pivot anchors — e.g., SpawnLocation rendering is suppressed by
# default but the part itself is the prefab's logical root.
_TRANSPARENCY_IMMUNE = frozenset({
    "SpawnLocation", "Seat", "VehicleSeat",
})


def _is_marker_part(p: RbxPart) -> bool:
    """A marker is anything invisible (transparency >= 1) and not one
    of the transparency-immune classes (SpawnLocation/Seat/VehicleSeat).
    Visible Parts — with or without an explicit ``shape`` — are real
    geometry: Roblox renders ``shape=None`` as a default Block. The
    previous form ``Part with shape=None → marker`` over-filtered
    plain-block prefab roots.
    """
    cls = getattr(p, "class_name", None)
    transparency = getattr(p, "transparency", 0.0) or 0.0
    if transparency >= 1.0 and cls not in _TRANSPARENCY_IMMUNE:
        return True
    return False


def _find_root_anchor_part(
    part: RbxPart, *, root_name: str | None = None,
) -> RbxPart | None:
    """Pick the wrapped root geometry, or ``None`` if no clear anchor.

    Only fires on the wrapped-root shape — a Model whose direct
    children include a ``<root>_Mesh`` child produced by
    ``scene_converter._wrap_geometry_with_children_into_model``. That
    wrap shape is the one the plan's algorithm explicitly targets:
    geometry + child markers/triggers, where the geometry is the
    intended pivot anchor.

    Returns ``None`` for everything else (single-mesh templates,
    multi-submesh FBX prefabs without a wrap, primitive-only models).
    The caller then falls back to the legacy identity wipe, which
    preserves prior behaviour for those shapes — the heuristic is
    unreliable when there is no clear "wrapped root" signal.
    """
    direct = part.children or []
    # Candidates for the wrapped root child's name: the prefab's
    # current name AND the pre-rename root GameObject name. The wrap
    # function uses the GameObject's name; the caller may have since
    # renamed ``part`` to the prefab asset name.
    candidate_mesh_names = {f"{part.name}_Mesh"}
    if root_name:
        candidate_mesh_names.add(f"{root_name}_Mesh")
    for c in direct:
        if (
            getattr(c, "name", None) in candidate_mesh_names
            and getattr(c, "class_name", None) in _BASEPART_CLASSES
            and not _is_marker_part(c)
        ):
            return c
    return None


def generate_prefab_packages(
    prefab_library: PrefabLibrary | None,
    serialized_field_refs: dict[str, dict[str, str]] | None,
    guid_index: GuidIndex | None,
    material_mappings: dict[str, MaterialMapping] | None = None,
    uploaded_assets: dict[str, str] | None = None,
    include_all: bool = False,
    legacy_prefab_pivot: bool = False,
    resolved_template_names: Mapping[str, str] | None = None,
    addressable_prefab_ids: set[str] | None = None,
) -> PrefabPackagesResult:
    """Build ``ReplicatedStorage.Templates`` entries from Unity prefabs.

    Args:
        prefab_library: Parsed PrefabLibrary from ``unity.prefab_parser``.
        serialized_field_refs: ``{relative_cs_path: {field_name: target}}``.
            When provided, only prefabs named in any script's field
            values are emitted.
        guid_index: GUID index for resolving nested asset references.
        material_mappings: GUID → MaterialMapping for applying
            SurfaceAppearances to converted parts.
        uploaded_assets: Asset-path → rbxassetid URL map.
        include_all: When True, emit every parsed prefab regardless of
            script references. Useful for tests; off by default so
            production runs don't bloat the rbxlx.
        resolved_template_names: ``{prefab_id: resolved_child_name}`` computed
            once by ``plan_scene_runtime``. The emitter reads the Templates
            child name from this map rather than recomputing it; ``None`` /
            empty (single-mode, no planner) → bare name fallback.
        addressable_prefab_ids: prefab_ids referenced by the Addressables block,
            unioned with the bare-name ``referenced`` selection (via
            ``select_emitted_prefab_ids``) to form the emission target set.

    Returns:
        ``PrefabPackagesResult`` with the template parts, an optional
        companion spawner script, a manifest dict, and a list of
        unconverted entries for prefabs that couldn't be emitted.
    """
    result = PrefabPackagesResult()
    if prefab_library is None or not getattr(prefab_library, "prefabs", None):
        return result

    referenced = _collect_referenced_prefab_names(serialized_field_refs)
    resolved_names: Mapping[str, str] = resolved_template_names or {}
    addr_ids: set[str] = set(addressable_prefab_ids or set())

    # Lazy import to keep scene_converter out of this module's top-level
    # import graph (avoids circular-import risk during pipeline setup).
    # ``_prefab_stable_id`` produces the same ``<guid>:<rel_path>``
    # namespace the scene-instantiation path uses, so a runtime-spawned
    # clone's ``_SceneRuntimeId`` matches the planner's ``game_object_id``
    # for the same prefab template (PR2 follow-up §6).
    from converter.scene_converter import (
        _convert_prefab_node,
        _prefab_stable_id,
    )

    # Project root used by ``_prefab_stable_id`` to derive a project-
    # relative path for the namespace. None when no GUID index is
    # supplied (e.g. tests) — ``_prefab_stable_id`` then returns an
    # empty namespace and stamping no-ops, matching the conservative
    # ``_scene_namespace`` rule.
    project_root = (
        getattr(guid_index, "project_root", None) if guid_index else None
    )

    # Build a variant→parent name lookup so variant templates carry a
    # ``VariantParentTemplate`` attribute pointing at their source
    # prefab's name. The runtime can either clone the variant directly
    # (current path: the variant template is the fully-resolved tree)
    # or compose at clone time by cloning the parent and re-applying
    # overrides. Metadata emits regardless; the runtime composer is
    # opt-in via the PrefabSpawner module.
    variant_parent_by_name: dict[str, str] = {}
    by_guid = getattr(prefab_library, "by_guid", None) or {}
    for prefab in prefab_library.prefabs:
        if not getattr(prefab, "is_variant", False):
            continue
        parent_guid = getattr(prefab, "source_prefab_guid", None)
        if not parent_guid:
            continue
        parent = by_guid.get(parent_guid)
        if parent is None:
            continue
        parent_name = getattr(parent, "name", None)
        child_name = getattr(prefab, "name", None)
        if parent_name and child_name:
            variant_parent_by_name[child_name] = parent_name

    # Emission target: bare-name ``referenced`` UNION the addressable prefab_ids.
    # The bare leg stays a NAME test (not an id test): guid-less / single-mode
    # collapses every prefab_id to one value, so an id-only test would over-emit.
    def _is_emitted(name: str, prefab_id: str) -> bool:
        if include_all:
            return True
        return name in referenced or prefab_id in addr_ids

    # Bare base names that collide within the emitted set. On a resolved-name
    # miss a colliding base can't bare-fallback (it would clone the wrong
    # template), so it WARNs + skips; a unique base falls back harmlessly.
    _base_counts: dict[str, int] = {}
    for _tmpl in prefab_library.prefabs:
        _nm = getattr(_tmpl, "name", None)
        if not _nm:
            continue
        _ns = _prefab_stable_id(_tmpl, guid_index, by_guid, project_root)
        if not _is_emitted(_nm, _ns):
            continue
        _base_counts[_nm] = _base_counts.get(_nm, 0) + 1
    colliding_bare_bases = {b for b, c in _base_counts.items() if c > 1}

    # Variant-parent base-name uniqueness check. ``VariantParentTemplate`` stays
    # a BARE parent name (the runtime composer finds its source by it), which is
    # unambiguous only while no two emitted prefabs share that parent base. If
    # two do, the bare name can't pick the right source template → WARN (fail-
    # soft, a real collision is a follow-up rather than a silent break).
    _colliding_variant_parents = sorted(
        parent_name
        for parent_name in set(variant_parent_by_name.values())
        if parent_name in colliding_bare_bases
    )
    if _colliding_variant_parents:
        log.warning(
            "[prefab_packages] variant-parent base name(s) %s collide among "
            "emitted prefabs; the bare VariantParentTemplate metadata is "
            "ambiguous and may resolve the wrong source template",
            _colliding_variant_parents,
        )

    # Track the BARE base name of every emitted template so the
    # ``referenced_but_missing`` manifest compares against bare names, not the
    # RESOLVED (possibly suffixed) ``t.name`` (D15 fix). A colliding-but-emitted
    # base would otherwise be falsely reported missing.
    emitted_base_names: set[str] = set()

    for template in prefab_library.prefabs:
        name = getattr(template, "name", None)
        if not name:
            continue
        # Stable prefab namespace for ``_SceneRuntimeId`` stamping —
        # mirrors ``_convert_prefab_instance``'s ``prefab_namespace`` so
        # a clone produced by ``host.instantiatePrefab`` carries the same
        # ``<guid>:<rel_path>:<file_id>`` lookup key the planner emits
        # for the prefab's instances. Without this, the runtime's
        # ``resolveCloneChild(clone, ns_goid)`` walk misses every
        # descendant and components boot with ``self.gameObject = nil``
        # (PR2 follow-up §6, observed as "no touch part on nil" at the
        # 1Hz turret-bullet spawn cadence in SimpleFPS).
        #
        # Computed before the skip check: emission unions the addressable
        # prefab_ids, not just the bare ``referenced`` names.
        prefab_namespace = _prefab_stable_id(
            template, guid_index, by_guid, project_root,
        )
        if not _is_emitted(name, prefab_namespace):
            continue
        # Read the Templates child name from the planner's
        # ``resolved_template_names`` (do not recompute). On a miss, a unique
        # base bare-falls-back; a colliding base WARNs + skips (bare-fallback
        # would clone the wrong template).
        child_name = resolved_names.get(prefab_namespace)
        if child_name is None:
            if name in colliding_bare_bases:
                log.warning(
                    "[prefab_packages] no resolved name for colliding prefab "
                    "%r (id %r); skipping to avoid cloning the wrong template",
                    name, prefab_namespace,
                )
                continue
            child_name = name
        root = getattr(template, "root", None)
        if root is None:
            result.unconverted.append({
                "category": "prefab_package",
                "item": name,
                "reason": "no root node in parsed prefab",
            })
            continue
        try:
            part = _convert_prefab_node(
                root,
                guid_index=guid_index,
                material_mappings=material_mappings or {},
                uploaded_assets=uploaded_assets or {},
                runtime_namespace=prefab_namespace,
            )
        except Exception as exc:
            result.unconverted.append({
                "category": "prefab_package",
                "item": name,
                "reason": f"conversion raised {type(exc).__name__}: {exc}",
            })
            continue
        if part is None:
            result.unconverted.append({
                "category": "prefab_package",
                "item": name,
                "reason": "_convert_prefab_node returned None (depth limit or empty)",
            })
            continue
        # Capture the original root GameObject name before the rename
        # so the anchor picker can still find the wrapped
        # ``<root_name>_Mesh`` child that
        # ``scene_converter._wrap_geometry_with_children_into_model``
        # emitted (the wrap uses the GameObject's name, which may
        # differ from the prefab asset name).
        original_root_name = getattr(part, "name", None)
        # Name the top-level part the resolved Templates child name so
        # ``WaitForChild(child_name)`` resolves and colliding bases stay
        # distinct. For a non-colliding prefab ``child_name == name``.
        part.name = child_name
        emitted_base_names.add(name)
        # Prefab template pivot. Legacy (``U2R_LEGACY_PREFAB_PIVOT=1``):
        # wipe to identity. New (default-on): set ``WorldPivot.Position``
        # to a root-geometry anchor's world position so ``Model:GetPivot()``
        # matches Unity ``Instantiate(prefab, target)``.
        #
        # Known limitations (no per-part Unity-local tracking, no PrimaryPart emission):
        # 1. A non-zero Unity local position on the anchor child (rare for wrapped
        #    prefabs) lands geometry on the target, not the Unity root; the exact
        #    ``WorldPivot = roblox_world - unity_local * scale`` fix needs Unity locals
        #    threaded through the ``RbxPart`` tree, which the converter does not carry.
        # 2. A runtime script that assigns ``clone.PrimaryPart =`` before
        #    ``clone:PivotTo(...)`` makes Roblox derive the pivot from PrimaryPart and
        #    ignore this WorldPivot. The rbxlx writer does not emit ``Model.PrimaryPart``
        #    referents, so we can't pre-pin a sane PrimaryPart.
        from core.roblox_types import RbxCFrame
        if legacy_prefab_pivot:
            part.cframe = RbxCFrame()
        else:
            anchor = _find_root_anchor_part(part, root_name=original_root_name)
            if anchor is None:
                # Empty Model / single-part template: legacy wipe.
                # ``part.cframe`` is the part's CFrame (Part/MeshPart)
                # rather than a Model WorldPivot, so wiping lets
                # callers ``:Clone()`` and parent at origin without
                # inheriting the template's authored source position.
                part.cframe = RbxCFrame()
            else:
                root_cf = part.cframe
                anchor_cf = anchor.cframe
                # Translation: anchor's world position so PivotTo lands
                # the root geometry on the target. Rotation: prefab
                # root's rotation, preserved verbatim.
                part.cframe = RbxCFrame(
                    x=anchor_cf.x, y=anchor_cf.y, z=anchor_cf.z,
                    r00=root_cf.r00, r01=root_cf.r01, r02=root_cf.r02,
                    r10=root_cf.r10, r11=root_cf.r11, r12=root_cf.r12,
                    r20=root_cf.r20, r21=root_cf.r21, r22=root_cf.r22,
                )

        # Tag variants with their parent template name so the runtime
        # spawner can compose at clone time (and so a follow-up parent-
        # template update propagates to variants).
        parent_name = variant_parent_by_name.get(name)
        if parent_name:
            part.attributes["VariantParentTemplate"] = parent_name

        result.templates.append(part)

    if result.templates:
        # Phase 2a slice 5 round 3: stamp ``intrinsic_script_type`` at
        # construction. ``_generate_prefab_packages`` runs AFTER
        # ``_classify_storage``, but ``classify_storage`` only coerces
        # ``Script→LocalScript`` — never touches ModuleScript — so the
        # ``ModuleScript`` literal here remains the intrinsic value
        # regardless of phase order. Stamp it explicitly so resume
        # rehydration doesn't fall back to the heuristic for a known
        # value.
        result.spawner_script = RbxScript(
            name="PrefabSpawner",
            source=_SPAWNER_LUAU,
            script_type="ModuleScript",
            intrinsic_script_type="ModuleScript",
            parent_path="ReplicatedStorage",
            source_path="packages/PrefabSpawner.luau",
        )
    # Resolved child names actually emitted (possibly suffixed).
    emitted_names = {t.name for t in result.templates}
    # Two colliding bases whose first-6 guid hex are equal would resolve to the
    # SAME suffixed name → a real on-disk collision. Detect + log it.
    if len(emitted_names) != len(result.templates):
        name_counts: dict[str, int] = {}
        for t in result.templates:
            name_counts[t.name] = name_counts.get(t.name, 0) + 1
        dupes = sorted(n for n, c in name_counts.items() if c > 1)
        log.warning(
            "[prefab_packages] post-resolve child-name collision among "
            "emitted templates: %s — clones may resolve the wrong template",
            dupes,
        )
    # ``referenced_but_missing`` and variant chains compare against the BARE
    # base names of emitted templates, not the resolved (possibly suffixed)
    # ``t.name`` — else a colliding-but-emitted base reports as missing.
    variant_chains = {
        name: parent
        for name, parent in variant_parent_by_name.items()
        if name in emitted_base_names
    }
    result.manifest = {
        "total_templates": len(result.templates),
        "emitted_count": len(result.templates),
        "total_prefabs": len(prefab_library.prefabs),
        "addressable_referenced": len(addressable_prefab_ids or set()),
        "emitted_names": sorted(emitted_names),
        "referenced_but_missing": sorted(referenced - emitted_base_names),
        # Per emitted variant, the parent template name. Lets tools
        # and the runtime composer reconstruct the inheritance chain.
        "variant_chains": variant_chains,
    }
    log.info(
        "[prefab_packages] emitted %d/%d templates "
        "(%d referenced, %d addressable, %d unconverted)",
        len(result.templates), len(prefab_library.prefabs),
        len(referenced), len(addressable_prefab_ids or set()),
        len(result.unconverted),
    )
    return result


def write_packages_manifest(out_dir: Path, manifest: dict[str, Any]) -> Path:
    """Persist the package manifest to ``<out>/packages/manifest.json``."""
    import json
    pkg_dir = out_dir / "packages"
    pkg_dir.mkdir(parents=True, exist_ok=True)
    path = pkg_dir / "manifest.json"
    path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    return path
