"""generate_prefab_packages.

Converts each Unity PrefabTemplate that gameplay scripts actually
reference into an RbxPart tree, attached to the rbxlx's
``ReplicatedStorage.Templates`` folder. Scripts then do:

    local rifle = ReplicatedStorage.Templates:WaitForChild("Rifle"):Clone()

or use the generated ``PrefabSpawner.luau`` companion module for
convenience + optional placement.

The folder name is exported as :data:`PREFAB_PACKAGES_FOLDER` so other
pipeline passes (notably ``script_coherence._fix_prefab_lookups``) can
reference the same value without duplicating the literal — the folder
legitimately lives in ReplicatedStorage and must be exempted from any
RS-to-workspace lookup rewrite.

**Filtering:** only prefabs referenced by at least one script's
serialized field (via ``serialized_field_refs``) are
emitted. Emitting every parsed prefab would bloat the rbxlx with
assets no script ever spawns. Unreferenced prefabs still expand
inline inside scene hierarchies via ``scene_converter`` — that path
isn't affected by this module.

**Inline-over-runtime compliance:** the generated PrefabSpawner is a
thin stateless helper (one ``Clone`` + property assignment). It does
not gate any gameplay and is not required — scripts can still call
``Templates:WaitForChild(...):Clone()`` directly. Per
``docs/design/inline-over-runtime-wrappers.md`` this pattern is
allowed for pure convenience helpers.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from core.roblox_types import RbxPart, RbxScript
from core.unity_types import GuidIndex, PrefabLibrary
from converter.material_mapper import MaterialMapping

log = logging.getLogger(__name__)

# Folder under ``ReplicatedStorage`` that holds the prefab templates.
# Single source of truth — referenced by:
#   - the generated PrefabSpawner.luau body in this file
#   - script_coherence._fix_prefab_lookups (exempted from the
#     RS-to-workspace rewrite, since the folder legitimately lives in RS)
PREFAB_PACKAGES_FOLDER = "Templates"


@dataclass
class PrefabPackagesResult:
    """Outcome of ``generate_prefab_packages``."""
    templates: list[RbxPart] = field(default_factory=list)
    spawner_script: RbxScript | None = None
    manifest: dict[str, Any] = field(default_factory=dict)
    unconverted: list[dict[str, str]] = field(default_factory=list)


# Companion spawner module. Generated verbatim; attached at the tail
# of write_output whenever at least one template gets emitted.
_SPAWNER_LUAU = """\
-- Auto-generated by prefab_packages
-- Thin wrapper around ReplicatedStorage.Templates:Clone() — see
-- docs/design/inline-over-runtime-wrappers.md for the policy.

local PrefabSpawner = {}

local ReplicatedStorage = game:GetService("ReplicatedStorage")

local function _templatesFolder()
\treturn ReplicatedStorage:WaitForChild("Templates")
end

function PrefabSpawner.spawn(name, parent, cframe)
\tlocal template = _templatesFolder():FindFirstChild(name)
\tif not template then
\t\twarn("[PrefabSpawner] Template not found: " .. tostring(name))
\t\treturn nil
\tend
\tlocal clone = template:Clone()
\tif cframe then
\t\tlocal primary = clone.PrimaryPart or clone:FindFirstChildWhichIsA("BasePart")
\t\tif primary then
\t\t\tclone:PivotTo(cframe)
\t\tend
\tend
\tclone.Parent = parent or workspace
\treturn clone
end

-- Returns the variant chain for a template by walking the
-- VariantParentTemplate attribute. The chain is ordered from the named
-- template up to its root parent. Useful for diagnostics and for
-- composers that need to walk the inheritance chain.
function PrefabSpawner.variantChain(name)
\tlocal chain = {name}
\tlocal seen = {[name] = true}
\tlocal cur = _templatesFolder():FindFirstChild(name)
\twhile cur do
\t\tlocal parentName = cur:GetAttribute("VariantParentTemplate")
\t\tif not parentName or seen[parentName] then break end
\t\tseen[parentName] = true
\t\ttable.insert(chain, parentName)
\t\tcur = _templatesFolder():FindFirstChild(parentName)
\tend
\treturn chain
end

return PrefabSpawner
"""


def _collect_referenced_prefab_names(
    serialized_field_refs: dict[str, dict[str, str]] | None,
) -> set[str]:
    """Extract the set of prefab names referenced by any serialized field.

    The serialized_field_refs map uses the convention from 4.9:
    prefab references are the raw prefab stem; audio references are
    ``audio:<path>``. We filter out the latter.
    """
    names: set[str] = set()
    for fields in (serialized_field_refs or {}).values():
        for _field_name, target in fields.items():
            if isinstance(target, str) and not target.startswith("audio:"):
                names.add(target)
    return names


def generate_prefab_packages(
    prefab_library: PrefabLibrary | None,
    serialized_field_refs: dict[str, dict[str, str]] | None,
    guid_index: GuidIndex | None,
    material_mappings: dict[str, MaterialMapping] | None = None,
    uploaded_assets: dict[str, str] | None = None,
    include_all: bool = False,
) -> PrefabPackagesResult:
    """Build ``ReplicatedStorage.Templates`` entries from Unity prefabs.

    Args:
        prefab_library: Parsed PrefabLibrary from ``unity.prefab_parser``.
        serialized_field_refs: ``{relative_cs_path: {field_name: target}}``.
            When provided, only prefabs named in any script's field
            values are emitted.
        guid_index: GUID index for resolving nested asset references.
        material_mappings: GUID → MaterialMapping for applying
            SurfaceAppearances to converted parts.
        uploaded_assets: Asset-path → rbxassetid URL map.
        include_all: When True, emit every parsed prefab regardless of
            script references. Useful for tests; off by default so
            production runs don't bloat the rbxlx.

    Returns:
        ``PrefabPackagesResult`` with the template parts, an optional
        companion spawner script, a manifest dict, and a list of
        unconverted entries for prefabs that couldn't be emitted.
    """
    result = PrefabPackagesResult()
    if prefab_library is None or not getattr(prefab_library, "prefabs", None):
        return result

    referenced = _collect_referenced_prefab_names(serialized_field_refs)
    target_set = referenced if not include_all else None

    # Lazy import to keep scene_converter out of this module's top-level
    # import graph (avoids circular-import risk during pipeline setup).
    from converter.scene_converter import _convert_prefab_node

    # Build a variant→parent name lookup so variant templates carry a
    # ``VariantParentTemplate`` attribute pointing at their source
    # prefab's name. The runtime can either clone the variant directly
    # (current path: the variant template is the fully-resolved tree)
    # or compose at clone time by cloning the parent and re-applying
    # overrides. Metadata emits regardless; the runtime composer is
    # opt-in via the PrefabSpawner module.
    variant_parent_by_name: dict[str, str] = {}
    by_guid = getattr(prefab_library, "by_guid", None) or {}
    for prefab in prefab_library.prefabs:
        if not getattr(prefab, "is_variant", False):
            continue
        parent_guid = getattr(prefab, "source_prefab_guid", None)
        if not parent_guid:
            continue
        parent = by_guid.get(parent_guid)
        if parent is None:
            continue
        parent_name = getattr(parent, "name", None)
        child_name = getattr(prefab, "name", None)
        if parent_name and child_name:
            variant_parent_by_name[child_name] = parent_name

    for template in prefab_library.prefabs:
        name = getattr(template, "name", None)
        if not name:
            continue
        if target_set is not None and name not in target_set:
            continue
        root = getattr(template, "root", None)
        if root is None:
            result.unconverted.append({
                "category": "prefab_package",
                "item": name,
                "reason": "no root node in parsed prefab",
            })
            continue
        try:
            part = _convert_prefab_node(
                root,
                guid_index=guid_index,
                material_mappings=material_mappings or {},
                uploaded_assets=uploaded_assets or {},
            )
        except Exception as exc:
            result.unconverted.append({
                "category": "prefab_package",
                "item": name,
                "reason": f"conversion raised {type(exc).__name__}: {exc}",
            })
            continue
        if part is None:
            result.unconverted.append({
                "category": "prefab_package",
                "item": name,
                "reason": "_convert_prefab_node returned None (depth limit or empty)",
            })
            continue
        # Force the top-level name to match the prefab name so
        # WaitForChild(name) resolves.
        part.name = name
        # Prefabs live at (0, 0, 0) as templates — scripts set CFrame
        # on clone. Strip any authored world-space translation the
        # prefab parser may have preserved.
        from core.roblox_types import RbxCFrame
        part.cframe = RbxCFrame()

        # Tag variants with their parent template name so the runtime
        # spawner can compose at clone time (and so a follow-up parent-
        # template update propagates to variants).
        parent_name = variant_parent_by_name.get(name)
        if parent_name:
            part.attributes["VariantParentTemplate"] = parent_name

        result.templates.append(part)

    if result.templates:
        result.spawner_script = RbxScript(
            name="PrefabSpawner",
            source=_SPAWNER_LUAU,
            script_type="ModuleScript",
            parent_path="ReplicatedStorage",
            source_path="packages/PrefabSpawner.luau",
        )
    emitted_names = {t.name for t in result.templates}
    variant_chains = {
        name: parent
        for name, parent in variant_parent_by_name.items()
        if name in emitted_names
    }
    result.manifest = {
        "total_templates": len(result.templates),
        "emitted_names": sorted(emitted_names),
        "referenced_but_missing": sorted(referenced - emitted_names),
        # Per emitted variant, the parent template name. Lets tools
        # and the runtime composer reconstruct the inheritance chain.
        "variant_chains": variant_chains,
    }
    log.info(
        "[prefab_packages] emitted %d templates "
        "(%d referenced, %d unconverted)",
        len(result.templates), len(referenced), len(result.unconverted),
    )
    return result


def write_packages_manifest(out_dir: Path, manifest: dict[str, Any]) -> Path:
    """Persist the package manifest to ``<out>/packages/manifest.json``."""
    import json
    pkg_dir = out_dir / "packages"
    pkg_dir.mkdir(parents=True, exist_ok=True)
    path = pkg_dir / "manifest.json"
    path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    return path
