"""Loader for the vendored Roblox callable-member corpus.

The corpus (``data/roblox_callable_members.json``) is a flat union of every
callable (method) name in the official Roblox API dump. It is regenerated by
``tools/refresh_roblox_corpus.py``. This module exposes a read-only query API
over the snapshot, loaded once and cached at module scope.
"""

from __future__ import annotations

import json
from pathlib import Path

_SNAPSHOT_PATH = Path(__file__).resolve().parent / "data" / "roblox_callable_members.json"


class _Corpus:
    """Immutable in-memory view of the snapshot."""

    __slots__ = ("version", "members")

    def __init__(self, version: str, members: frozenset[str]) -> None:
        self.version = version
        self.members = members


def _load_snapshot() -> _Corpus:
    raw = json.loads(_SNAPSHOT_PATH.read_text(encoding="utf-8"))
    if not isinstance(raw, dict):
        raise ValueError(f"corpus snapshot is not a JSON object: {_SNAPSHOT_PATH}")

    raw_version = raw.get("apiDumpVersion")
    version = raw_version if isinstance(raw_version, str) else ""

    raw_members = raw.get("callableMembers")
    if not isinstance(raw_members, list):
        raise ValueError(f"corpus snapshot has no 'callableMembers' list: {_SNAPSHOT_PATH}")
    members = frozenset(m for m in raw_members if isinstance(m, str))

    return _Corpus(version=version, members=members)


# Load once at import; the snapshot is a committed, read-only data file.
_CORPUS: _Corpus = _load_snapshot()


def is_callable_member(name: str) -> bool:
    """True iff ``name`` is a callable (method) name in the corpus snapshot."""
    return name in _CORPUS.members


def corpus_version() -> str:
    """The ``apiDumpVersion`` recorded in the snapshot."""
    return _CORPUS.version
